### ISSUE TITLE
TextLayer   does not respond to changes in the [textLayer] parameter

### ISSUE THREAD

**Issue by pauljohnleonard** [stephanrauh/ngx-extended-pdf-viewer#1004]
**Describe the bug**

The changing the parameter textLayer   e.g. [textLayer]="textLayer"  does not seem to have any effect.  I was hoping setting it false would remove the layer.  

**Version info**

- Version of ngx-extended-pdf-viewer  "10.5.0-alpha.0",

**Addditional info **

I realise that this might be the intended behaviour in which case I will find a work around.
I presume that if I need a text layer then I must provide an initial value of true for this ?

**Comment by stephanrauh** [comment]
Most of the time I've got the opposite problem: I need the text layer, but it doesn't render for some reason. :)

Please tell me what you're doing, precisely:
- Do you switch to [textLayer]="false" after opening the PDF viewer? I didn't add `[textLayer]` to the `ngOnChanges()` method, so it doesn't change anything after the initialization phase.
- Do you start with `[textLayer]="false" from start, only to observe the text layer is there despite trying to de-activate it?

**Comment by pauljohnleonard** [comment]
"so it doesn't change anything after the initialization phase."

OK that explains the behaviour. 

No worries, I will start off with it true then find the DOM element and switch it on/off in my code. (display:none). 

FYI I am trying to implement text selection for my annotations.   I also need to interact with a copy of the canvas to do the drawing mode so I need to switch the text layer on and off .

**Comment by stephanrauh** [comment]
I see. Just in case you're interested, here's some technical background:

As you may or may not know, I'm using pdf.js as a base library. That's the PDF viewer of Firefox. That, in turn, means that every feature we're using has been developed for Firefox, and nothing else. Demand a non-Firefox feature from the pdf.js team, and you're almost certainly rejected. That's OK, because it's a fine viewer, but it also amounts to a couple of limitations.

One of them being toggling the text layer. Firefox doesn't need such a feature. Truth to tell, I believe Firefox always activates the text layer. Deactivating the text layer is one of the hidden features I've unlocked to you, but there's no official support (apart from my humble efforts). 

So I don't have a clue what happens if I were to toggle the text layer after the initialization phase. I suppose you'd be unhappy with the result. There's a small cache of up to 50 pages. Either I'd have to clear the cache when the text layer is toggled, or you'd still see the text layer on some pages after switching it off.

Cutting a long story short, I could make `[textLayer]` dynamic, but I know it's a lot of work and I suspect few users benefit from it.

**Comment by stephanrauh** [comment]
By the way, I've tried to indicate the attribute isn't dynamic in the documentation:

![image](https://user-images.githubusercontent.com/3045767/140422407-dcbe00eb-2187-4c89-a9c0-a3bede3aec09.png)

I know it's easy to miss. Any suggestion how to distinguish initialization-phase-only parameters from dynamic parameters?

**Comment by pauljohnleonard** [comment]
Thanks  for the background.   Reading docs is not one of my strengths so I probably just missed seeing that it was only used at initialisation.   Form what you you say I think my best hope is to have this layer enabled at the start and manipulate the textlayer element  directly to allow interaction with the canvas.  

I think  setting the textLayer pointer-events: none;  Should let me capture events from the canvas.

**Comment by stephanrauh** [comment]
I suppose you also could capture events from the page instead of capturing canvas events. The page is the parent container of both the canvas and the text layer. The page is at the same position and has the same size as the canvas.

**Comment by pauljohnleonard** [comment]
OK that might help. Thanks.  But then I would need to be able to turn off the text layer selection?   I need to do some more experimenting.    

FYI  I am using the pageViewer to manage the the scaling and transforming. To convert my mouse events into the pdf space.  The event here is being captured from my canvas drawing annotation overlay.     

`
  cursorToReal(e: { offsetX; offsetY }) {
    let z = this.pageViewer.viewport.convertToPdfPoint(e.offsetX, e.offsetY);

    return { x: z[0], y: z[1] };
  }

  realToCanvas(pos: AnnotationPoint) {
    let z = this.pageViewer.viewport.convertToViewportPoint(pos.x, pos.y);
    return {
      x: z[0] * this.pageViewer.outputScale.sx,
      y: z[1] * this.pageViewer.outputScale.sx,
    };
  }
`

**Comment by stephanrauh** [comment]
Nice!

**Comment by scry-UrjitDesai** [comment]
Hey @pauljohnleonard I too am struggling with the same issue. Were you able to get around it? If yes, could you please tell me the work around ?

**Comment by scry-UrjitDesai** [comment]
I figured a work around and it is working fine for me. Leaving the solution here, if someone else stumbles across the same issue. 

```
onPdfLoaded() {
    this.PDFViewerApplication = (window as any).PDFViewerApplication;
  }
```

I have used the following code to hide or show the textlayer. When it is hidden, the pointer events are registered on the underlying canvas element. 
```
this.PDFViewerApplication.pdfViewer._pages.forEach((page) => {
        page.textLayer.hide(); // to hide the text layer
        page.textLayer.show();
      

      });
```
