### ISSUE TITLE
./node_modules/ngx-extended-pdf-viewer/fesm2015/ngx-extended-pdf-viewer.js 5160:50-54 "export 'take' was not found in 'rxjs'

### ISSUE THREAD

**Issue by nguyenvan** [stephanrauh/ngx-extended-pdf-viewer#1058]
Hi Stephan Rauh 
when I install  ngx-extended-pdf-viewer on Angular 11. I got this error
```
./node_modules/ngx-extended-pdf-viewer/fesm2015/ngx-extended-pdf-viewer.js 5160:50-54
"export 'take' was not found in 'rxjs'
```
 After I checked I see error happen because rxjs does not map with current rxjs. I change the code at line 5 
```typescript
import { Subject,take  } from 'rxjs';
```
to 
```typescript
import { Subject} from 'rxjs';
import { take } from 'rxjs/operators';
```
and system works correct.
Could you check and update?
Thanks

**Comment by stephanrauh** [comment]
I see your point, but I have a hard time understanding which part of my source code causes your problem. Which file did you modify, precisely? It sounds like you've modified a JavaScript file - i.e. one of the compiled files. Is this correct? If so, can you give me some context? I've tried to find the offending `import` statements, but I failed.

Last questions: which version of ngx-extended-pdf-viewer are you using?

**Comment by stephanrauh** [comment]
Hm... maybe I was too fast. Chances are I've found the issue. Does the error vanish when you update to version 11.0.0-alpha.10?

**Comment by Kurabombei** [comment]
Hi Stephan Rauh,
I am experiencing the same issue on Angular 15.2.9 with ngx-extended-pdf-viewer in the 18.1.2 version. I see an error with that take operator not being properly imported. It could be because of some bad merge or something. 
How can I rebuild the fesm2020 folder by changing your import ? Or what should I do in order to have a working build?
Thank you for your time!
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/41858424/83b6d545-2953-451e-a7b9-5f174e0dd464)
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/41858424/ffeea00e-fd7a-404f-8525-53bbd55e0a07)

**Comment by stephanrauh** [comment]
Oh, you're right. It's not a merge conflict, it's just me accepting the suggestions of my IDE without thinking twice. Or even once. :)

Version 18.1.3 should fix this bug.

**Comment by Kurabombei** [comment]
Thank you, I will check it.

**Comment by stephanrauh** [comment]
What's your current state of the art?
