### ISSUE TITLE
Multiple instances support

### ISSUE THREAD

**Issue by impondesk** [stephanrauh/ngx-extended-pdf-viewer#1061]
Any plans to support multiple instances of PDF viewer on same page?

**Comment by stephanrauh** [comment]
No. That's more or less impossible, because the base library, pdf.js, pollutes the global name space.

However, I intend to wrap the library as a WebComponent. This allows users to use the library with React.js, Vue.js, plain vanilla JS, and even Angular. As a side effect, you can put multiple PDF files on the same page. At least I believe it's possible. You guys keep me busy by opening so many issues I never got to creating the WebComponent :)

**Comment by Tezra** [comment]
It seems this issue has been [fixed](https://github.com/mozilla/pdf.js/issues/5148) in PDF.js. Can this be revisited? Or does the global namespace issue still interfere with how this interacts with the PDF?

**Comment by stephanrauh** [comment]
I ran a quick test: two PDF viewers side-by-side, showing different PDF files, and the second PDF viewer is hidden for five seconds. So the first PDF viewer finishes rendering before the second starts initializing.

The result: when the second PDF viewer becomes visible, the first PDF viewer renders the new PDF file. The second PDF viewer merely shows a gray area.

I don't know what they fixed in the commit you've found, but it doesn't seem to refer to the UI part of the viewer. Many people simply use pdf.js without the UI, and I suppose that's what was fixed in 2015.
