### ISSUE TITLE
Install ngx-extended-pdf-viewer with systemjs

### ISSUE THREAD

**Issue by Philip-b** [stephanrauh/ngx-extended-pdf-viewer#1067]
I'm well into the development of showing PDF documents on our site and it has worked fine locally on my computer.
Then I pushed to our dev environment and noticed that is doesn't work there.

We use angular 8, so we had to use version 8.3.0 of this library.
We also use systemjs 0.21.6.

It wouldn't be a simple task to upgrade to the latest angular to get the latest version of ngx-extended-pdf-viewer.
So that would be the last resort if there is no easy fix for this.

The documentation and all the help I'm able to find tells me to do changes to my angular.json or angular-cli.json, but since we use systemjs we don't have any of those files.
I've done everything in the documentation but to add the rows for the assets into the angular.json file.

- I've done npm i ngx-extended-pdf-viewer --save
- I've imported the module with import { pdfDefaultOptions } from 'ngx-extended-pdf-viewer';
- I've set the default assets folder with pdfDefaultOptions.assetsFolder = './node_modules/ngx-extended-pdf-viewer/assets';
- Since we use systemjs I had to add a row into our systemjs config like this:
```
System.config({
        map: {
            app: "app",
            [...],
            "ngx-extended-pdf-viewer": "node_modules/ngx-extended-pdf-viewer/bundles/ngx-extended-pdf-viewer.umd.js"
        }, 

```

As I said, it works fine on my machine, but on the server with minification, the path to the assets folder gets invalid and I get this error in the browser console.
![image](https://user-images.githubusercontent.com/9108894/144884547-63518cec-80d2-47c3-9935-58996e64dabe.png)

Is there anyway to make sure systemjs knows about the assets in a real dev / prod environment?

I tried to add "pdfjs": "node_modules/ngx-extended-pdf-viewer/assets/pdf-2.7.673.min.js" above ngx-extended-pdf-viewer in the systemjs config to no avail. But I feel like the .umd.js file should handle all of this right?

Hopefully that is enough information that is needed from me.

Thanks.

**Comment by stephanrauh** [comment]
Good news first: the library is highly configurable, so I believe you'll manage to get it up and running. I'm no expert on systemjs - I was lucky to enter the Angular world when system.js was already getting out of fashion - but I'm positive I can help you.

If I understand you correctly, you've bundled the pdf*.js files and the viewer*.js file with your Angular code into one single giant file. This approach works, but it's not the most efficient way.

By default, the library loads the three files pdf*.js, pdf.worker*.js, and viewer*.js dynamically when the `NgxExtendedPdfViewrComponent` is initializing. It expects these three files to be in the assets folder. So my installation instructions tell you to copy the folder node_modules/ngx-extended-pdf-viewer/assets into the folder /assets of the web application.

I guess something's going wrong there. The simplest way to find the problem is probably debugging the code: https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/b03b866a2c50bf50263eecfa65770c3c8f5b21f4/projects/ngx-extended-pdf-viewer/src/lib/ngx-extended-pdf-viewer.component.ts#L824 and https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/b03b866a2c50bf50263eecfa65770c3c8f5b21f4/projects/ngx-extended-pdf-viewer/src/lib/ngx-extended-pdf-viewer.component.ts#L766. You're using an old version of the library, so the line number don't match, but you'll find the methods.

The file pdf.worker*.js is loaded at a different line of code, so it's more difficult to debug. There's a `pdfDefaultOptions` attribute called `workerSrc`. You can overwrite it to define the correct URL of the worker file.

Hope that helps!
Stephan

**Comment by stephanrauh** [comment]
BTW, I'm keeping this ticket open until you've told me you've solved the issue or until I suspect you've give up.

**Comment by Philip-b** [comment]
Thanks for the quick reply.
Unfortunately this is an old app with a bunch of legacy code.

It's late so I will look into this more tomorrow, but a few things first.

Yes, all of our .js files seems to be bundled up into a massive app.bundle.js (part of the legacy).
But I can't debug that, it's in our dev/staging server and in production I get this issue and that is where it's minified.
Locally I can debug it and I did find the functions, but they don't have the row you specified. This is what I get debugging that locally:
![image](https://user-images.githubusercontent.com/9108894/144916696-c0821024-cb26-4dda-b20d-df29109c5195.png)

And:
![image](https://user-images.githubusercontent.com/9108894/144916826-25b31eea-aae0-4a3d-ad35-b978129de20b.png)


So yeah, I see how I need to override workerSrc. Which in my case seems to be needed to be overwritten with:
`pdfDefaultOptions.workerSrc = () => 'the path';`

Although that line should only be run in a live environment since the paths are different locally and on the live servers. 
Maybe I can use angulars "environment.production" for that.
Will discuss with the team tomorrow morning.

Let's say I do figure out the correct path for the workerSrc for production, would that enable it to find the pdf*.min.js file as well?

**Comment by stephanrauh** [comment]
> Let's say I do figure out the correct path for the workerSrc for production, would that enable it to find the pdf*.min.js file as well?

It's an independent setting. However, your screenshot reveals something unexpected. The pdf*.js and the viewer*.js files are loaded from the node_modules folder. That doesn't look right. Your production server probably doesn't have this folder.

You can configure the correct URL of these two files using `pdfDefaultOptions.assetsFolder`.

As for `pdfDefaultOptions.workerSrc`: yes, you're guessing correctly. It's a lambda returning the URL of the file pdf.worker*.js.

BTW, you can simplify things a little by setting `[minifiedJSLibraries]="false"`. This way, you're using the non-minified files.

Can you deactivate minification on the dev server? That'd allow you to debug the code. Debugging minified code isn't impossible, but it's no fun at all.

**Comment by Philip-b** [comment]
Alright so it got me thinking with what you said and I landed in a solution that I'm not very fond of but sort of works. I just need to fix the build to the server.
So we use gulp and systemjs for deploying (which I have no experience of), I had to make some custom configuration to copy literally everything in the assets folder to a custom folder that is not the node_modules folder. I then set the `pdfDefaultOptions.assetsFolder` and `pdfDefaultOptions.workerSrc` to look in that folder instead.
That part works, now I just need to figure out some other things like having different pdfDefaultOptions locally and in production. I also need to automate the copy of assets folder in the deployment.
I guess that is the sort of pain you have to live with when not using the latest angular.

Deactivating minification on the dev server just crashed the deployment and I don't know why and I don't have time to figure that out.

**Comment by stephanrauh** [comment]
It's weird that disabling minification caused a crash. Apart from that, do you still need me help?
