### ISSUE TITLE
GetTextByPage returns text from pdf not in the order that is displayed 

### ISSUE THREAD

**Issue by cvetinaOfficial** [stephanrauh/ngx-extended-pdf-viewer#1072]
[Tesy BelliSlimo Dry manual.pdf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/7692446/Tesy.BelliSlimo.Dry.manual.pdf)
- I am using your library for preview and extraction of the text from each page for read aloud functionality. Unfortunately, some pages are not extracted in the order that is displayed and text to speech is reading in that order, i.e., the text starts with the 3th paragraph and continues with the 1st and 2nd paragraphs. Could you please try to debug the problem with the file I will attach and write me a note if you found something (page 6 -> It is getting the 3th paragraph first, named Important rules).

Thank you,
Best regards 
Cvetina

**Comment by stephanrauh** [comment]
I suspect your PDF file is the problem. When I open your PDF file in Google Chrome, and I try to select the text on page 6, Chrome's PDF viewer reacts a bit weird. I can select the text of the upper third of the page, or I can select the text below. When I move the mouse across the border, the selection behaves erratically.

So here's my theory: the author of the PDF file has two (or more) boxes of text on the page. And they've positioned these boxes using absolute x/y coordinates. So the text that occurs first in the source code is shown in the lower half of the page, and the page occurring later in the source code is shown above. In other words: the order of the texts in the PDF file doesn't respect the linear text flow. 

Unfortunately, I don't have a professional PDF editor at hand, so I can't verify my theory. But maybe you can. What happens if you print your PDF file as a PDF file? That's not as ridiculous as it sounds: usually the print algorithm prints the text in the correct order, because you can't render a page out-of-order on real paper with an affordable printer.

**Comment by stephanrauh** [comment]
I dug deeper into the topic. I'm pretty sure that the source code of the PDF file is the problem. However, some PDF viewers do a decent job ordering the text correctly. Unfortunately, it's beyond my scope. To fix the problem, you'd have to modify the worker thread of pdf.js - and that's a piece of code I prefer not to modify. I don't even understand it.

I've found that the problem doesn't only occur when selecting text. You can also reproduce it using the find functionality. This screenshot shows that the top-most occurrance of "to" is shown after hitting the "next" button 16 times:

![image](https://user-images.githubusercontent.com/3045767/147579954-6ca8ab40-bc08-4f0c-b1fc-cbcb0087f409.png)

**Comment by stephanrauh** [comment]
Instead of trying to use the internal API of the PDF viewer, you can also try to extract the text from the DOM. The text is rendered as a large collection of `<span>` tags. Extracting text is a bit cumbersome because the text is divided into so many `<span>` tags. Often, they even split words. The good news is they bear the x/y coordinates, so you can order them correctly. The bad news is that this doesn't help you: the source code of the PDF files organizes the text into text boxes, but after rendering there's no hint about that.

So I suppose it's best to fix the source code of the PDF file. Alternatively, you can add an issue at https://github.com/mozilla/pdf.js. Don't tell them about text extraction - that's something they don't care about because their focus is writing a PDF viewer for Firefox. But when you tell them about the wrong order of find results, or if you tell them you can't mark and copy the text in Firefox, you may be lucky.

For the sake of convenience, here's a screenshot of the DOM tree (or a small part of it):

![image](https://user-images.githubusercontent.com/3045767/147580717-da2e6e15-65d0-4fb4-9730-6b5e1709c0be.png)
