### ISSUE TITLE
Take a snapshot function.

### ISSUE THREAD

**Issue by wajedali** [stephanrauh/ngx-extended-pdf-viewer#110]
Hello ,

Adob PDF Reader provide functionality like take snapshot as shown in fig below, do you think its possible with pdf viewer.

![Take_ScreenShot](https://user-images.githubusercontent.com/46092751/61443151-38133380-a949-11e9-8600-7abb69fbb96a.png)

Thank you.

**Comment by stephanrauh** [comment]
I'm not sure I want to do that. Taking screenshots of a PDF documents sounds like an exotic use-case to me. As far as I can see, you can implement the feature yourself: https://stackoverflow.com/questions/4912092/using-html5-canvas-javascript-to-take-in-browser-screenshots.

**Comment by wajedali** [comment]
I was looking adobe reader features and thought to suggest features to angular pdf viwer.

I had tried but its not user friendly - here is the post - https://stackoverflow.com/questions/57036487/image-snipping-from-page

**Comment by stephanrauh** [comment]
Ah, I see. That's very kind of you! Thank you very much! 

Once again, I'm happy to learn what a friendly place the developer community it. You guys rock!

![image](https://user-images.githubusercontent.com/3045767/61490594-9e31a200-a9ad-11e9-90ff-2dd7674dc01d.png)

**Comment by stephanrauh** [comment]
As for the implementation bit: yes, I can imagine it's not easy to get the screenshot function up and running. I've tried many years ago, and since then, the situation seems to have improved only gradually. That's one of the reasons why I'm so reluctant. The other reason is that it's easy to take a screenshot with most devices. For example, for Windows there's a great tool called Greenshot. There's no way to compete with it, so I won't even try. :)

However, I'm wonder if it might be a good idea to open ngx-extended-pdf-viewer for user-defined extensions. I'll keep this ticket open until I've finished pondering about that. :)

**Comment by stephanrauh** [comment]
I've got an idea how to make the toolbar much more flexible. That'll land with version 1.1.

I'll close the ticket for the moment. But before doing so, let me shout "thank you!" to you. You've inspired me to improve the library, going beyond simply integrating the Mozilla lib into Angular.
