### ISSUE TITLE
Find functionality not able to highlight exact text in PDF with own Implementation

### ISSUE THREAD

**Issue by srmkumar** [stephanrauh/ngx-extended-pdf-viewer#1101]
Hi Team,
I am trying to implement  the **find/ search** using this plugin which look like the below using this plugin.

![image](https://user-images.githubusercontent.com/14026447/147086225-bbb75a06-8bb5-41eb-9d46-b737880e877c.png)

I am able to do that using **RegExp** and populating the data in the grid as shown in below.

![PDF releated](https://user-images.githubusercontent.com/14026447/147086515-40829cc6-9279-4e05-9edb-85c1aefdb4a4.png)

By using the following method **ngxExtendedPdfViewerService.getPageAsText** we are converting the PDF page as a text and extracting extracting the searched key word using RegEx ((https://stackoverflow.com/questions/43910176/show-searched-text-of-a-pdf-along-with-page-number))  and displaying in the left side grid as attached above.

but when I try to click on the **specific item** I am not able to **highlight in the pdf document.**
could some one help me on how to locate specific location in the PDF when we click on the searched Items? 

TYIA
Kumar

**Comment by stephanrauh** [comment]
That's a difficult task because the text is scattered across countless `<span>` tags. Often, such a  `<span>`  divides a word.

I think you can find out how to do it by a lot of debugging and setting breakpoints at these lines or files:
https://github.com/stephanrauh/pdf.js/blob/a908aac822b54b970f3aceac091a4707de09470e/web/pdf_find_controller.js#L76

https://github.com/stephanrauh/pdf.js/blob/a908aac822b54b970f3aceac091a4707de09470e/web/pdf_find_controller.js#L504

https://github.com/stephanrauh/pdf.js/blob/bleeding-edge/web/text_highlighter.js

**Comment by srmkumar** [comment]
Hi Steph,

Thank you for the quick response will try further with debugging the code.

Thank you so much.
Kumar
