### ISSUE TITLE
viewerPositionTop changing the value.

### ISSUE THREAD

**Issue by YurchenkoAndrew** [stephanrauh/ngx-extended-pdf-viewer#1105]
viewerPositionTop changing the value.

I need to implement showing a toolbar by a button. But when the toolbar is in the false position, the viewerPositionTop cannot be changed to a value of 0px.

Couldn't find anywhere in the documentation about this data parameter.
This option is very useful for customizing the module.
Perhaps it is possible to already control this parameter? I would be grateful for a hint!

**Comment by YurchenkoAndrew** [comment]
At the moment, I found a way out.
Overridden in the css class .grab-to-pan-grab { top: 0 !important}

But this is not a good practice.
Would like full interaction with the component.

**Comment by stephanrauh** [comment]
Can you add a sketch or a screenshot, please? At the moment, I don't see what you're trying to do.

`viewerPositionTop` is an internal parameter. It is calculated here: https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/418fa317c5f3106d45270decf071d0328c562046/projects/ngx-extended-pdf-viewer/src/lib/ngx-extended-pdf-viewer.component.ts#L659

The idea is to shift the divs below the toolbar up and down depending on the magnification of the toolbar. This even allows for multiline content in the toolbar.

**Comment by feonx** [comment]
I have got the same issue. 

My angular application contains multiple divs with a class name 'toolbar'. This line below takes the first occurrence of a element with class name 'toolbar' on the page. 

`const toolbar = document.getElementsByClassName('toolbar')[0] as HTMLElement; `

Since my toolbar is like 300+ pixels height, the PDF gets calculated with a 'top' of 300+.. and results in the PDF not showing on the page anymore. Or another way to say it is: it takes the 'wrong' element because the first 'toolbar' isn't the ngx-extended-pdf-viewer' toolbar, but my own.

Isn't using native JavaScript bad practice? Maybe use the 'ElementRef' as constructor argument in the pdf-toolbar.component and output the left and top?

If you'd like I can add a pull request with a fix when I have time.

**Comment by stephanrauh** [comment]
The base library, pdf.js, uses `document.getElementBy*()` all the time. So I didn't feel that bad about using the native JavaScript function. I guess Angular mostly frowns upon write accesses.
