### ISSUE TITLE
Incremental save

### ISSUE THREAD

**Issue by namblard-sword** [stephanrauh/ngx-extended-pdf-viewer#1128]
Hello,

First of all i don't know if it is doable, if not, excuse me for the bothering.

**Is your feature request related to a problem? Please describe.**
The issue I'm facing is that editing a pdf with the pdf viewer and then saving the blob in my be invalidate the former seal applied on the document. I was wondering if there was a way to have an incremental save, meaning that we keep the current revision and to append the changes to make sure the seal is not invalidated.

**Describe the solution you'd like**
As of now the saving is done using your NgxExtendedPdfViewerService with the method getCurrentDocumentAsBlob() where you call the save document method of pdfjs.

Would it be possible to consider having either a similar method with the behaviour describe earlier or to have a parameter to swith from one behaviour to another.

If no solution are doable please let me know.

Thanks a lot for your time,

Kind regards

**Comment by stephanrauh** [comment]
Don't worry about bothering me. :) But I'm afraid I don't understand your question. What are you referring to when you say "seal"? What get's broken by calling `getCurrentDocumentAsBlob()`?

**Comment by namblard-sword** [comment]
Hi,

Thank you for your reply.

Let's imagine a workflow: we have a contract between two parties.

First party fills its part and then sign it.
Then second party fills the document and download it with getCurrentDocumentAsBlob().

If you look to your downloaded file using adobe for instance then the signature would be considered as broken.

That's what I would like to be enhanced if possible. 
As I deactivate fields regarding users and lock acroforms in pdf after they signed, the integrity of the signing should not be harmed.

Thank you for your time.

**Comment by stephanrauh** [comment]
Oh, you're talking about the signature. Well, that's something I don't know much about. I only know that the PDF viewer can't verify the validity of the signature. So it's not surprising it breaks the signature when you're downloading the PDF file.

- Please check if the signature is also broken when you download the file using the download button. 
- If it's broken, please repeat the same here: https://mozilla.github.io/pdf.js/web/viewer.html.

If the signature is invalid after downloading the file from the Mozilla page, you can ask the pdf.js team to fix the bug. Don't tell them about ngx-extended-pdf-viewer, because that's not their project. The focus is implementing a PDF viewer for Firefox. Just tell them the signature becomes invalid after downloading it in Firefox.

**Comment by namblard-sword** [comment]
Hi,

Thank you for your reply, you can close the issue I'll check that with pdfjs team. I'm sorry to have wasted your time.

Have a nice day !

**Comment by stephanrauh** [comment]
@namblard-sword It was an interesting challenge, so you didn't waste my time! :)

@timvandermeij When you see an issue submitted my @namblard-sword  - I've sent them to you. If I can be of assistance, don't hesitate to ask me!
