### ISSUE TITLE
disableHistory does not work

### ISSUE THREAD

**Issue by michaelmarcuccio** [stephanrauh/ngx-extended-pdf-viewer#1163]
`pdfDefaultOptions.disableHistory = true; `
does not disable history. Localstorage 'pdfjs.history' is still created and updated.

- Version: 11.1.2
- Browser: Chrome

![image](https://user-images.githubusercontent.com/20432260/152009933-0ede4ab1-fc84-44d8-a7b8-dee96c3cfa4e.png)

I am working around this by doing the following on every viewer load:
`localStorage.removeItem('pdfjs.history');`

**Comment by stephanrauh** [comment]
You're raising an interesting question. 

Actually, the feature controlled by `disableHistory` is never activated, regardless of the value of the attribute. The PDF viewer runs in embedded mode, and the history is a history of URLs. That doesn't make sense in embedded mode, so it's always deactivated.

The history you've found seems to play a different role. So it's not surprising it's not affected by `disableHistory`.

On the other hand, I can change the semantics of `disableHistory`.  I believe this makes sense because the attribute is currently useless, and the fingerprint you've found is a kind of history, too.

**Comment by stephanrauh** [comment]
Your bug fix (or improvement?) has landed with version 11.2.0-alpha.3.
