### ISSUE TITLE
running build shows error on your node_module

### ISSUE THREAD

**Issue by ALapaque** [stephanrauh/ngx-extended-pdf-viewer#119]
**Describe the bug**
the pdf viewer is working fine but unfortunately when i'm building my app it says 

`ERROR in node_modules\ngx-extended-pdf-viewer-vv\ngx-extended-pdf-viewer.d.ts.NgxExtendedPdfViewerComponent.html(270,17): : Property 'showSelectToolButton' does not exist on type 'NgxExtendedPdfViewerComponent'.
`

**Version info**
- Version of ngx-extended-pdf-viewer 1.0.0-rc.6

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Chrome
 - Version 75.0.3770.142

Otherwise, please tell me how to reproduce the behavior:
just a simple use use  with  
```html
<ngx-extended-pdf-viewer *ngIf=""
                           [src]=""
                           backgroundColor="#ffffff"
                           [height]="'120vh'"
                           [useBrowserLocale]="true">
  </ngx-extended-pdf-viewer>
```
and after that run npm run build-prod and this shows me the error

**Comment by stephanrauh** [comment]
I believe something else is going on here. I've removed the attribute `showSelectToolButton` in version 0.9.47. That's because I realized it's simply the opposite of `showHandToolButton`. My theory: somewhere in your project there's still a `showSelectToolButton` left.

BTW, I've tried hard to reproduce your bug, running it on two computers (Windows and Mac). If you still can't find the root cause, please clone the [showcase](url)

**Comment by ALapaque** [comment]
Hi @stephanrauh,

I've totally reinstalled your module and it worked well.

Thanks for your help :)

**Comment by stephanrauh** [comment]
That's great news. Thanks for reaching out after solving the bug!
