### ISSUE TITLE
Error when on IFrame

### ISSUE THREAD

**Issue by vels-sonata** [stephanrauh/ngx-extended-pdf-viewer#1198]
when <ngx-extended-pdf-viewer></ngx-extended-pdf-viewer> comes under IFrame, it throws `pdf.worker.js 404 (Not Found)`.

![image](https://user-images.githubusercontent.com/43806410/153576145-595aa612-5620-4916-96f3-bdffa0d603fe.png)

PDF not getting loaded when inside an IFrame.
![image](https://user-images.githubusercontent.com/43806410/153576540-4b43c568-e56c-4563-b50a-b6e393ec6702.png)

Steps to reproduce.
The sample project attached [here](https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/pull/241).
1. deploy this application on localhost (name it as 'pdf') and browse, ensure it works.
2. rename index.txt to index.html and deploy this in a another site and browse, the PDF not getting loaded.
[index.txt](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/8048019/index.txt)
The same works we change iframe -> src -> https://mozilla.github.io/pdf.js/web/viewer.html

Please suggest. 

Thanks.

**Comment by stephanrauh** [comment]
I'm afraid it works flawlessly on my machine. I had to update Angular because your version (Angular 11) doesn't seem to be compatible to node.js 16. Plus, I added your `index.txt` so I can open it by navigating to http://127.0.0.1:4200/iframe.html.

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/3045767/153725109-cbeb80e6-9bd8-4821-a2c6-4fb033d2010f.png">

**Comment by stephanrauh** [comment]
Maybe you've run into a CORS problem, or maybe you're using the wrong URL? I'm asking because your console snippet also mentions that the favicon is missing.

**Comment by vels-sonata** [comment]
Thanks for the help, No issues after upgrading to version 11.2.0
