### ISSUE TITLE
delayFirstView is required actually?

### ISSUE THREAD

**Issue by vels-sonata** [stephanrauh/ngx-extended-pdf-viewer#1206]
Hi,
![image](https://user-images.githubusercontent.com/43806410/154688863-1410e3af-8dbf-4ddb-99e3-c1e06f26e232.png)
Little confuse here, it says deprecated, but in our case without delayFirstView PDF is not getting loaded on first time with 1000ms,But if we set to 10000ms the PDF loads, is it required? what is happening behind this delayFirstView.

**Comment by vels-sonata** [comment]
When we upgrade the version from 8.3.0 to 11.2.0, we made only the following changes.
`pdfViewerComponent.fillFormFields(this.formData);` 
to
`pdfViewerComponent.updateFormFields(this.formData, this.oldFormData);`
with version 11.2.0 `(pagesLoaded)` event not firing properly.

**Comment by stephanrauh** [comment]
The change concerning the checkbox is probably caused by this bugfix: https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/958

It's possible to make checkboxes behave like radiobuttons. I suppose the author of your PDF file used this feature accidentally. The problem is a checkbox has only two values: true and false. If you use several checkboxes as radiobuttons, you need a way to distinguish them. That's why I added the radio button value to the name of the checkbox. In most cases, you shouldn't even notice, but it seems your document is a corner case.
