### ISSUE TITLE
Recent CSS change looks wrong

### ISSUE THREAD

**Issue by michaelmarcuccio** [stephanrauh/ngx-extended-pdf-viewer#1278]
Toolbar CSS changes broke a little bit of the formatting. The pager widget has the padding/margin overriden on the input element with:

ngx-extended-pdf-viewer .html .toolbar *, ngx-extended-pdf-viewer .html .treeItem * {
    padding: 0;
    margin: 0;
}

![image](https://user-images.githubusercontent.com/20432260/161176591-4f6e3107-78a6-450f-aae0-4266647c9480.png)
Issue occurs in Version 12.1.0.

Looks good in Version 12.0.3.
![image](https://user-images.githubusercontent.com/20432260/161176623-c9d7b851-e96e-4985-a80f-e7683412dd61.png)

**Comment by stephanrauh** [comment]
Versions 12.1.1 and 13.0.0-alpha.3 both fix the bug. 

Thanks for reporting it! I hope we've found all regressions caused by #1120 by now - but what seems trivial at the time turned out to be surprisingly complex. In other words: if you find another layout glitch, don't hesitate to report it!

Best regards,
Stephan
