### ISSUE TITLE
showUnverifiedSignatures is true, still signatures are not shown in PDF

### ISSUE THREAD

**Issue by manjari09** [stephanrauh/ngx-extended-pdf-viewer#1280]
Hello Team,
I am using ngx-extended-pdf-viewer v12.1.0, and I want in my application to show Digital Signature. For this I used, below directive in my HTML file, 

[showUnverifiedSignatures]="true"
But still I am getting warning in console and message in box in PDF.
Could you please let me know how to achieve the same.

I am using Angular version - 12.1.0

Thanks & Regards
Manjari Kumari

**Comment by manjari09** [comment]
Just to update, we are able to see the signatures. But, we want message which comes in red box to be hidden, Is there any way to do so?

**Comment by stephanrauh** [comment]
Yes, of course that's possible. But I don't want to make it too easy because everything concerning digital signatures is about trust. Just imagine: what happens if a user of your application sees a fraud signature, trusts it, and runs into trouble because of that? 

If you can make sure the signature is valid, I don't object hiding the message. It's just that I want to make you aware of the risk. 

That said, have a look at the HTML code. You can hide the red message using a simple CSS rule.
