### ISSUE TITLE
pdf-2.13.482.min.js is missing from assets

### ISSUE THREAD

**Issue by peterterbe** [stephanrauh/ngx-extended-pdf-viewer#1282]
**Describe the bug**
I've just added the ngx-extended-pdf-viewer to the project and NgxExtendedPdfViewerModule is in my app.module. When I open my application it loads the main controls but nothing else. The network tab shows that it tried to download `http://localhost:4200/assets/pdf-2.13.482.min.js`

The assets have been set in angular.json, it copyies everything into dist/assets and I checked the assets folder in node_modules where that file doesn't exists either. 

The folder has a `pdf-2.13.482.js` but not `min.js`. I suppose this is an alpha version bug as I use ^13.0.0-alpha.3. Or should I make webpack create the .min file?

**Version info**
- Version of ngx-extended-pdf-viewer ^13.0.0-alpha.3

**Desktop (please complete the following information):**
 - Browser: Chrome

Btw, thanks for maintaining this library!

**Comment by stephanrauh** [comment]
That's probably my fault. As a workaround, you can set the attribute `[minifiedJSLibraries]="false"`. That costs a little performance, but that's the only disadvantage.

All those JavaScript files are generated automatedly - you don't need to use Webpack. No idea what went wrong. Maybe it's because I had to fix a bug in the old 12.1.1 version, and there's no automated process for it because it's the first time I did it. So I copied the files manually. Your bug might be a nasty side effect of this.

**Comment by stephanrauh** [comment]
Just double-checked it: you're right, the files are missing: https://unpkg.com/browse/ngx-extended-pdf-viewer@13.0.0-alpha.3/assets/.

However, they are there in the bleeding-edge branch: https://unpkg.com/browse/ngx-extended-pdf-viewer@13.0.0-alpha.3/bleeding-edge/

Weird!

**Comment by stephanrauh** [comment]
I've published version 13.0.0-alpha.4. Now the missing files are back.

Enjoy!
Stephan
