### ISSUE TITLE
Scroll using relative or absolute coordinates?

### ISSUE THREAD

**Issue by crlsmsq** [stephanrauh/ngx-extended-pdf-viewer#1301]
I was wondering if there's a way to scroll to a certain part of a page via giving relative or absolute coordinates?

**Comment by stephanrauh** [comment]
Yes, of course. The base library offer the function [scrollIntoViewer()](https://github.com/mozilla/pdf.js/blob/3635a9a3338feb0049be4f1521d5a5afd173a832/web/ui_utils.js#L115). However, I'm reluctant to expose this function because it uses an internal coordinate system that's probably both difficult to explain and to understand.

However, if you can wrap your head around it, feel free to use it. I believe it's one of the stable APIs.

**Comment by stephanrauh** [comment]
BTW, even if I've closed the ticket, I'd like to hear from you. Does my hint help you? Do you think I should document it? Or do you even think I should implement and maintain an official API for that?

**Comment by dashakureru** [comment]
I also need the same feature and I'm not sure how to call **scrollIntoViewer**. A documentation would be helpful :)

**Comment by stephanrauh** [comment]
I've implemented both relative and absolute coordinates. The absolute coordinates are probably useless, because they depend on the zoom level, but I didn't want to omit them. How do you like this API? https://pdfviewer.net/extended-pdf-viewer/scrolling

I've published the new API with version 13.0.0-alpha.16.

I'm looking forward to your feedback!
Stephan
