### ISSUE TITLE
Zoom on iOS disabled

### ISSUE THREAD

**Issue by pilz97** [stephanrauh/ngx-extended-pdf-viewer#1373]
I am running the ngx-extended-pdf-viewer on an iPad.
In one case i have a really long pdf, so without zooming you cannot read anything:
![image](https://user-images.githubusercontent.com/42172207/168832975-d90703a9-040f-4a56-904e-99bf97e927ae.png)

In my Electron App on Windows the zoom factor is perfect, but i figured out that the zoom option is disabled on iOS, is there any reason why?

![image](https://user-images.githubusercontent.com/42172207/168833278-8f14e44d-3dbe-44f1-affc-6a83d2a84949.png)

**Comment by stephanrauh** [comment]
That's unexpected. Please browse to http://pdfviewer.net on your iPad and check if you can zoom. My iPad allows me to zoom, what about you iPad?

After that, open your document on http://pdfviewer.net. If zooming is disabled, it has something to do with your document.

If so, it's possibly caused by the page size. Every browser has a maximum image ( = page) size, and iOS devices are particularly limited. According to https://www.npmjs.com/package/canvas-size, these are the current limits:
<img width="708" alt="image" src="https://user-images.githubusercontent.com/3045767/168901489-313a6bec-27d5-4817-80e2-2b91df0eb88a.png">

Do you happen to know the page size?

BTW, maximum page size is one of the advantages of ngx-extended-pdf-viewer over every other viewer based on pdf.js. I lifted the maximum page size by checking what the browser's able to display. The original implementation stopped at the lowest common denominator (i.e. iOS).

**Comment by pilz97** [comment]
@stephanrauh thx for your quick reply.

I uploaded my file it works fine in safari on my ipad. But won't in my app.
Maybe it's some issue related to my cordova app.

**Comment by stephanrauh** [comment]
Can you debug the JavaScript code? If so, set `[useMinifiedJavaScript]="false"` and debug this function:
https://github.com/stephanrauh/pdf.js/blob/5acf993eb1ae2f259fe832bc3551cde7457329bd/web/pdf_page_view.js#L823

It determines the maximum resolution and sets the parameter `PdfViewerOptions.maxZoom`. At least I thought so until I saw it's commented. My best guess is I've set the parameter at another line, but maybe I've accidentally killed the feature. However, your bug points to a low setting of `maxZoom`.

As for the difference between Cordova and Safari: Maybe your Cordova app has less memory that Safari. Or it's really something different.

**Comment by stephanrauh** [comment]
I haven't heard from you for a long time. I'm closing the ticket now.
