### ISSUE TITLE
Cannot read properties of undefined (reading 'appendChild')

### ISSUE THREAD

**Issue by ClausElmann** [stephanrauh/ngx-extended-pdf-viewer#1386]
Trying to display a pdf inside a 'popup dialog' <p-dialog  (https://www.primefaces.org/primeng/) - but it gives Cannot read properties of undefined (reading 'appendChild')

Is it not possible to pop up a pdf in some way?

Is there a work around?

**Comment by stephanrauh** [comment]
Well, PrimeNG has mediocre quality, so I'm not surprised you've run into problems. In particular, I had a lot of trouble with `<p-dialog>`. I can only guess: maybe your problem is related to DOM manipulations or to some dynamic rendering pdf.js doesn't expect.

However, you should be able to display `ngx-extended-pdf-viewer` in any DOM that doesn't change. So a common trick to solve issues with pop-up dialogs is to show the PDF viewer with a delay. By default the viewer is hidden, and it's only displayed a fraction of a second after opening the dialog. Something like this pseudocode:

```typescript
public visible = false;
dialogService.open(MyFavoritePopupDialog);
setTimeout(() => this.visible = true, 300);
```
```html
<p-dialog>
  <ngx-extended-pdf-viewer *ngIf="visible">
</p-dialog>
```

**Comment by stephanrauh** [comment]
I prefer to keep issues open until I know you've managed to solve your problem. That, in turn, means I'd appreciate your feedback. Did my hint help to?

Best regards,
Stephan

**Comment by ClausElmann** [comment]
Thanks a lot Stephan, very helpfull

whent with
`
showBasicDialog() {
    this.displayPdfDialog = true;
    setTimeout(() => {
      this.pdfViewerVisible = true;
      this.cd.detectChanges();
    }, 300);
  }
`
