### ISSUE TITLE
IE 11 can't load pdf

### ISSUE THREAD

**Issue by kubydog** [stephanrauh/ngx-extended-pdf-viewer#139]
Hello @stephanrauh, the pdf viewer is broken on IE 11
Error Message: file origin does not match viewer's
![image](https://user-images.githubusercontent.com/12166284/64671780-d1277c00-d4ac-11e9-987c-b689fd2c77cc.png)

I did research on this error and found it is caused by view-es5.js. In my project,  I did a quick fix based on https://github.com/mozilla/pdf.js/issues/7153, but it needs me to modify the source code 

Is there any easy way to avoid this?

ngx-extended-pdf-viewer version: 1.5.1
angular version: 7

After I fixed the pdf loading issue. I got issues of changing page:
By scrolling: 
![image](https://user-images.githubusercontent.com/12166284/64674587-827de000-d4b4-11e9-9f5b-35ff3a0e30ba.png)

By selecting thumbnail:
![image](https://user-images.githubusercontent.com/12166284/64674558-7003a680-d4b4-11e9-878c-133511a62e7e.png)

By entering page number in page input box, nothing happen, doesn't go to the page entered.

Chrome works fine

**Comment by stephanrauh** [comment]
What was your change to the source code? Did you modify the array `HOSTED_VIEWER_ORIGINS`?

**Comment by kubydog** [comment]
I added two lines code in view.js
var LOCAL_AUTO_DETECT_ORIGIN = window.location.origin;

 var HOSTED_VIEWER_ORIGINS = ['null', 'http://mozilla.github.io', 'https://mozilla.github.io'];

 HOSTED_VIEWER_ORIGINS.push(LOCAL_AUTO_DETECT_ORIGIN);

**Comment by stephanrauh** [comment]
Quick sign-of-life: I've started to investigate your topic. As far as I remember, I've already integrated your fix, but I was interrupted by private life. I hope I can find some spare time for this project soon, in a week or two. Stay tuned!

Best regards,
Stephan

**Comment by rbdv159** [comment]
Having the same problem. Any solutions upcoming?

**Comment by stephanrauh** [comment]
@kubydog The problems with scrolling and entering the page number should be a thing of the past. Update to version 1.7.0, and everything should be OK. If these errors still occur, report them at #154.

**Comment by stephanrauh** [comment]
@rbdv159 I assume you're referring to the "file origin" message?

**Comment by stephanrauh** [comment]
@rbdv159 @kubydog After thinking about it for a while, I don't believe this is an error. You've stumbled upon a protection against CORS attacks. No browser except IE11 will accept PDF files that don't come from the same URL as the Angular application.

I've tried to reproduce the bug, but I didn't manage to do so. Every combination that came to my mind either works or is rightfully blocked by the CORS protection.

The `HOSTED_VIEWER_ORIGINS` bit is a CORS protection, too. It has been added to the PDF viewer because the viewer is also added the Firefox and Chrome natively.

The `window.location.origin´ doesn't make any difference. In my tests, that is. I'll add it as soon as you manage to convince me it's useful. What's your precise scenario?

I'll close the ticket now, but I'm still listening to the channel. Don't hesitate to leave your suggestions or - even better - your reproducer (i.e. a small, simple, but complete project showing the bug).

Best regards,
Stephan
