### ISSUE TITLE
In Angular 8.2.0 This pdfviewer is not working properly for only IE 11, remaining browser are working fine, I did all changes for IE11 in my code, in IE "Next Page and Previous Page" functionality was not working.

### ISSUE THREAD

**Issue by Ramu145** [stephanrauh/ngx-extended-pdf-viewer#140]
In IE11 : Error:

ERROR TypeError: Object doesn't support this action

How can i fix it for Next Page and Previous Page actions

**Comment by stephanrauh** [comment]
Which version of the PDF viewer are you using? When I tested IE11 compatibility yesterday, everything was broken, but I didn't have any clue what was going on. :(

**Comment by stephanrauh** [comment]
@Ramu145 Which find action are you referring to? Does the error happen when you click one of the button? Or are your referring to the programmatic API?

**Comment by stephanrauh** [comment]
@Ramu145 Are you still there? Can you give me any clue how to reproduce the bug you've reported?

**Comment by Whisper-** [comment]
Hi Stephanrauh,

Same issue is happening on my part when displaying the pdf in IE11. 
On next / previous page click the error described in the ticket happens (the same error happens when scrolling down through the pages)

![image](https://user-images.githubusercontent.com/9658649/65892769-8a43ec80-e3af-11e9-94f8-e26bcced6a3a.png)

I've added the scripts in angular.json as described (hopefully):
![image](https://user-images.githubusercontent.com/9658649/65892893-b495aa00-e3af-11e9-83b3-0806817d44fe.png)

**Comment by stephanrauh** [comment]
Sounds like a missing polyfill. Can you send me expand the error message and send me the  stacktrace?

**Comment by rnallani** [comment]
I am seeing the same issue in IE 11, Angular 6 with polyfills enabled. 

![Capture](https://user-images.githubusercontent.com/1250477/66366702-f5b12f80-e956-11e9-8798-21376ba9f71a.PNG)

**Comment by stephanrauh** [comment]
Maybe this is related to #154?

**Comment by stephanrauh** [comment]
I believe that's the same bug as #154 and #120. Let's close the ticket. It should be solved with version 1.7.0.
