### ISSUE TITLE
view pdf document in Html elements not using canvas element

### ISSUE THREAD

**Issue by sameerAhmad9291** [stephanrauh/ngx-extended-pdf-viewer#141]
**Is your feature request related to a problem? Please describe.**
I want to display pdf document in html elements format. As i will be easy for web crawls to extract text from pdf file.

**Describe the solution you'd like**
UseCanvasDisplay flag will be easy to use feature.

**ngx-extended-pdf-viewer:**

![image](https://user-images.githubusercontent.com/6412013/64776831-62acf180-d572-11e9-8b6f-ba004afcd3db.png)

**ng2-pdf-view:**

![image](https://user-images.githubusercontent.com/6412013/64777077-de0ea300-d572-11e9-9361-33e2b24ab32b.png)

**Comment by stephanrauh** [comment]
Whow, that's quite a challenge for the Google crawler: first it has to run the Angular application, and then it has to run the PDF viewer. Currently, none of my PDF files of the showcase made it into the Google index.

The best option is to add a direct link to your PDF file. That's something Google can easily find and interpret. It's a bit tricky because you want to show the PDF files as embedded files. I'm not sure it's a good idea to provide a direct link to the PDF, plus a redirection to your application that's only active for humans. That'd be a good solution, but as far as I remember, Google doesn't like that (for good reasons).

Here's more info: https://www.thewebmaster.com/seo/2016/feb/24/google-we-index-pdfs-just-like-any-other-web-page/

BTW, there's at least one document on the showcase including the text layer:
https://pdfviewer.net/find
<img width="871" alt="image" src="https://user-images.githubusercontent.com/3045767/64842965-0eeae880-d604-11e9-8852-0d7cc3b2e6d7.png">

**Comment by stephanrauh** [comment]
Sorry, it seem's I've given you exactly the opposite of the correct advise. Try setting `handTool="false"` or `handToolButton=`true`. I've just looked up the (internal) code snippet responsible for activating the text layer:

```typescript
    if (!this.handTool) {
      options.set('textLayerMode', 1);
    } else {
      options.set('textLayerMode', this.showHandToolButton ? 1 : 0);
    }
```

(That's a part of the implementation of ngx-extended-pdf-viewer, not something you should use in your application).

**Comment by sameerAhmad9291** [comment]
[handTool]="false" worked Thanks.

**Comment by stephanrauh** [comment]
That's great news!
