### ISSUE TITLE
Pdf load incomplete - samsug galaxy s21 plus

### ISSUE THREAD

**Issue by casper5822** [stephanrauh/ngx-extended-pdf-viewer#1413]
**Describe the bug**
pages inside the pdfs render incomplete (text and image are no displayed)

**Version info**
- extended-viewer 13.0.0

**Desktop (please complete the following information):**
 - Browser chrome
 
**Smartphone (please complete the following information):**
 - Device: samsung galaxy s21 plus

**screenshots**
This error happens also on ng2-pdf-viewer 

![IMG_20220605_221135_470](https://user-images.githubusercontent.com/26361006/172068762-1af7851f-3bcd-42d9-a9d4-67d7607cf5a8.jpg)

**Additional context**
Angular 12 web app. Pdfs work great on all devices expect samsung galaxy s21 plus

**Thank you!**

**Comment by stephanrauh** [comment]
If the bug also happens on ng2-pdf-viewer, it's almost certainly a bug of the base library. Please report it over there.

Reporting a bug at https://github.com/mozilla/pdf.js/issues requires you to, well, do it right. They don't accept bug if you mention Vadym's or my library. You have to convince the Mozilla team that the bug affects Firefox.

The first step is to reproduce the bug on https://mozilla.github.io/pdf.js/web/viewer.html. If you can't reproduce it on this page, return to me. But I'm sure you can reproduce it.

After that, report the bug on https://github.com/mozilla/pdf.js/issues. It helps if you fill the form meticulously, and if you don't mention Angular.

That said, I suspect the Samsung Galaxy is the culprit. Maybe the bug is gone after the next update of the operating system.

Best regards, and happy Pentecost
Stephan

**Comment by stephanrauh** [comment]
I've closed the issue because I believe I can't help you. But I'm still listening to this channel. If you've got new insight, or if you're still stuck, just add a comment here.

**Comment by casper5822** [comment]
Thank you for your response.
We find a very similaropen  issue on pdfjs so i just added my comment on this ticket.
You can find it here:
https://github.com/mozilla/pdf.js/issues/12307

**Comment by casper5822** [comment]
Hello @stephanrauh, it seems to be a problem on all android12 device.
You can see here another ticket about this topic: https://github.com/mozilla/pdf.js/issues/14709

**Comment by stephanrauh** [comment]
@casper5822 Let's hope someone escalates the problem to the browser development team. Probably that's the Chrome team, but it also might be Samsung.
