### ISSUE TITLE
Sidebar Thumbnail overlap with scrollbar

### ISSUE THREAD

**Issue by manzoorsharif123** [stephanrauh/ngx-extended-pdf-viewer#1438]
Hi,

Version ngx-extended-pdf-viewer - 8.2.0

Issue - Sidebar thumbnails are getting overlapped with verticle scroll bar.
Please find attached screenshot.

But when i tried to drag the thumbnail width get fixed automatically.

How can i fix the thumbnail width or fix the overlap permanently.

![EDBE814D-3AC0-4CD3-A76C-C26AF934BC45](https://user-images.githubusercontent.com/108550245/176958075-ff4d34be-29f4-4a3a-b8ce-d27a12dc8aa9.jpeg)

Thanks & Regards,
Manzoor

**Comment by stephanrauh** [comment]
Is updating to the current version of ngx-extended-pdf-viewer an option? It's not that I don't want to help you - but this project is a leisure-time project with a disappointing number of regular contributors (zero), so I fix bug in the current version only.

However, I can give you some clues. I remember the ill-positioned scrollbar. I do not remember what I did to solve it. Most likely it's a CSS issue. There's a CSS variable defining the width of the initial width of the div containing the thumbnails. When you drag the thumbnail width, the width is overwritten with an inline style.

So I'm not sure, but I suppose the issue is related to the CSS rules containing the "200px" bit (in the current version - probably another figure, like 150px, in the old version):

<img width="293" alt="image" src="https://user-images.githubusercontent.com/3045767/176969198-6a6570b8-0e42-4d20-abda-2afd1c7d5c66.png">

**Comment by stephanrauh** [comment]
I like to keep issue open until I know you've managed to solve your issue. So I'd like to hear from you. Whether my hint helped you to solve the problem or not, tell me!

Best regards,
Stephan

**Comment by manzoorsharif123** [comment]
Hi Steph - Will try css and confirm back.

Thanks,
Manzoor

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by manzoorsharif123** [comment]
[Image.jpeg]

i tried implementing this css, unfortunately it is not able to overridden pdf viewer original css.
On run time when i am making these changes in browser this is working but not working with angular.

Any suggestions on this.

Thanks In Advance.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by stephanrauh** [comment]
If you can do the changes in the browser, you can also do them in Angular. You just need to figure out how to do this.

I suppose it's best to do this in the `styles.css`. If you try to add the rules to the CSS code of an Angular component, Angular adds code to make the CSS rules local.

If you're already doing this, you need to increase the priority of your CSS rules until they override the original CSS rules. Some time ago, I've written an article telling you how to do this: https://www.beyondjava.net/gentle-introduction-css

Hope that helps!
Stephan

**Comment by manzoorsharif123** [comment]
Hi Steph - This is fixed, ng deep required to overwrite pdf viewer default css.

thumbnailview component has to be updated rather than side content bar.

Really appreciate your help.

Thanks & Regards,
Manzoor

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by stephanrauh** [comment]
That's great news! `::ng-deep` is a bit dangerous because the Angular team has announced to drop it. However, they're already announcing it for years - it seems to be one of the things that are hard to replace: https://angular.io/guide/component-styles#deprecated-deep--and-ng-deep

If you want to avoid `::ng-deep` you can put your CSS rules into the global styles CSS or your can add a component without view encapsulation (https://angular.io/guide/view-encapsulation).
