### ISSUE TITLE
How do I extract the current cursor position in the PDF?

### ISSUE THREAD

**Issue by rwitmans** [stephanrauh/ngx-extended-pdf-viewer#1466]
Hi! Is there a way to be able to extract the position of where you clicked in the PDF itself? I currently can only get the position somewhere on the website, but not the precise position on the PDF. Thanks for suggestions in advanced.

**Comment by stephanrauh** [comment]
If you're interested in the page number, that's easy. Every page is a canvas, and one of the DOM attributes of the canvas (or one of its parent elements) is the page number.

If you're interested in the position within the page, that's a hard problem. I don't have a clue which coordinates to use. I don't know anything about your raw PDF file, so I can't provide you with useful coordinates. If you're happy with percentages, you're lucky. You can implement this without my help. All you need to do is to find out the height and width of the canvas, and to determine the position of the mouse click relative to the canvas.

One last thing: you'll want to add a `(click)` listener to the canvas (or one of its parent elements, or possibly the text layer because it's above the canvas, so it receives the click event first and there's a connection to the text). You can use the `(pageRendered)` event or the `(textLayerRendered)` event. These events are fired after creating the corresponding `<div>`, so they are a good choice to register the `(click)` event listener.

**Comment by stephanrauh** [comment]
I'm closing the ticket because I'm positive I've been able to help you. If you're still running into trouble, don't hesitate to add comments. I'm still listening to this channel!

Best regards,
Stephan
