### ISSUE TITLE
Bolded Capital B when viewed in dialog breaks the font

### ISSUE THREAD

**Issue by vanh285** [stephanrauh/ngx-extended-pdf-viewer#1474]
![image](https://user-images.githubusercontent.com/82790548/182825059-7449a6a8-59ef-433c-9c8b-84a83e992ac0.png)

**Comment by stephanrauh** [comment]
I'm afraid I need more context. All I can guess is your document is Vietnamese - but since I don't speak your language, I'm not even sure about that.

However, you're reporting a rendering error. So maybe I can help you creating a better error report.

- First, please test your document here: https://mozilla.github.io/pdf.js/web/viewer.html.
- If you can reproduce the error over there, please report the bug here: https://github.com/mozilla/pdf.js/issues. I recommend not mentioning ngx-extended-pdf-viewer, because I just sort of highjacked the PDF viewer of Firefox to display PDFs in Angular applications.
- If the file renders fine on Mozilla's showcase, please run a test in my showcase: https://pdfviewer.net/.
- If it works fine in my showcase, it's probably a configuration issue of your project.
- Otherwise, it may be an error I introduced. However, that's unlikely because I didn't modify the rendering engine.

In any case, when reporting the bug, please add the PDF file, and instruction how to reproduce the bug, and the messages of your console window.

Best regards,
Stephan

**Comment by vanh285** [comment]
It seems that the problem is not with the package. Thank you for the support. Problem occurs only with uploaded MS Word documents converted into pdf and then viewed. Thank you for the quick response!

**Comment by stephanrauh** [comment]
You're welcome!
