### ISSUE TITLE
Can not dynamically change pdf inside src attribute

### ISSUE THREAD

**Issue by Raiseku** [stephanrauh/ngx-extended-pdf-viewer#1482]
Hello, i have a problem on binbdings variable to a src attribute

This is how i defined the ngx tag:
```html
 <ngx-extended-pdf-viewer id="ngxPDFviewer" [src]="currentPdf" [showPrintButton]="false" [showDownloadButton]="false" [showOpenFileButton]="false" [useBrowserLocale]="true">
</ngx-extended-pdf-viewer>
```

and this is how i defined my .ts file: 
```typescript
 import { Component, OnInit } from '@angular/core';
  @Component({
    selector: 'app-view-classificazione',
    templateUrl: './view-classificazione.component.html',
    styleUrls: ['./view-classificazione.component.css']
  })

  export class ViewClassificazioneComponent implements OnInit {
    public currentPdf = "../../assets/img/pdf-test.pdf";
    ngOnInit(): void {

    $("#tableDocumenti").on("click", "tr", function (event) {
      var $item = $(this).closest("tr").find(".titolo_doc").text();
      if($item == "1"){
        this.currentPdf = "../../assets/img/dummy.pdf";
      } 
    });
}
}
```
Now, when i click to a tr inside my table, if the text is "1" the pdf should change to another one, which is called "dummy.pdf". 
Is this the correct way to do what i need?

i'm using Chrome and i'm on Windows

**Comment by stephanrauh** [comment]
Yes. But you're using jQuery, and Angular doesn't react to jQuery events. There are several approaches to solve this, but for starters, simply wrap the assignment in a timeout:
```typescript
  setTimeout(() => this.currentPdf = "../../assets/img/dummy.pdf");
```

If that works, read the full story about Angular change detection and timeouts on my blog: https://www.beyondjava.net/zonejs

**Comment by stephanrauh** [comment]
BTW, I'd appreciate your answer if it works, so I know I can close the ticket.

Best regards,
Stephan

**Comment by Raiseku** [comment]
Hello, i have tried you're code but that didn't work. I thank you anyway because i didn't know that Angular couldn't react to jQuery events and because of this i have completely changed my approach, now i directly use mat-table and ng-container and everything works!

**Comment by stephanrauh** [comment]
When you say "it doesn't work", you're probably referring to the `setTimeout()` bit? Strange - usually it does work, unless you've activated the `OnPush` change detection strategy. You could have used something like triggering Angular's change detection manually.

Be that as it may, using `mat-table` is a much more reliable approach. For what it's worth, I don't like the approach of `mat-table` because its so cumbersome. If you're looking for a simpler alternative, there's also https://swimlane.github.io/ngx-datatable/ (among a plethora of other table widgets).
