### ISSUE TITLE
Cannot read properties of undefined (reading 'div') - scrollPageIntoView

### ISSUE THREAD

**Issue by csensoft1** [stephanrauh/ngx-extended-pdf-viewer#1510]
scrollPageIntoView - when using this method to scroll to place on a page. I am getting the below erro

ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'div')
TypeError: Cannot read properties of undefined (reading 'div')
    at PDFViewer.scrollPagePosIntoView (viewer-2.14.304.min.js:22:164794)
    at NgxExtendedPdfViewerService.scrollPageIntoView (ngx-extended-pdf-viewer.mjs:3033:16)

How do I fix this problem? Sorry if it is repeat question. I tried to search online but could not find a appropriate solution. 

Thanks

**Comment by stephanrauh** [comment]
The showcase demo (https://pdfviewer.net/extended-pdf-viewer/scrolling) still works, so I suppose it's got something to do with your setup. How can I reproduce the issue?

**Comment by csensoft1** [comment]
Hi Stephan,

 Thanks for the response. 
This is my html file
<div class="container-fluid mt-5">    
    <div class="row">
        <div class="col">
            <ngx-extended-pdf-viewer [src]="src" [height]="'90vh'" 
                [(zoom)]="zoomPercentage"
                [showPresentationModeButton]="true"
                [showSpreadButton]="false"
                [showPropertiesButton]="false"
                [showOpenFileButton]="false"
                [showBookmarkButton]="false"
                [useBrowserLocale]="true"                 
                [(formData)]="formData"
                (formDataChange)="[setFormData($event), resetTimer()]" 
                (pageRendered)="[delayedUpdateFormData(), resetTimer()]"
                (pageChange)="resetTimer()"
                (pagesLoaded)="resetTimer()"
                (pdfLoaded)="resetTimer()"
                (pdfDownloaded)="resetTimer()"
                (currentZoomFactor)="resetTimer()"
                (pdfLoadingStarts)="resetTimer()"
                (beforePrint)="resetTimer()"
                (afterPrint)="resetTimer()"
                [textLayer]="true"
                [(page)]="page">
            </ngx-extended-pdf-viewer>
        </div>
    </div>
</div>
On Typescript, I have these after assinging pdf file to src
            this.zoomPercentage = zoom;
            this.page = 2;
            this.ngxService.scrollPageIntoView(2, {top: '100%'});

**Comment by stephanrauh** [comment]
Sounds like a timing issue. In this particular setup, you don't need to call `this.ngxService.scrollPageIntoView(2, {top: '100%'});`. Assigning the `[page]` already does the trick.

I suppose the bug happens because you're trying to scroll the page into view before it has been rendered. That's simply I use case I didn't think of when implementing the code. You can work around the bug by delaying the call until the page has rendered, i.e. using the event `(pageRendered)`. At the moment, I don't know when precisely the divs are available. `(pagesLoaded)` fires a bit earlier, maybe the divs are already available at that point of time.

**Comment by csensoft1** [comment]
(pageRendered) works fine. Thank you, Stephan.
