### ISSUE TITLE
Print feature is not working when the ngx-extended-pdf-viewer control is in a modal form

### ISSUE THREAD

**Issue by hararm** [stephanrauh/ngx-extended-pdf-viewer#152]
Print feature is not working when the ngx-extended-pdf-viewer control is in a modal form. Launch ngx-extended-pdf-viewer control as part of the modal form and by clicking on the Print button in the browser print dialog(Chrome, Firefox) the actual pdf document will not be shown instead the printed document will consist of controls located on the modal form.
![pdfdoc](https://user-images.githubusercontent.com/12174760/66580491-800eb480-eb4c-11e9-921e-701ba9484c4a.jpg)
![printdialog](https://user-images.githubusercontent.com/12174760/66580543-9157c100-eb4c-11e9-9dcf-74f154c280b4.jpg)

**Comment by stephanrauh** [comment]
Interesting. That's definitely something to fix. Give me a hint how to reproduce the bug. Are you using Bootstrap, Angular Material, and any other UI framework?

**Comment by stephanrauh** [comment]
I've sort of managed to reproduce the bug. It looks slightly different on my machine, but it's clear that the modal is interfering with the print. In my case, the print shows a gray area over the PDF file.

Before clicking "print":
<img width="688" alt="image" src="https://user-images.githubusercontent.com/3045767/67120960-a8e91680-f1ea-11e9-8d43-a91cefa11489.png">

What's being printed:
<img width="763" alt="image" src="https://user-images.githubusercontent.com/3045767/67121086-f36a9300-f1ea-11e9-97c0-ca17da4e6dbc.png">

**Comment by stephanrauh** [comment]
> after clicking on print button the whole body appeared in the print preview mode. 

Well... that's probably a side-effect of how the pdf.js printing algorithm works. The general idea is to hide the entire page, add the PDF file as a collection of images, and to print the result. 

As it turns out, this algorithm is vulnerable to side-effects. Currently, I can only guess. It seems that the "hide the page" bit doesn't work. Your hint concerning the `z-index` also sounds plausible.

**Comment by stephanrauh** [comment]
Increasing the `z-index` might be an option. Currently I'm trying a different approach: hiding the modal altogether. The print algorithm hides everything except the print container with a CSS rule. As it turns out, the CSS rule is overrules by a `display: block` of the modal. Let's examine if we can fix it.

**Comment by stephanrauh** [comment]
I've just released version 1.6.2. It improves the compatibility with Bootstrap significantly.

However, I haven't found out yet how to correct the font size, so you need to wrap Bootstrap in a media query. Otherwise, your print is reduced to 62.5% of the original size.

For example, if you're using SCSS and Bootstrap 4, remove the import of Bootstrap.min.css from the Angular.json file. Instead, import it by including Bootstrap by adding this line to the global `styles.scss` file:

```css
@media screen {
  @import '../node_modules/bootstrap/scss/bootstrap';
}
```
Caveat: this trick only works with the SCSS version of both `styles.scss` and `bootstrap.scss`. It doesn't work with simple CSS.

**Comment by stephanrauh** [comment]
Like always: I'd like to hear from you, even if the bug fix works. Otherwise I'll never know if I've closed the ticket too early. :)

**Comment by hamzou247** [comment]
Hello,

Thank you for solving the issue. Still i'm experiencing quite the same thing on mobile IOS. Any idea of why?
![image](https://user-images.githubusercontent.com/57844322/68998264-89f4a780-08b0-11ea-9216-38a5e5bfa531.png)

**Comment by stephanrauh** [comment]
Bonsoir,

on my iPad printing behaves even more strange. Instead of printing the PDF page, it prints the HTML page. I can see that pdf.js prepares the print, but it seems that the media query is ignored. I've attached a screenshot of my preview.

I've been hunting the iOS bug for a long time (see #83). There are some pretty arcane solutions and work-arounds for pdf.js. In the end, I decided to close the ticket without solving it. You're the first one asking for the feature. If you've got a solution, I'll happily accept your pull request, but currently I don't have a clue what's going wrong, or how to debug it.

There's a simple work-around: click on the "download" button and print it using the context menu ("send to printer"). Maybe you have to enable the download button and tell your users about it, but it works like charm.

Best regards,
Stephan
 

![image](https://user-images.githubusercontent.com/3045767/68998609-0d17fc80-08b5-11ea-8a0e-d7e0023f8565.png)

**Comment by stephanrauh** [comment]
I've went over the print CSS again. When you update to version 9.0.0, brace yourself for breaking changes. I hope I've managed to avoid them, but it's hard to tell.

**Comment by rekna1** [comment]
I had similar problem, only first paged was printed, and I was able to solve it in all browsers by adding to css:
`#printContainer { position: absolute; }`

**Comment by stephanrauh** [comment]
@rekna1 Does `#printContainer { position: static; }` work, too? That's the default used by pdf.js.

**Comment by rekna1** [comment]
just tried it, static does not seem to work in my case..

perhaps because of position absolute of containing element.
included approximate structure of page with soms position/display attributes
```
div                      position:relative

  div                    position:absolute; display:flex; flex-flow:column;

    div                  flex:auto

    div                 flex:1

       ngx-extened-pdf-viewer
```

**Comment by stephanrauh** [comment]
It must be something different. The media query hides ngx-extended-pdf-viewer and all its parent elements. At runtime, the print container is moved to the `<body>` tag:

![image](https://user-images.githubusercontent.com/3045767/134062675-df52b31d-7913-41c7-aa5a-437348b7ac6d.png)

I'm reluctant to stray away from the defaults. Maybe this approach works:
```css
@media print {
  html,
  body
  #printContainer { 
    position: static !important; 
  }
}
```

(Of course, `!important` is an act of desperation, but it's OK for a proof of concept).

**Comment by rekna1** [comment]
I just tried with replacing position absolute with the above... it's not working, only one page in preview. 

I also verified that position: static is applied in the chrome inspector and it is. 

Then reverted to position absolute and it works again.
