### ISSUE TITLE
setting pdfDefaultOptions.rangeChunkSize has no effect

### ISSUE THREAD

**Issue by productivityindustries** [stephanrauh/ngx-extended-pdf-viewer#1529]
**Describe the bug**
No matter the value set for pdfDefaultOptions.rangeChunkSize, it doesn't change how many bytes are used.

**Version info**
- Version of ngx-extended-pdf-viewer 14.5.3

 - Browser Version 105.0.5195.102 (Official Build) (x86_64)

**To Reproduce**
Use a relative big PDF file, set a value for pdfDefaultOptions.rangeChunkSize then observe chunks are still requested using the default value of 65536 bytes.

**Additional context**
I have debugged a bit this issue and I may have found the issue.
While the value is correctly set into AppOptions in overrideDefaultSettings(), the implementation of AppOptions (https://github.com/mozilla/pdf.js/blob/803e7af5954b8d84f8dab2b632a3167c7fd14e46/web/app_options.js) returns in getAll() only properties defined in this file in const defaultOptions (see https://github.com/mozilla/pdf.js/blob/803e7af5954b8d84f8dab2b632a3167c7fd14e46/web/app_options.js#L357). Even though the property is set in userOptions, it won't be returned, leaving it undefined and then gets finally defined by default here: https://github.com/mozilla/pdf.js/blob/ae12a219d1946edff565a0fd81f1398584635ae6/src/display/api.js#L340
To fix this would require to change app_options.js

However for those advanced settings it may be beneficial to expose another interface to pass arguments to pdf.js getDocument (wrapped by PDFViewerApplication.open in this project) leaving more control to the application (for both openPDF() and openPDF2()).
For example it could be implemented in NgxExtendedPdfViewerComponent as @Input() extraParameters: any; (or typed using DocumentInitParameters ) then in openPDF() and openPDF2() it would override the properties defined in extraParameters into 'options' before calling  PDFViewerApplication.open()

Thank you!

**Comment by stephanrauh** [comment]
As you're probably aware of, I'm maintaining my own fork of pdf.js, so modifying `AppOptions` shouldn't be an issue. I just need to debug it myself and wrap my head around it. Your detailed analysis makes it sound like a walk in the park.

As for the `extraParameters`: interesting idea. Let me ponder about it. I never introduced such a parameter because I didn't want to make these options a part of the core API. Setting the internal parameters apart from the first-class citizens allows me to get away when Mozilla changes their internal API. At least I hope so. But maybe I'm too careful.

**Comment by stephanrauh** [comment]
Strange. It seems the feature never worked. Funny thing I remember testing it. 

I don't want to modify the API because I've documented for such a long time (even if it never worked). @productivityindustries, your awesome research made it easy to fix the bug without modifying the API. The bugfix is going to land with version 16 soon.

BTW, sorry for the long delay. The project has become so popular I struggle keeping up with the flood of new issues. Can I talk you into supporting me and joining the project?

**Comment by stephanrauh** [comment]
Your bugfix has landed with version 16.0.0-alpha.8.
