### ISSUE TITLE
PDF issue with search results display order 

### ISSUE THREAD

**Issue by akhilaet-92** [stephanrauh/ngx-extended-pdf-viewer#1556]
Hi @stephanrauh ,

I am using ngx-extended-pdf-viewer version 15.0.5 in my angular 13 application and facing issue with search result display order. The search results are showing up in random way and not according to page-wise. This happens only with random pdf files and key words. Providing the details of a reproducible scenario below:

I am attaching a sample pdf file in which I am facing issue with key word "Sample". The search result highlights some random occurrence instead of the first one, that needs to be highlighted. Attaching screenshot below.

How do we resolve this issue? Appreciate any help here.

![image](https://user-images.githubusercontent.com/62993854/195649332-e2c3757b-4033-4258-811d-8c5eb4e04572.png)

[c4611_sample_explain.pdf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/9778586/c4611_sample_explain.pdf)

**Comment by stephanrauh** [comment]
I've checked your file and found that the page numbers of the search results are in the correct order. The results on page 1 are shown first, followed by page 2, followed by page 3, and so on. It's not that the search result jumps arbitrarily between pages. Correct me if I'm wrong - because that'd be something I consider a bug.

However, the search results within the page seem to be shown randomly. There's nothing you or I can do about it. The only one who can fix this is the author of the PDF file. Many PDF files consists of several blocks - roughly comparable to an HTML `<div>`, each of them having a position and content. Looking at your example file, I suppose the page footer is a separate block. Unfortunately, in the source code of the PDF file it's before the block containing the bulk of the text, although from the human reader's point of view, it's the other way round.

The search algorithm extracts the text from the PDF file without checking the coordinates. Truth to tell, I'm not even sure it's possible to write an algorithm simulating the natural read flow. There are just too many options in the PDF world. Among other things, there are languages like Arabic, writing from the right to the left, or even Chinese, where some texts are written in colums, so the primary read direction is top-down.

If you think the issue needs to be fixed, please open a bug ticket at the base project: https://github.com/mozilla/pdf.js/issues
