### ISSUE TITLE
Other pages is loading forever even after several reload has been done

### ISSUE THREAD

**Issue by ajlsemana** [stephanrauh/ngx-extended-pdf-viewer#1560]
Greetings!!!

**Describe the bug**
We are sometimes not able to see the other pages content and we noticed that it keeps loading forever during an on-going session.

**Version info**
"ngx-extended-pdf-viewer": "^3.7.2",

**Desktop (please complete the following information):**
 - Chrome Version 106.0.5249.119 (Official Build) (64-bit)

**To Reproduce**
Just open and close the pdf viewer.

**Screenshots**
![pdf-viewer-page-not-loading](https://user-images.githubusercontent.com/7235178/196755384-d6ad2ff8-124d-454e-a895-5dbbbaa9a2cc.jpeg)

![image](https://user-images.githubusercontent.com/7235178/196755798-9e07c2f4-105a-476f-a35b-013d969e32a1.png)

![image](https://user-images.githubusercontent.com/7235178/196756119-2179006c-5090-4ac5-be35-cd73a7717d6d.png)

Thank you so much.

**Comment by stephanrauh** [comment]
I'm unhappy to disappoint you, but I'm afraid I can't support version 3.7 for two reasons:

- It requires an old version of Angular, which requires an old version of node.js. It'd take me hours to install the correct versions.
- I hardly manage to keep up with new issues. Supporting the newest version only is my way to cope with the unexpected success of the library.

Can you update to the latest version? If so, do you still observe the bug?

Best regards,
Stephan

**Comment by stephanrauh** [comment]
I didn't hear from you for a long time, so I assume you've solved the issue one way or another. If you've managed to solve the bug, I'd like to hear from you. If you haven't, I'd like to hear from you, too, because even negative feedback is an opportunity for improvement.

Best regards,
Stephan

**Comment by ajlsemana** [comment]
Hi Steph,

Sorry for the late response.

Unfortunately, we did not update to the latest version since our app is running in Angular 6 for very long time and it is quite hard now to update it to latest. 

Issue still persist in the PDF viewer, as a workaround we just added a reload button that will empty and refill back the [src] to act as sort of reload, though it will take so many retries before all the pages shows completely.

We highly appreciated your concern.

**Comment by stephanrauh** [comment]
I see. Maybe - just maybe - reducing this timeout helps you:

https://github.com/stephanrauh/pdf.js/blob/1dec7598158f380f284b06f45ebb6e1281060445/web/app.js#L82

By default, the timeout is set to ten second, but at some point in time, I made a mistake, and I never found out what it was. Reducing the timeout from 10 seconds to 10 milliseconds worked surprisingly well. The only victim was my proudness, because I still don't know what the root error is.

Be that as it may, you can try to reduce this timeout in your application. Unfortunately, I don't know how you can do this, because you're probably using the binary files of the npm package. I suppose you can fork https://github.com/stephanrauh/pdf.js, check out the old branch, and compile the base viewer manually. You can see on the console window which branch of pdf.js you'll want to check out: both the version number of ngx-extended-pdf-viewer and the base library pdf.js are printed.

**Comment by ajlsemana** [comment]
Thank you so much. Our team will try this idea that you've shared.

**Comment by stephanrauh** [comment]
@ajlsemana Please keep me in the loop. I'm looking forward to learn how your team managed to solve the issue, and if there's something I can do in my limited spare time, I'll be happy to help!
