### ISSUE TITLE
./node_modules/ngx-extended-pdf-viewer/fesm2015/ngx-extended-pdf-viewer.mjs 4839:14318-14330

### ISSUE THREAD

**Issue by tavogusta19** [stephanrauh/ngx-extended-pdf-viewer#1593]
hello, I have a problem to pdf viewer

![image](https://user-images.githubusercontent.com/43972767/204005667-be775e97-e7e3-473d-98ec-8bf8ae6c15d0.png)

![image](https://user-images.githubusercontent.com/43972767/204005692-4a6342c3-fde8-45dc-ace9-a14a507b6fb9.png)

**Comment by stephanrauh** [comment]
This looks like an Ivy problem. As you may or may not know, the Angular team has implemented a new rendering engine called Ivy. It's superior, and most of the time it works out of the box, but it's impossible to provide a library that's both compatible to the earlier rendering engine and still benefits from the advantages of Ivy. 

That's why I decided to abandon pre-Ivy compatibility with version 11. Try downgrading to ngx-extended-pdf-viewer 10.5.0. That's the latest version compatible to the old rendering engine.

However, if your project allows it, please upgrade to Ivy. More likely than not, you won't notice the difference, except it works a tad more smoothly. Binaries tend to be smaller, the application is faster, and it's easier to debug the code.

**Comment by stephanrauh** [comment]
Off topic - si disculpas mi curiosidad: ¿28 centigrados en España? ¿Donde vives? Estoy friando con casi 0 centigrados. ¡Estoy un poco envidioso! :)

**Comment by stephanrauh** [comment]
Back to topic: maybe this discussion helps you: https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/1343

**Comment by stephanrauh** [comment]
I'm closing this ticket now. If you've still got problems, feel free to open it again.
