### ISSUE TITLE
PDF viewer freezes ionic app on iOS 16.1

### ISSUE THREAD

**Issue by hinkelrex** [stephanrauh/ngx-extended-pdf-viewer#1615]
**Describe the bug**
Scrolling through PDFs in the viewer occasionally freezes the entire ionic application.
Pages will stop rendering and shortly after, the entire app will become unresponsive.
"[IPC] Connection::waitForSyncReply: Timed-out while waiting for reply for WebPage_TouchEventSync" is the only error I can read through XCode.

**Version info**
- 15.2.0 
- Occurs on both normal and bleeding-edge branch
 
**Smartphone**
 - Device: iPhone 13, iOS 16.1

**To Reproduce**
It is reproducable in a blank ionic angular project with nothing in it but the pdf viewer.
To set up such a project:

    ionic start myApp super --type=ionic-angular
    cd myApp
    ng add ngx-extended-pdf-viewer

Then replace "ion-router-outlet" in the app component with "app-example-pdf-viewer".

It doesn't happen on all PDF files though and unfortuantely I can't share the ones I have problems with due to copyright. 
I will try and find a shareable PDF to reproduce the issue and to provide a good sample project for this bug. 

Maybe there are some ideas on what could cause this.

Thank you for your work.

**Comment by stephanrauh** [comment]
Does this bug happen only on iOS? Is it specific to iOS 16? Which version of ionic are you using?

I also need your help because I've never installed a self-written Ionic application on an iOS device. How do I do that?

BTW, if you're allowed to use Browserstack, give it a try. I suppose it's easier to get the logs of a frozen device from Browserstack.

**Comment by hinkelrex** [comment]
After some more testing I concluded that the this isn't a problem of this PDF Viewer since the problem does also occur with other PDF viewers (specifically the ng2 one), so I guess is that it's either something from pdf.js or webkit, since the problem also doesn't occur on Android. 

For reference I could resolve my spcific issue by splitting the problematic PDFs into images and converting those into a PDF again.
Maybe that means that some element within the PDF caused the issue. I couldn't poinpoint exactly what that could be though. The only thing I noticed was that the error seemed to occur mostly in PDF files exported from powerpoint.

Thank you for your time and the hard work of this great package.

**Comment by stephanrauh** [comment]
Interesting. Both ng2-pdf-viewer and ng2-pdfjs-viewer use the original, unmodified pdf.js library, so it really might be a problem of the base library. Do you think you can pin down the bug more closely? If so, I can reach out to the Mozilla team and connect you with them. There's just one problem: you can't open a bug ticket over there because they've begun to triage the flood of new issues, rejecting everything that's not directly associated with Firefox. So you either need to convince the Mozilla team that your issue also happens in Firefox, or to pique the curiosity of one of the developers.

I'm reluctantly closing this ticket now. But I'm still listening to this channel, so feel free to add comments if you've got new insight.

Best regards,
Stephan
