### ISSUE TITLE
Feature Request: Enhance Find In Document

### ISSUE THREAD

**Issue by pedrojrivera** [stephanrauh/ngx-extended-pdf-viewer#162]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Would it be possible to expose additional elements from the search feature? Currently you provide a service to perform our own text searches. What would be excellent is the ability to toggle (1) Highlight All, (2) Match Case, (3) Whole Words. 
Also, would be nice to get the feedback from the search result. See screen shots below for examples. By having these features exposed, I could expose them to our custom interfaces. 

I would be glad to assist in adding these features but don't know if you had already planned in exposing these additional properties. 

**Additional context**
<img width="686" alt="find-2" src="https://user-images.githubusercontent.com/32545483/67752873-2b9f7c00-fa0a-11e9-804e-c8f43fe9bb0f.png">
<img width="504" alt="find-1" src="https://user-images.githubusercontent.com/32545483/67752874-2b9f7c00-fa0a-11e9-89d5-4f1b7c8dfa00.png">

**Comment by stephanrauh** [comment]
Well, pull requests are always welcome!

Currently, the `PdfViewerService` simple remote-controls the UI. I guess you can follow the same approach to implement your three features.

I suppose it'd be also nice to have a real programmatic API. For example, `find()`  could return a list of all search results. Currently, that's beyond the scope of the PDF viewer because that'd require us to use internal APIs. But if you find out how to do stuff like this, you're welcome to open a second ticket and provide it as a second pull request.

**Comment by stephanrauh** [comment]
@pedrojrivera Did you already have some time to implement this feature? If not, I'd implement it myself soon.

**Comment by stephanrauh** [comment]
I've just published version 1.8.0 featuring the advanced search. Note that there's a small breaking change: now you need to add `loadash.deburr` to your package.json (`npm install loadash.deburr --save`).

There's a live demo at https://pdfviewer.net/find.

<img width="984" alt="image" src="https://user-images.githubusercontent.com/3045767/70946663-dc63e800-2057-11ea-9c32-0229d3e5e275.png">

<img width="255" alt="image" src="https://user-images.githubusercontent.com/3045767/70946719-fd2c3d80-2057-11ea-94a8-7b68d4979974.png">
