### ISSUE TITLE
on every double click zoomChange is triggered

### ISSUE THREAD

**Issue by Julian-B90** [stephanrauh/ngx-extended-pdf-viewer#1645]
**Describe the bug**
First Change the Zoom Level for example "100%". Then made a double click on the PDF the Zoom Level Change to "page-width"
Then made a double click again the zoom Level change again.

**Expected Behavior**
In "Text Mode" i would expect selecting the word on double click.

**Version info**
- Version of ngx-extended-pdf-viewer 15.2.2

**Desktop (please complete the following information):**
Microsoft Edge Version 108.0.1462.76 (Offizielles Build) (64-Bit)
 
If you really can't provide me a reproducer, please tell me how to reproduce the behavior:
1. Change Zoom Level to 100%
2. Made a double click
3. Zoom Level Change
4. Made a double click
5. Zoom Level Change again
6. In the Version 11.2.0 the zoom Level only change once

**Comment by stephanrauh** [comment]
Strange. You say it worked differently in version 11.2? Now it works like I've intended it to work. The way zooming worked on iOS devices until Apple removed my favorite feature. So you're saying the double-tap gesture was broken. :)

The problem is that Apple has removed the feature. I wonder if anybody expects the double-tap to do anything useful. I'm afraid not. So I believe I ought to remove the feature. I hate this because it used to be a useful feature, but I also hate to confuse users.

Any ideas?

**Comment by Julian-B90** [comment]
Hey @stephanrauh, 

maybe we can add e feature flag for this?

**Comment by Julian-B90** [comment]
In which situation is the else block executed?

```ts
if (this.zoom !== pdfDefaultOptions.doubleTapZoomFactor && this.zoom + '%' !== pdfDefaultOptions.doubleTapZoomFactor) {
      this.previousZoom = this.zoom;
      this.zoom = pdfDefaultOptions.doubleTapZoomFactor; // by default: 'page-width';
      await this.setZoom();
    } else {
      if (this.previousZoom) {
        this.zoom = this.previousZoom;
      } else {
        this.zoom = 'page-width';
      }
      await this.setZoom();
    }
```

**Comment by stephanrauh** [comment]
The "then" part is the default. It's executed when the zoom isn't the target zoom.
The "else" part is run when on the second double-tap. It resets the zoom to its previous value.

The idea is supporting a website looking like a newspaper. It allows you to enlarge a column or an image in  so you can read it comfortably, and to be able to reset the zoom so you can see the entire document again. 

Unfortunately, my library doesn't know about the size of the columns or images (if there are any). It doesn't even know how much white space is on the left and right hand sides of the text. These restriction make the double-tap feature much less useful than I'd like.

And, of course, in text mode, the feature is more or less useless because a double tap or double click invokes two actions. That's almost certainly confusing.

Adding a feature toggle sounds like a good idea to me.

**Comment by stephanrauh** [comment]
I've added your toggles and published it with version 16.0.0-alpha.3. I tried to use sensible defaults, knowing that this is a breaking change.

I didn't publish the new version of the showcase yet, but you can see in the commit above or the screenshot below what the three new `pdfDefaultOption`s mean. I'm looking forward to your feedback!

<img width="1085" alt="grafik" src="https://user-images.githubusercontent.com/3045767/212499853-fa8ec1a7-d330-4e21-82c0-f0d84035a142.png">

**Comment by Julian-B90** [comment]
Thank you very mutch vor your work i will test it on monday ;-)

**Comment by stephanrauh** [comment]
Monday's almost over. Any news? :)

**Comment by Julian-B90** [comment]
Hey @stephanrauh i have test it with doubleTapZoomsInTextSelectionMode. Its fine ;-) thank you very mutch
