### ISSUE TITLE
Pdf viewer does not get fully destroyed after closing the page

### ISSUE THREAD

**Issue by tedKarabeliov** [stephanrauh/ngx-extended-pdf-viewer#1661]
Hello,

We have an Angular 15 application using the viewer. We use the viewer in 2 pages which have routing between them. So the user can be on the first page with the viewer on it, click on a link to the second page, and have the viewer on the second page.

Now when we switch the pages, angular destroys the component along with the ngx-extended-pdf-viewer.
When the viewer initializes for the second page, we get initialization errors:

"You're trying to open two instances of the PDF viewer. Most likely, this will result in errors."
"Could not load the translation files for the PDF viewer. Check the flag useBrowserLocale, check the locales subfolder of the assets folder, or add the locale definition to the index.html"

If we explicitly wait for 500 milliseconds, the issue disappears.

So my conclusion is that the viewer doesn't get destroyed fast enough and does it asynchronously after the component is destroyed (ngOnDestroy is called)

My question is: is there a way to prevent this without artificially waiting? For example wait for an event or something?

If you need additional clarification I can setup an example project.

Thanks in advance!

**Comment by stephanrauh** [comment]
I'm afraid you'll have to put up with the 500 milliseconds wait. You can try to encapsulate one of the viewers (or both) in an iFrame, as shown in https://pdfviewer.net/extended-pdf-viewer/side-by-side. But that's a bit cumbersome and sort of a hack (albeit a reliable one).

The root cause is the asynchronous nature of the base library. Almost everything in pdf.js is asynchronous. So the problem is not that `ngOnDestroy` is called too late. Instead, pdf.js takes some time to tidy up. I'm afraid there's nothing I can do about it.
