### ISSUE TITLE
getting js file  error while creating  new angular library using ngx-extended-pdf-viewer

### ISSUE THREAD

**Issue by simran9988** [stephanrauh/ngx-extended-pdf-viewer#1664]
Hi i am creating angular library using Ngx-Extended-pdf-viewer. i am able to copy your library assets folder into my newly created library using workflow.when i download my package into new app i also get the assets folder along with  the my library in the node module.
but i am facing this error:
GET http://localhost:4200/assets/op-chaining-support.js net::ERR_ABORTED 404 (Not Found)
GET http://localhost:4200/assets/pdf-2.16.453-es5.min.js net::ERR_ABORTED 404 (Not Found)

i want to know  how i can set assets folder path from  my-libaray to new app so i can get rid of error.
here is the  screenshot of my node modules after insatlling my libraray with assets folder.
![Capture1](https://user-images.githubusercontent.com/105843633/215744492-fd78ad2d-0028-4400-91e3-716fe5ff1279.JPG)

**Comment by stephanrauh** [comment]
You won't like my answer, but my honest answer is I don't know, and I believe this is a shortcoming of Angular libraries.

The last time I investigated the topic, Angular libraries allowed you to share TypeScript code, but they didn't allow you to share assets. That's a pain in the ass to me because the entire PDF rendering engine resides in the assets folders.

I worked around the topic by asking my users to add a couple of lines to their `angular.json` (see https://pdfviewer.net/extended-pdf-viewer/getting-started and click on the tab "Angular CLI"). As you can imagine, this didn't work. Only when I implemented an Angular schematics manipulating your `angular.json`, the flood of confused questions slowed down.

I hope the Angular team is going to implement support for assets (or maybe they already did and I missed it).
