### ISSUE TITLE
Compatbility issue while updating to angular 13

### ISSUE THREAD

**Issue by mayankgpt185** [stephanrauh/ngx-extended-pdf-viewer#1678]
Hi, 

I'm trying to update my angular version to 13.3.12 but I found no compatible versions of 'ngx-extended-pdf-viewer'

when I try to use the latest version it gets installed successfully but while serving the project i'm getting this
'An unhandled exception occurred: Script file node_modules/ngx-extended-pdf-viewer/assets/pdf.js does not exist.' 

Please help me fixing this issue.

Regards,

**Comment by losbeekos** [comment]
Since v15 of this library there is AMD modules support (see: https://github.com/stephanrauh/ngx-extended-pdf-viewer/releases/tag/15.0.0). So the filenames and paths changed (see screenshot below), you'll have to change that accordingly.

![Screenshot 2023-02-10 at 15 10 22](https://user-images.githubusercontent.com/3503447/218112448-012b7995-9528-4a53-8edf-f33377e504cc.png)

**Comment by stephanrauh** [comment]
I suspect, you, @mayankgpt185, are coming from a very old version of ngx-extended-pdf-viewer. I also suspect your problem isn't a runtime problem, but a compile-time problem. If `ng build` shows the same error message, it's a compile-time problem. Otherwise, I'd be very confused.

Once upon a time (ok, one or two years ago), I simply called the files `pdf.js`, `pdf.worker.js`, and `viewer.js`. This approach worked most of the time, but after updating many users ran into caching issues. So I decided to rename the JavaScript files. Now, the version number is part of the file name. Plus, the version number changes each and every time I publish a new version.

As a consequence, you need to configure your `angular.json` differently. I reckon the `assets` section of your `angular.json` referenced the exact file names, including `node_modules/ngx-extended-pdf-viewer/assets/pdf.js`. Use wildcards instead. I've documented that at https://pdfviewer.net/extended-pdf-viewer/getting-started (and click on the "Angular CLI" tab).

```json
  "assets": [
    "src/favicon.ico",
    "src/assets",
    {
      "glob": "**/*",
      "input": "node_modules/ngx-extended-pdf-viewer/assets/",
      "output": "/assets/"
    }
  ],
  "scripts": []
```

If you're still stuck: The best way to spot the bug is to create a fresh project. That's just a temporary project that's guaranteed to run. So you can compare the configuration of the working project to your broken project. Usually, this helps you to find the problem within minutes. Setting up the reference project takes five minutes at most:

1. `ng new my-demo-project`
2. `cd my-demo-project`
3. `ng add ngx-extended-pdf-viewer`  (and accept all the defaults)
4. Add the new component `<app-example-pdf-viewer>` to your `<app-component>` to display the PDF file.
5. ng s -o

**Comment by stephanrauh** [comment]
I'm closing this ticket now because I'm positive @losbeekos and I gave you enough hints to solve the issue yourself. If you need more help, don't hesitate to post to this ticket. I'm still listening.

BTW, kudos to Jeroen for chiming in. It's good to know that users start helping other users! Thanks a lot!

Best regards,
Stephan
