### ISSUE TITLE
[logLevel]="0" still show log in console

### ISSUE THREAD

**Issue by jordankkk** [stephanrauh/ngx-extended-pdf-viewer#1692]
**Describe the bug**
set [logLevel]="0" still show log in console

**Version info**
- 16.0.2, 15.2.2

**Desktop (please complete the following information):**
 - All Browser
 

**To Reproduce**
set [logLevel]="0"

**Screenshots**
![chrome_zuwJFMrCe1](https://user-images.githubusercontent.com/38534295/220814884-6b421087-a014-4c68-a69d-6523f75e55e4.png)

Thanks

**Comment by stephanrauh** [comment]
I'm not sure about this. I can see why seeing the version number is confusing after setting `[logLevel]="VerbosityLevel.ERROR"`. The version number is obviously not an error. But I consider it an important information. When I receive a bug report, I'm always happy if the version number is included because it narrows things down. So I'm reluctant to suppress it.

However, you can suppress it yourself. https://pdfviewer.net/extended-pdf-viewer/filtering-console-log shows you how to do it. At least I hope so - I feel I need to re-phrase the text. The bottom line is you can define a closure that receives every log message. If your closure returns `false`, the message isn't printed to the console.
