### ISSUE TITLE
Bad Pdf.js version

### ISSUE THREAD

**Issue by darvisdd** [stephanrauh/ngx-extended-pdf-viewer#1697]
Hello.

I had the ngx-extended-pdf-viewer version installed
and everything was working OK.

I recently renewed the PC, when installing it from 0 I get a problem that I don't see how to solve.

Version of ngx-extended-pdf-viewer: ^16.0.2
PDF.js version in assets: 3.3.491
Version requested by the browser when executing the project: 3.3.492

And that is the problem. The version of the Assets of the library and that of the requested by browser does not match.

Could you tell me how to solve the problem?

Thank you

![image](https://user-images.githubusercontent.com/126679258/222142405-82b04887-04d5-4f3d-a128-43e9e2a8da0d.png)

**Comment by stephanrauh** [comment]
That's strange. I'd love to investigate the topic, but unpgk.com is down again, so investigating is not as easy as it should be.

Maybe you simply update to version 16.2.4. I've published this version a few minutes ago. If everything works according to the plan, this version includes pdf-3.4.393.min.js.

Please tell me if it works. Especially if it works - because otherwise I'm sure you're going to tell me! :)

Best regards,
Stephan

**Comment by darvisdd** [comment]
Thank you very much for the reply.

Version 16.2.4 is not yet in the NPM repository.
In any case, deleting all node_modules and installing with version 16.2.3 is not reproducing the problem for me.

Thanks again, this was really strange.
