### ISSUE TITLE
Firefox 110.0.1 - Height of pdf viewer is fixed to 100px

### ISSUE THREAD

**Issue by b-mi** [stephanrauh/ngx-extended-pdf-viewer#1702]
**Describe the bug**
In the version of Firefox 110.0.1, ngx-extended-pdf-viewer fix height to 100px after usage of Print button.

**Version info**
- 15.0.9 to 16.2.4

**Desktop (please complete the following information):**
 - Firefox 110.0.1
 
**To Reproduce**
1. Go to: https://pdfviewer.net/extended-pdf-viewer/blob
2. Click on Print button, and close the dialog. 
3. Height of ngx-extended-pdf-viewer change to height 100px.

**Screenshots**
https://i.imgur.com/bmOC1Qw.png

Thank you!

**Comment by stephanrauh** [comment]
What a strange bug! It also occurs in Firefox 109. But it doesn't happen on all pages of the demo. What's the difference?

**Comment by b-mi** [comment]
According to the documentation, ngx-extended-pdf-viewer fixes the height at 100px in case of a problem with height detection. 

There is also an error message for this in the Firefox console: 

"The height of the PDF viewer widget is zero pixels. Please check the height attribute. Is there a syntax error? Or are you using a percentage with a CSS framework that doesn't support this? The height is adjusted automatedly."

**Comment by stephanrauh** [comment]
Thanks for adding your insight! Part of the problem was that there really was an error in my code. It ignores height defintions like "100vh" or "60em". The height calculation resulted in NaN, so the default 100px triggered.

However, there's also a Firefox bug. During printing, the `clientHeight` of the div containing the PDF viewer is 0. That's obviously nonsense, because the div is still visible.

Be that as it may, adding a workaround wasn't difficult, and it's definitely faster than waiting for the next Firefox bugfix.

**Comment by stephanrauh** [comment]
Your bugfix has landed with version 16.2.5.

Enjoy!
Stephan

**Comment by b-mi** [comment]
Thank you.
