### ISSUE TITLE
Scroll API messed up when a pdf contains pages with different orientations. 

### ISSUE THREAD

**Issue by crlsmsq** [stephanrauh/ngx-extended-pdf-viewer#1707]
**Describe the bug**
I have a 2 paged pdf, 1st page is in portrait mode, and the 2nd page is in landscape mode. If I use `scrollPageIntoView(1, "{ left:60%}"`, it jumps to the far right beyond the 1st page. This is caused by having the 2nd page max width as the total 100% width for both pages. When i scroll down to the 2nd page, it seems it was on 60% of that page

**Version info**
- Version of ngx-extended-pdf-viewer: 16.0.0-alpha.0

**Desktop (please complete the following information):**
 - Browser:  Edge Chrome
 
**Smartphone (please complete the following information):**
 - Device: Windows PC

**To Reproduce**
- Use the PDF provided below
- Scroll to page 1 with left as 60% or above

**Demo PDF file**
[Portrait.pdf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/10922118/Portrait.pdf)

**Comment by stephanrauh** [comment]
Yeah, that's a use-case I didn't think of. I'm not sure I can do something about it, but I can have a look.

**Comment by stephanrauh** [comment]
it took me a while to understand that the scroll API is not messed up. Your demo file tricked me into believing there's something wrong, but when I debugged, I noticed that the percentages are relative to the page in question.

I've added a demo to the showcase that makes the behavior more obvious. Please note that the PDF viewer can't move that page to a setting like `left="100%`, because that'd mean the page scrolls out of the visible area. The scroll container doesn't allow that. If the page is twice as wide as the viewer container, setting the scroll position beyond 50% stops making a difference. 

Maybe it's more intuitive if I add a `right` parameter. However, at the moment, I'll leave it at that.
