### ISSUE TITLE
Visualization bug on mobile on chrome: menu hamburger and extra space

### ISSUE THREAD

**Issue by GabrieleGruppoInformatico** [stephanrauh/ngx-extended-pdf-viewer#1709]
**Check this first**
No happening on the two website provided (can't really try on the simple example, cause it's not responsive)

**Describe the bug**
Visualization bugs on mobile browser  Chrome.

**Version info**
16.2.5

**Desktop (please complete the following information):**
No issue found on desktop browser
 
**Smartphone (please complete the following information):**
Iphone SE (chrome console emulator)
Samsung Galaxy s8 (chrome console emulator)
Iphone 14 pro max ( IOS 16.3)
Samsung Galaxy A32 (Android 13)

**To Reproduce**
1. Button that open a modal with Pdf inside (your component that load a pdf)
2. Open it (1st everything fine)
3. Open it a second time and there will be the hamburger menu exploded and it overlaps other items inside the viewer.
On iphone, it will resize badly (white space in the bottom).
4. Bonus. you can try to tilt the smartphone, it will happen to fix the menu but no the extra space on the bottom.

**Screenshots**
![1_Iphone_verticale_ok](https://user-images.githubusercontent.com/116347225/224272084-cf1b9228-8f98-4cd2-b798-2fe37863e9ef.png)

![2_Iphone_Verticale_ok_menu](https://user-images.githubusercontent.com/116347225/224272106-7a9c7580-ebf9-4572-8bdf-09bd835c2606.png)
![3_Iphone_2Volta_ErroreVisualizzazione](https://user-images.githubusercontent.com/116347225/224272109-f9626e2b-5fb8-44a0-bc11-3e714541bb81.png)
![4_Iphone_2Volta_ErroreVisualizzazione](https://user-images.githubusercontent.com/116347225/224272111-a872b91c-591a-4667-8f90-7ecd4b2fea1d.png)
![5_Iphone_2Volta_ErroreVisualizzazione_ConsoleLog](https://user-images.githubusercontent.com/116347225/224272113-7d6033f7-ed87-46fd-9cf6-876aa1b97195.png)
![6_Iphone_2Volta_ErroreVisualizzazione_LandScape](https://user-images.githubusercontent.com/116347225/224272117-c66b25a1-db58-4e69-a667-62b7716e7c24.png)
![7_Iphone_2Volta_Ok_LandScape](https://user-images.githubusercontent.com/116347225/224272121-2d743a0f-b18c-4ba2-aae4-c5d8e63adc6f.png)
![8_Samsung_2Volta_ErroreVisualizzazione](https://user-images.githubusercontent.com/116347225/224272125-9a896480-5cae-4aa2-82c1-c52335674e2c.png)

**Additional context**
We had this problem since version ^12.x.x

**Comment by stephanrauh** [comment]
@GabrieleGruppoInformatico How can I reproduce the bug? https://pdfviewer.net/extended-pdf-viewer/modal doesn't seem to suffer from the same problem. I only noticed that the burger menu is invisible if the toolbar is less than 350 pixels wide.

**Comment by stephanrauh** [comment]
@GabrieleGruppoInformatico ping :)

**Comment by GabrieleGruppoInformatico** [comment]
We use the component inside a ionic project (based on Nx).

Here a snippet. 

`<ion-content scroll-y="false">
<ngx-extended-pdf-viewer *ngIf="FileName" [base64Src]="FileName" [language]="Language" [textLayer]="true"
[showHandToolButton]="true" height="95%" zoom="page-fit">
</ion-content>`

Idk if it could be helpful, we use Ionic/angular ModalController 
import { ModalController } from '@ionic/angular';

We tried to update to the latest v17, but no changes to it. The menu's buttons problems both in chrome simultator and real mobile device (didn't try to release a new version with the new package version for real device, cause the problem is still present in the simulator as before)

**Comment by stephanrauh** [comment]
That makes it difficult for me because I'm not too familar with Ionic. Can I talk you into sending me a very simple reproducer?

BTW, to get rid of the "0px" console message, version 17 offers `[zoom]="'auto'". In older versions `[zoom]="undefined"` probably does the trick just as well, but only if you deactivate strict type checking.

**Comment by stephanrauh** [comment]
I'm afraid I don't know how to help you. You know, I can't solve a problem that doesn't happen on my machine. However, you can try updating to version 18.0.0-alpha.5. I've changed the way the toolbar and the secondary menu work. Maybe I've solved your bug as a side-effect.

**Comment by dan-rp1** [comment]
@stephanrauh @GabrieleGruppoInformatico 

Hi there, I was also using the pdf viewer in a component loaded into ionic's modal and experienced this same problem. I was able to solve it (somewhat crudely) by delaying the rendering of the viewer component as follows:

in my component.html;
`
  <ng-template [ngIf]="ready">
    <ngx-extended-pdf-viewer [src]="src"></ngx-extended-pdf-viewer>
  </ng-template>
`

in my component.ts;
`
export class PdfModalComponent implements AfterViewInit {

.....

  ngAfterViewInit(): void {
    setTimeout(() => {
      this.ready = true;
    }, 250)
  }
`

Perhaps the proper height and width are not available to the viewer when it renders, because it is nested in the modal element which is being added to the dom simultaneously. Thus the layout issues can occur.
In that case, it's more an issue with the way its being used rather than the viewer itself.

**Comment by stephanrauh** [comment]
@dan-rp1 @GabrieleGruppoInformatico Adding a short delay usually helps with modal dialogs. Maybe the timing is slightly different when you open the modal for the second time because the JavaScript compiler can use pre-compiled code (or something like that). That'd explain why it first for the first time, but fails when re-opening the modal.
