### ISSUE TITLE
How to show the e-signature of an pdf file?

### ISSUE THREAD

**Issue by todicdar** [stephanrauh/ngx-extended-pdf-viewer#171]
Hello, 
Are there any way to ngx-extended-pdf-viewer show e-signature from pdf file? 
Thanks.

**Comment by stephanrauh** [comment]
I've just published version 1.8.0-rc.1 with preliminary support. **Caveat:** The next version will hide the signature again. You'll have to activate it by a switch.

The reason is that pdf.js can't verify the signature. It displays it, no matter if can be trusted or not. So people should know what they're doing. I want them to activate the feature as a deliberate decision.

**Comment by stephanrauh** [comment]
Also see https://github.com/mozilla/pdf.js/issues/1076.

**Comment by todicdar** [comment]
It is fantastic. It works. Thank you so much for this feature.

**Comment by stephanrauh** [comment]
I've implemented `showUnverifiedSignatures`. 

@todicdar You'll need to update your HTML template after updating to 1.8.0-rc.3. By default, signatures are switched off. Just add `showUnverifiedSignatures="true"`.

**Comment by todicdar** [comment]
Dear,

I notice that the 'showUnverifiedSignatures' attribute does not exist in
ngx-extended-pdf-viewer 5.1.0.
Do you have plans to include it in this version in the future?
Thanks.

Best regards,

Darko Todic

**Comment by stephanrauh** [comment]
I didn't remove the attribute. It's still there. I suppose something else has changed. The base library, pdf.js, deliberately deactivated the feature. So they didn't check if it's still there when they implemented form support. Just deactivate forms, and your signature shows again. 

```typescript
export class AppComponent {
  public document1 = '/assets/pdf_file.pdf';

  constructor() {
    pdfDefaultOptions.renderInteractiveForms = false;
  }
}
```

Also see #514.
