### ISSUE TITLE
PinchToZoom touchevents should be listened to on the pdf viewer element

### ISSUE THREAD

**Issue by digaus** [stephanrauh/ngx-extended-pdf-viewer#1733]
**Is your feature request related to a problem? Please describe.**

PinchToZoom feature listens to document touch events. This is a problem when we have the viewer inside an element which also listens to touchevents. That way I can not use `stopPropagation()` on the wrapper element for the touch events because the pdf viewer also will not receive the touch events.

**Describe the solution you'd like**

Use the pdf viewer element as basis for touch events

**Describe alternatives you've considered**
-

**Additional context**

Context here is that I am trying to use a card style modal (Ionic Framework) which naturally has some animations while dragging. I can prevent these animations by using stopPropagation() on the pdf viewer element. However this also results in the PinchToZoom function not working

**Comment by stephanrauh** [comment]
I've published your improvement with version 17.0.0-alpha.6. Please run a test and tell me about it. At the moment, I'm short of free time, so I can't test the feature as thoroughly as I'd like to do. Plus, I'd like to know whether my change fixes your application.

Enjoy!
Stephan

**Comment by stephanrauh** [comment]
BTW, you mention the `PinchToZoom` feature. The `PinchToZoom` class was my first attempt to provide a decent pinch-to-zoom feature. In the meantime, I've removed it because the base library has implemented a superior solution. In other words, the feature is still there (and works better than ever), but the `PinchToZoom` class is gone for good.
