### ISSUE TITLE
Pdf items of undefined error some Pdf file

### ISSUE THREAD

**Issue by troimaclure** [stephanrauh/ngx-extended-pdf-viewer#1737]
Hello, 

- Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.html? 
No
- Does the bug also happen on https://pdfviewer.net/simple? 
Yep

**Describe the bug**
1. load given pdf 
2. Try set object on select box
3. See error

**Version info**
- Version of ngx-extended-pdf-viewer : Latest 

Possible résolution : Maybe upgrade Pdf.js

[Bulletin light.pdf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/11161614/Bulletin.light.pdf)

**Comment by stephanrauh** [comment]
I've already managed to solve your bug (probably setting a record: it merely took 5 minutes!). It was a stupid mistake by me, and I wonder why nobody else noticed the bug previously, including me.

If everything works according to the plan (it never does...), I'm going to publish the bugfix this week-end as version 17.0.0-alpha.0. It's an alpha version because I'm updating to pdf.js 3.5 and because I feel I have to remove a few exotic feature in order to keep up with the flood of new tickets. Calling it "alpha" doesn't mean I consider it to be a low-quality version.

**Comment by stephanrauh** [comment]
I've decided to re-write the entire form support from scratch. As far as I can see, it works now, but it'll take a couple of days to land. I'm busy next week.

**Comment by stephanrauh** [comment]
With version 17.0.0-alpha.3, your bug is gone. I'm closing the issue now.

**Comment by troimaclure** [comment]
Thank you !
