### ISSUE TITLE
polyfills.js:10014 Access to XMLHttpRequest at 'file:///D:/Report.pdf' from origin 'http://localhost:4200' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.

### ISSUE THREAD

**Issue by swatijal70** [stephanrauh/ngx-extended-pdf-viewer#176]
How to solve this issue in Angular 6:

polyfills.js:10014 Access to XMLHttpRequest at 'file:///D:/Report.pdf' from origin 'http://localhost:4200' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.

**Comment by stephanrauh** [comment]
There's no good way to solve this issue. It's driving me nuts, too. But it's part of the fight against hackers, so we have to put up with it.

Here's what you can do:

- Use Internet Explorer. It doesn't protect you against cross site scripting attacks. (Bad choice, I know).
- Start Chrome without CORS protection. That's a bad choice too, so this option may have been removed since I last checked.
- Open the file in a new window, or have the user open it in a new window. I'm not sure this works, but as long as it's clear that the request is triggered by the user, the browser won't complain.
- Use a file upload dialog to open the file. This way, the file is either on your server or on the client, and the browser won't complain, either.
- Wrap your application in Electron to create an almost-native application. In this case, the browser also assumes you know what you're doing.

**Comment by stephanrauh** [comment]
More information about CORS attacks: http://aetherlab.net/2013/11/cors-attack-scenarios/

Hope that helps!
Stephan
