### ISSUE TITLE
Ngx Extended Pdf Viewer Print is Not Working Properly If my pdf has 10 pages then itry to print by clicking print icon the print summery is opened bu the problem is it took only 1 (first page of the pdf file) page to the print summery as well as in print 

### ISSUE THREAD

**Issue by Musthafafazil** [stephanrauh/ngx-extended-pdf-viewer#1771]

**Comment by stephanrauh** [comment]
Hm. I don't think your issue affects every PDF consisting of ten pages. So I need a reproducer. Can you send me a small but complete project demonstrating the problem? The project should include the offending PDF file, but it shouldn't force me to install any third-party software. In particular, I don't want to install or configure a database.

Thanks in advance,
Stephan

**Comment by stephanrauh** [comment]
This kind of problems is almost always caused by your CSS rules. Please create a new project from scratch, as described at https://pdfviewer.net/extended-pdf-viewer/getting-started, and test it with your PDF document. This will take you merely five minutes. If the new project still has problems, please send it to me, along with the PDF document causing trouble.

Best regards,
Stephan
