### ISSUE TITLE
Drawing when zoomed in

### ISSUE THREAD

**Issue by BossuytWannes** [stephanrauh/ngx-extended-pdf-viewer#1802]
When zooming in on a pdf and scroll down to the bottom right, when you start drawing the view jumps up to almost the top of the pdf, making me draw a line from the bottom to the center of the PDF.

Steps to reproduce:
1. Open a pdf
2. Zoom in (let's say a zoom of 150%)
3. Go tot he right bottom corner
4. Start drawing

I was able to reproduce this on google chrome on the example via following link: [https://pdfviewer.net/extended-pdf-viewer/zoom](https://pdfviewer.net/extended-pdf-viewer/zoom)
You can reproduce on the example by zooming in, moving the view to the bottom of the page (make the next page visible) and start drawing.

**Comment by stephanrauh** [comment]
Please run the test again on the showcase. I haven't publish a new version yet, but I've already deployed it on https://pdfviewer.net/extended-pdf-viewer/zoom. I believe I've found the bug.

BTW, this bug has been haunting me for several days now... but I needed your confirmation that it's not just me because I was looking for the bug at the wrong places.

**Comment by BossuytWannes** [comment]
Seems to have solved it indeed.
Let me know in what version it will be fixed for me 👍

**Comment by stephanrauh** [comment]
The bugfix has landed with version 17.4.2.

Enjoy!
Stephan

**Comment by BossuytWannes** [comment]
Thanks for the fast response, works like a charm!
