### ISSUE TITLE
Render a rectangle on top of the PDF

### ISSUE THREAD

**Issue by scry-UrjitDesai** [stephanrauh/ngx-extended-pdf-viewer#1816]
Hey, I have a requirement wherein I have a list of items which contains metadata that represents the page number and the coordinates of a rectangle on the PDF. I want to achieve the following functionality:

Whenever user clicks on an item, the pdf should scroll to that page and the bounding box should be displayed. If the user clicks on another item or an item that does not have the coordinates, then the previous bounding box should disappear.

I am being able to add the annotations but when I click on a new item the previous annotations still remain until I resize the window (which causes the pdf page to re-render thus removing previous annotations). Any help is highly appreciated. Thank you!

Here is my HTML code: 
```html
<ngx-extended-pdf-viewer
    #pdfViewer
    [src]="pdfSrc"
    (annotationLayerRendered)="onAnnotationLayerRendered($event)"
    [(page)]="page"
    pageViewMode="multiple"
    (pageChange)="onPageChange($event)"
    (pdfLoaded)="onPdfLoaded($event)"
    (pageRendered)="onPageRendered($event)"
  ></ngx-extended-pdf-viewer>
```

Here is my typescript code:

```ts
onPdfLoaded(event: PdfLoadedEvent) {
    console.log('on pdf loaded= ', event);
    this.totalPages = event.pagesCount;
  }

onPageRendered(event) {
    console.log('on page rendered= ', event);
    this.canvases[event.pageNumber] = event.source.canvas;
    if (Object.keys(this.originalCanvases).length !== this.totalPages) {
      console.log('here');

      this.originalCanvases[event.pageNumber] = event.source.canvas;
    }
    console.log('original canvases= ', this.originalCanvases);
    console.log('canvases= ', this.canvases);

    this.annotationService.getCoordinates().subscribe((data) => {
      if (data) {
        const page = data[0]['page_n'];
        this.page = page;
     
        const currentCanvas = this.canvases[page];
        this.context = this.canvases[page].getContext('2d');
        this.x_start = data[0]['scaled_x_start'] * currentCanvas.width;
        this.y_start = data[0]['scaled_y_start'] * currentCanvas.height;
        this.x_end = data[0]['scaled_x_end'] * currentCanvas.width;
        this.y_end = data[0]['scaled_y_end'] * currentCanvas.height;
        this.context.strokeStyle = 'red';
        this.context.lineWidth = 1;
        this.context.strokeRect(
          this.x_start,
          this.y_start,
          this.x_end - this.x_start,
          this.y_end - this.y_start
        );
      } else {
        this.pdfViewerService.removeEditorAnnotations(); // this does not remove the annotations
      }
    });
  }
```

**Comment by stephanrauh** [comment]
You're close! The last missing piece falls into place when you look at what the new editors do. They add a new canvas on top of the canvas layer. So instead of drawing into the canvas the PDF viewer renders, put another canvas above the PDF canvas, give it a transparent background and paint your rectangle.

"Putting another canvas above" means adding another `<div>` to the page. By default, every page consists of multiple layers like so:
<img width="279" alt="grafik" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/3045767/556a9095-b8a7-41a6-ad22-198d634152d5">

So all you need to do in your `onPageRendered()` method is finding the page (probably `event.source` - I didn't check that yet), add a `<div>`, put a canvas into the div, and make both 100% wide and high.

This approach makes removing your rectangles simple: you've inserted the additional `<div>` and `<canvas>` yourself, so you can easily remove it. The draw and text editor add a nice twist: they add a `<canvas>` for every drawing, so you can manipulate them individually.

Oh, and `removeEditorAnnotations()` doesn't work in your case because you didn't use the editor framework.

Hope that helps!
Stephan
