### ISSUE TITLE
How to open a file from network drive/ physical drive (other than assets folder)?

### ISSUE THREAD

**Issue by manojmaity** [stephanrauh/ngx-extended-pdf-viewer#182]
**Check this first**
- Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.htm?
- Does the bug also happen on https://pdfviewer.net/simple?

**Describe the bug**
We have an angular app, which have to display pdf file from netwrok drive.
It there any way that it can be achieved?
Any help shall be appreciated.

Thanks in advance.

**Comment by stephanrauh** [comment]
Please fill in some details:

-  What's going wrong precisely? 
- Is there a message in the brower's console window? 
- Does it say something about CORS?
- Can you open the same file using the "open file" button of the PDF viewer?

As far as I remember, there's a protection against hacker attacks preventing you to open local files. However, when I tried to reproduce your issue, I saw that I can open the file using the "open file" button. So I suppose I can fix this - if that's your problem. Your problem description is slightly vague. :)

Best regards,
Stephan

**Comment by stephanrauh** [comment]
Bad news after reading up the file API again: there's no way to open a PDF file by filename. The only exception is having the user select and upload the file. For instance, you can use a `<input type="file">` tag. That's pretty much the same approach of the "open file" button.

The rationale is to protect you from hackers. Just imagine a website could read your local files and send them to a malicious server. Those things have happened in the past, and that's why browser manufacturers are very paranoid about file accesses.
