### ISSUE TITLE
Handle style using standalone files

### ISSUE THREAD

**Issue by alexandru-cazacu** [stephanrauh/ngx-extended-pdf-viewer#1828]
I have to make this library run on Chrome 51 in an Angular project. I'm using postcss-loader and postcss-preset-env to automatically downgrade modern css rules, like inset, which is supported from Chrome 87 onwards. To achieve this I extended the webpack configuration for both css and scss, but it seems to not work on this library because the styles are compiled into TypeScript (using compile-sass.ts, from what I've seen).

Would it be possible to use standalone files (.scss or .css) for the styles?

I tried to modify all the Angular style loaders, but it seems that the embedded styles from this library can't be processed by postcss.

**Comment by stephanrauh** [comment]
Use the attribute `[theme]="custom"`. At the moment I'm short of time, so I can't run a test myself, but if it works the way I intend it to work, it prevents loadings the inlined CSS.

If course, this rewards you with a broken PDF viewer because of the missing CSS rules. In your case, that's pretty much what you need: you've got a blank slate. You've already seen `compile-sass.ts`, so you probably know the rest: you need to compile the two files `'./projects/ngx-extended-pdf-viewer/src/lib/theme/pdf-light-theme/colors.scss'` and `'./projects/ngx-extended-pdf-viewer/src/lib/theme/pdf-light-theme/print.scss' to CSS. For example, you can add them to your `global.(s)css` (but I'm not sure if that generates the CSS dialect you need).

BTW: I wasn't aware that CSS has changed so much between Chrome 51 and Chrome 87. I've been focusing on delivering the correct JavaScript dialect. I'll add CSS compatibility to my to-do list.

**Comment by stephanrauh** [comment]
I've closed the ticket because I believe my hints are sufficient. If you still run into problems, don't hesitate to reach out to me!

Best regards,
Stephan

**Comment by alexandru-cazacu** [comment]
Thanks for the quick reply Stephan. I'll try when I have some time.
