### ISSUE TITLE
Download button on a specific location

### ISSUE THREAD

**Issue by Tweniee** [stephanrauh/ngx-extended-pdf-viewer#1837]
I want when i click on download button then it gets saved to a specified location instead of download .
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/93429474/4f009029-01ab-43c1-8338-501a9b7aa2b6)
i am using this version with angular 15,

**Comment by stephanrauh** [comment]
Please elaborate. "Specified location" = "a certain folder on the hard disk"? If you need that, I don't have a clue. I'm pretty much convinced it's impossible. The browser allows you to specify the name of the file, but that's it. In particular, you can't create a file on the user's device. That's one of the protections against hackers.

If you want to send the file to a backend, that's no problem. You can export the file, store it in a blob, and send the blob to an REST API. Live demo and documentation are here: https://pdfviewer.net/extended-pdf-viewer/export-file

**Comment by Tweniee** [comment]
Actually you are correct i get that, but i am not able to understand this documentation you provided,
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/93429474/dcccfcda-8e74-485d-af53-4c37c43c042e)
i want the blob file but not able to understand how to trigger this event "ngxExtendedPdfViewerService.getCurrentDocumentAsBlob()" where to put the button and how to display the button "Export te Blob file".

**Comment by stephanrauh** [comment]
First of all, don't put `getCurrentDocumentAsBlob()` into the constructor. More likely than not, this will result in an error because the PDF document hasn't been loaded yet.

Second, think about adopting the `async-await` paradigm. It's unpopular in the Angular world because of an accident. The Angular team decided to use `Observable` half a year before `async-await` became an official JavaScript keyword. In hindsight, favoring `Observable` over `Promise` looks like a weird decision. Read the full story here: https://www.beyondjava.net/angular-async-await

Back to your question. I assume you want to put a button somewhere on the page that triggers the download. The button is above or below the PDF file, so you can just use a regular Angular button. Add an `(click)` listener to the button, and that's where your put the `getCurrentDocumentAsBlob()` call:

https://github.com/stephanrauh/extended-pdf-viewer-showcase/blob/414c85ee4d5ac2da410ab4da293a29749128cdd7/src/app/extended-pdf-viewer/export-file/export-file.component.html#L9

https://github.com/stephanrauh/extended-pdf-viewer-showcase/blob/414c85ee4d5ac2da410ab4da293a29749128cdd7/src/app/extended-pdf-viewer/export-file/export-file.component.ts#L34-L38

**Comment by stephanrauh** [comment]
If you want to add the button to one of the toolbars of ngx-extended-pdf-viewer itself, that's possible, too. Check out https://pdfviewer.net/extended-pdf-viewer/custom-toolbar to learn how to do it.

BTW, you've mentioned you don't get my explanations. That's valuable feedback. How can I improve the showcase?

**Comment by Tweniee** [comment]
Thanks @stephanrauh it helped in a good way.

**Comment by Tweniee** [comment]
> If you want to add the button to one of the toolbars of ngx-extended-pdf-viewer itself, that's possible, too. Check out https://pdfviewer.net/extended-pdf-viewer/custom-toolbar to learn how to do it.
> 
> BTW, you've mentioned you don't get my explanations. That's valuable feedback. How can I improve the showcase?

Plus in response to your documentation page, lack of documentations text and events to properties most of the thing we need to understand by looking at the functioning provided. (Minor thing but the focus is always on the pdf thats a bit annoying when using ctrl+f)

A helping hand: As i have created multiple documentation for my projects and just started contributing to open source projects, i would like to help and make the documentation much more understandable.

I have seen that you are looking for helpers as ngx-extended-pdf-viewer is growing, so if you want we can create better things.

**Comment by stephanrauh** [comment]
Sounds great. Go ahead! I guess the easiest way to contribute to the documentation is cloning the showcase (https://github.com/stephanrauh/extended-pdf-viewer-showcase) and sending me a pull request.

I hope you don't mind if I run my grammar checker and re-phrase sentences to make them clearer. I want the texts to be a fun read.

Another option is publishing articles on my blog or on Medium. I can help you with that, too.

**Comment by Tweniee** [comment]
Sure i will try to make it better
