### ISSUE TITLE
Hey Stephanrauh! Can you show me how I can define type for StampEditor it is similar to how you define type for InkEditorAnnotation or FreeTextEditorAnnotation. Because currently I see on the latest version of extended-pdf-viewer there is no type support for StampEditor yet! Because I want to add a stampEditor to my problem

### ISSUE THREAD

**Issue by Congchuabongbong** [stephanrauh/ngx-extended-pdf-viewer#1844]
**I need your help!**
This project is becoming more popular by the day. I'm drowning in a flood of new issues and bug tickets. So I probably need your help to solve the issue. While we're at it: would you like to hunt down the bug yourself and to send me a pull request?

**Check this first**
The project is a wrapper around Mozilla's PDF viewer, so maybe your bug is caused by the base library. Please check this first by answering these three questions:
- Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.html? (If so, please open the issue at Mozilla's bugtracker).
- Does the bug also happen on https://pdfviewer.net/simple?
- Can you write a reproducer based on a freshly created project? To create such a project, please use `ng new myissue` and `ng add ngx-extended-pdf-viewer`.

**Describe the bug**
A clear and concise description of what the bug is. For example:

**Version info**
- Version of ngx-extended-pdf-viewer

**Demo PDF file**
Many errors happen with specific PDF files only. So please add a PDF file (after checking the copyright of the PDF file first!)

**Comment by stephanrauh** [comment]
At the moment, I can't. Technically, I could jot down a type definition. To be honest, it's already in the project, albeit in a slightly inofficial part of it: https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/6da3afc7700de6d2b42e0700b7073a7f95320fc5/projects/ngx-extended-pdf-viewer/types/src/display/editor/stamp.d.ts#L19-L25

However, publishing the type definition doesn't make much since because a crucial part is missing. My `addEditorAnnotation()` method does not allow you to add the image. Without this option, I don't see any point in defining a typing that doesn't help anybody.

During the next few months - probably until end of Oktober - I'm short of time. So I invite you to send me a pull request. I believe all you need to know to implement the feature is in the vicinity of this line:

https://github.com/stephanrauh/pdf.js/blob/325c39b469115b17d9ddb8cb1f7c452e77f65328/src/display/editor/stamp.js#L115
