### ISSUE TITLE
How to print multiple pdfs?

### ISSUE THREAD

**Issue by avinashgazula** [stephanrauh/ngx-extended-pdf-viewer#1859]
I'm looking to print multiple pdfs, and looks like there's currently only support to have one pdf in a component?

Also sidenote, how did you manage to currently open the print dialog using window.print() without it not opening in a new tab?  [Here's a small stackblitz](https://stackblitz.com/edit/stackblitz-starters-irpsfo?file=test%2Fsrc%2Fapp%2Fapp.component.ts) that shows it always opens in a new tab

**Comment by stephanrauh** [comment]
Yes, ngx-extended-pdf-viewer only supports a single PDF component at a time. That's a shortcoming I've inherited from pdf.js. The base library pollutes the global namespace. The team is reducing the pollution, and one day or another they'll manage to remove it, but they're not there yet. 

Printing is a really clever bit of software. It prints the current page. That's obviously a lie, because the current page is an Angular application, only it's not: pdf.js and, by extension, ngx-extended-pdf-viewer hide everything except a list of high-quality pages rendered as `<canvas>`. This, in turn, requires a lot of magic CSS, and it's a frequent cause of error reports.

You can see this in the DOM inspector if you set a breakpoint immedately before the `window.print()` call. I always forget the precise line, but I guess it's this one: https://github.com/stephanrauh/pdf.js/blob/8954ff27f08da7d3902c37ac263384636b8c8b8a/web/pdf_print_service.js#L285
