### ISSUE TITLE
[Export and importing drawings and free text] draw from canvas 

### ISSUE THREAD

**Issue by heyyoUna** [stephanrauh/ngx-extended-pdf-viewer#1860]
I have successfully obtained a formData array using the getFormData() function.

I am interested in placing a canvas drawing within the confines of the first formData rect area. To accomplish this, I am curious about the process of converting the canvas path array into an array of BezierPath objects. This conversion is necessary to utilize the addEditorAnnotation function effectively.

Additionally, I have observed that when the length of the bezier array in the 'paths' object is equal to 8, the annotation achieves proportional scaling, which aligns perfectly with my requirements. However, I've encountered difficulties when this array exceeds that length. I would greatly appreciate any guidance on how to address this issue.

**Comment by stephanrauh** [comment]
I'm afraid there's a misunderstanding here. Are you familiar with Bézier curves? These are mathematical functions to draw elegant curves connecting certain points. A canvas, in contrast, can be anything. It doesn't have to contain lines, there can be disconnected dots and two-dimensional objects. So, generally speaking, there' no easy way to convert an arbitrary canvas to an array of Bézier curves.

On the other hand, you've already experimented with the technology, so maybe I've misunderstood your question and interpreted your question too broadly. :)

That said, I know very little about the topic. I've even forgotten what I learned at university about splines 30 years ago. That's a pity, because I'd like to tune the algorithm to make the curves smoother, but that'd require me to dig more hours into the topic than I can afford right now.

BTW, maybe the new "stamp tool" is what you're looking for? It allows you to add images to the PDF file.

Here's some background reading about Bézier curves: https://en.wikipedia.org/wiki/B%C3%A9zier_curve

**Comment by heyyoUna** [comment]
I found that I misunderstood the Bézier curves.
I have experimented with the stamp tool, and it aligns perfectly with my requirements.
thank you so much for the assistance :)
