### ISSUE TITLE
Nameddest Doesn't work for pdfs

### ISSUE THREAD

**Issue by jackie-chatman** [stephanrauh/ngx-extended-pdf-viewer#1861]
When I send a known bookmark name/ named destination to the nameddest attribute it doesn't load the pdf to the specific page I've requested.  I've confirmed the value I am sending is correct by accessing the pdf locally via chrome and appending #nameddest=xyz or #xyz to the end and it works properly.  Could you please take a look at why this isnt working.  I am using your most recent version. Thanks.

**Comment by stephanrauh** [comment]
The feature still works at https://pdfviewer.net/extended-pdf-viewer/navigation. What's the difference to your implementation? Here's the source code:

https://github.com/stephanrauh/extended-pdf-viewer-showcase/tree/main/src/app/extended-pdf-viewer/navigation

**Comment by jackie-chatman** [comment]
This is my implementation:
 <ngx-extended-pdf-viewer [src]="src" height="65vh" [zoom]="actual" [useBrowserLocale]="true" [namedest]="nameddest"
                            [showRotateButton]="false" [showOpenFileButton]="false" [showPresentationModeButton]="true"
                            [showBookmarkButton]="false" [textLayer]="true"></ngx-extended-pdf-viewer>
                            
I see in your source code that you only trigger the navigation on a click event.  Could that be the reason I am not able to get my intended outcome?  I am looking to initially load the pdf on a certain section.

**Comment by jackie-chatman** [comment]
I tried setting up a new project following your design and still get the error: PDFLinkService.goToDestination: "null" is not a valid destination array, for dest="Certificates". 
Even though this destination does indeed exist.  When I open the file locally via google and add '#Certificate' to the end, it jumps to the expected destination.  Any ideas on why this would happen?

**Comment by stephanrauh** [comment]
Can you send me the complete stack trace? Before doing so, please set `minifiedJSLibraries="false"`. Otherwise, the stack trace is mostly useless.

You might be right: I never tested setting the `namedDest` attribute from start, so it might be broken. You can work around this shortcoming by setting it to `false` initially, and setting it to `true` after a short timeout. If that works, please tell me - it helps me to find and solve the bug.

At the moment, I'm busy. I hope I'll manage to find some spare time next week. If you want to speed up things: I always accept pull requests!

Best regards,
Stephan
