### ISSUE TITLE
Pages content and images are not shown or cut on mobile Andriod

### ISSUE THREAD

**Issue by Wafaa-kameel** [stephanrauh/ngx-extended-pdf-viewer#1865]
Images seem to be cut or not loaded.

Trying to troubleshoot that:
1-Open https://pdfviewer.net/extended-pdf-viewer/mobile on mobile Andriod 13/chrome browser 116.0.5845.163
2- Will get cut or even not loaded images 
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/144238663/feb5dfbf-efc9-48e8-bae3-0badb21a886f)
and sometimes like this: 
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/144238663/eabb42ae-e437-4749-9508-f2be4073b7c6)

Or I get partially empty pages with grey background 
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/144238663/0eb32057-5b8f-4293-a48b-8e1fc40a9f03)

**Comment by stephanrauh** [comment]
I wonder if that's a Chrome bug. And I'm pretty sure the bug also happens in the showcase of pdf.js itself. Can you check this, please? I don't have an Android device, so I need your help. Navigate to https://mozilla.github.io/pdf.js/web/viewer.html and upload your PDF files there. Are they rendered correctly?

**Comment by Wafaa-kameel** [comment]
No, it does not render correctly.

**Comment by stephanrauh** [comment]
All right. My educated guess is it's a Chrome bug. What I do know for sure is that I can't solve the bug. Please open a ticket at https://github.com/mozilla/pdf.js. Fill their form meticulously - they are always quick to reject tickets for formal reasons. In particular, don't mention my project because it's not a use-case they support. Good luck!
