### ISSUE TITLE
Message: Setting up fake worker failed: "Cannot load script at:

### ISSUE THREAD

**Issue by BhavirisettyNagaRavi** [stephanrauh/ngx-extended-pdf-viewer#1875]
viewer-3.5.550.min.js:44  An error occurred while loading the PDF.

PDF.js v3.5.550 (build: df5366593)
Message: Setting up fake worker failed: "Cannot load script at:

if i refresh page its working fine, but i navigate from one page to another this error popping up. i am using latest ngx2 extended pdf viewer

**Comment by stephanrauh** [comment]
That's not much context to work with. Please send me a screenshot of both your developer tools network tab and the console. Before you do, please add the attribute `[minifiedJSLibraries]="false"`. Otherwise, the stack traces are next to useless.

However, as the first step, I ask you to read https://pdfviewer.net/extended-pdf-viewer/getting-started and https://pdfviewer.net/extended-pdf-viewer/troubleshooting first. In particular, I recommend creating a fresh Angular project and adding the PDF viewer to it. `ng add ngx-extended-pdf-viewer` is a fail-safe recipe to get a working PDF viewer, and most people manage to spot their mistake quickly by comparing the working installation to their broken one.

Best regards,
Stephan

**Comment by BhavirisettyNagaRavi** [comment]
thanks
