### ISSUE TITLE
Is there a way to edit the font of text that can be added to a document using the add text option?

### ISSUE THREAD

**Issue by pnastya** [stephanrauh/ngx-extended-pdf-viewer#1883]
Hello! I'm trying to figure out how to use your library to change the font of added text in a document. 

My problem is that when outputting a document for printing or downloading, I need the text font to be different from the standard one.

Is it maybe possible now or is it in the plans to add the ability to dynamically change the font for adding text to text layer? 

I also noticed that some “Helv” font is not recognized and is replaced by some “standard” one when downloading a file: 

`Warning: Font "Helv" is not available -- attempting to fallback to a default font.`

Warning also apperars on demo pages.

Is it possible to customize these fonts?

Version: 18.0.1

**Comment by stephanrauh** [comment]
I wonder if there a misunderstanding. My first reaction was to say "hey, it's PDF - and this means the author defines the font, and you can never modifiy it". 

On the other hand, you're referring to the text layer, and you've mentioned an error message. So maybe you've run into a very specific error scenario.

As for printing: that doesn't involve the text layer. The text layer is just a little piece of black magic allowing you to mark text on the screen.

Thing is, I don't believe your error message is caused by the text layer. I consider it more likely to be caused by the text renderer. If that's true, the error message means that the author of the PDF file used a non-standard font and forgot to embed it with the PDF file. That's annoying, because the only solution is to fix the PDF file itself. I doubt you can talk any PDF viewer team into replacing font dynamically. The idea of PDF is that it's a file format you can rely upon. Manipulating the content of the PDF - even if it's only the font - contradicts this idea.

Be that as it may, I'm pretty sure you can reproduce the bug in the showcase of the base library: https://mozilla.github.io/pdf.js/web/viewer.html. If so, please open a ticket on their bug tracker.

Best regards,
Stephan
