### ISSUE TITLE
Loader on pdf pages

### ISSUE THREAD

**Issue by mkumar92** [stephanrauh/ngx-extended-pdf-viewer#1902]
Is there any option to show the loader on the pages when pdf pages are loading/buffering ( look like coming in pagination ).

**Version info**
- 18.0.2

**Comment by stephanrauh** [comment]
I wonder what you're looking for:
- There used to be a loading animation that showed when the PDF file loads. It always caused problems when updating to the latest version of pdf.js, so I guess now it's gone for good. You can implement you own loading spinner using the events Sébastien mentioned above.
- There *should* be a spinner on each page. I can't tell whether it's there or not because the pages render to quickly. However, looking at the DOM, I suspect the spinner is gone, too. At the moment, I can't tell whether that's a bug or not. Until I find out, you can solve the problem with a little CSS. Activate the spinner on HTML elements bearing the CSS class `.page` but lacking the attribute `[data-loaded=true]`.

You might also want to have a look at the rendering events, also documented in the page Seébastien showed you: https://pdfviewer.net/extended-pdf-viewer/pages-loaded

Remains the question how I can reproduce your issue. What's your use-case? Why don't your PDF pages render within fractions of a second?

**Comment by mkumar92** [comment]
@bonati-s @stephanrauh thanks for your quik response, its working fine for me now.
