### ISSUE TITLE
page fit

### ISSUE THREAD

**Issue by remimata** [stephanrauh/ngx-extended-pdf-viewer#1911]
Hello. I wanted to fit my pdf with my page. it worked for the first page but not for the following ones.
All pages have different width and height. 
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/90611299/b824934c-80f3-4308-be11-19f252206c2c)

But when I am on the following pages and I change the zoom and I come back to fit to page the page is zoomed well

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/90611299/38b6838d-81d9-4d07-a1fc-f9c309ae31d4)

[test.pdf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/13031113/test.pdf)

**Comment by stephanrauh** [comment]
Now that's a very good question. Does "page fit" mean the zoom level changes each time a new page become visible?

I don't think so. I understand why you'd expect that, but I'm afraid it'd result in a very unsatisfying UI. In single-page mode, you can do that without problems. But the default is a variant of infinite scroll, so the zoom level jumps when scrolling. I suppose that's both unexpected and confusing. So I don't want to implement this as the default behavior.

However, you can implement it yourself. Catch the `(pageChanged)` event. The method should set the zoom level to - say - 100%, and set it to `page-fit` shortly after. I'm not sure if you can set it to `page-fit` immediately after setting it to 100%. If that doesn't work, use a timeout:
```ts
public onPageChange() {
   this.zoom = '100%';
   setTimeout(() => this.zoom = 'page-fit');
}
```

**Comment by stephanrauh** [comment]
I'm closing the ticket now, but I'd like to hear from you. Does my hint solve your problem? Did I miss something? I'm always ready to open tickets again if there's new insight!

Best regards,
Stephan

**Comment by remimata** [comment]
yes it worked in page by page mode however the flash image when loading since it changes size.
And indeed I wanted to show the page by page mode which bugs when you put fit to page it only fits the first page.

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/90611299/8f5e0667-8bfe-476d-bf83-2eef25f0fcb5)

**Comment by stephanrauh** [comment]
I wonder If there's a loss in translation. I speak a little French - well, I assume it's painful to listen, but this is the internet, and it's all text, so here's my offer: Si c'est plus facile pour vous, ecrire-mois en Française. En tant qu'effet secondaire, c'est une excellente opportunité de pratiquer une langue que j'adore, même si c'est très difficile pour moi.

That said, let me summarize what I've understood:

- You've tried my `onPageChange()` approach, but it has annoying side-effects. It works, but when you go to another page, there's a nasty flash because of rendering and re-rendering with different zoom factors.
- I'm afraid I didn't understand your second sentence. You've activated the single-page mode, but even so, the `page-fit` setting only affects the first page? In other words, the scaling is wrong after navigating to another page? Is that still true after using my `onPageChange()` idea?

**Comment by remimata** [comment]
Ahah sorry I just forgot to punctuate my sentence correctly. 
So you're right on both points. Everything works as I wanted with your onPageChange() idea. 
But I thought it was a pity that in 1 by 1 page mode and in page to fit zoom mode, the zoom didn't adapt automatically.

**Comment by stephanrauh** [comment]
@timvandermeij What's your opinion? How should the PDF viewer behave when the zoom is set to "page-fit"? Currently, it scales the current page, and never changes the zoom factor again. Usually nobody notices, but in this case, the PDF document consists of pages with different sizes. 

Especially in single-page (aka page scroll) mode this becomes a little awkward: after paging to the next page, the header still reads "page-fit", but the page doesn't fit.

**Comment by timvandermeij** [comment]
I'm not really sure, and I think it's the same problem as described in https://github.com/mozilla/pdf.js/issues/3984#issuecomment-29536670. So far this has been quite a rare case, which is probably why it hasn't been addressed for almost 10 years now.
