### ISSUE TITLE
 Direct access to underlying viewer properties and methods.

### ISSUE THREAD

**Issue by ishanuda** [stephanrauh/ngx-extended-pdf-viewer#192]
Hi,
I am new to the usage of the library,

There is a feature in ng2-pdfjs-viewer that having direct access to underlying viewer
PDFJS and ViewerJS properties and methods.

01. Is this library has that feature?
02. Also, like to know how to enable internal links (hyperlinks) of the PDF files using this library?

regards.

**Comment by stephanrauh** [comment]
1. Both `PDFViewerApplicationOptions` and `PDFViewerApplication ` are directly available in the window scope. I think it might be a bit dangerous to use them because you never know what happens when the next update of pdf.js lands. But as long as you're aware of the risk, feel free to use them.

2. Can you send me an example PDF file, please?

**Comment by ishanuda** [comment]
Hi,
Thank you very much for the reply,

01. If you can provide an interface to the Both 
`PDFViewerApplicationOptions `and `PDFViewerApplication` then, when the PDF.js update the application the library can safely update the interface and users will be safe to use the feature built into the library.

NOTE: only a suggestion :-)

02. Here I have attached the example pdf with internal links to different types of local documents and an external link to youtube.cm.

[sample-pdfs.zip](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/4049590/sample-pdfs.zip)

Thank you

**Comment by stephanrauh** [comment]
Thanks for sending the PDF file! The link to Youtube works on my machine. So does the internal link. I haven't examined the other two links yet.

As for the interface: yes, it's a good idea, and it's already on my agenda. But it doesn't solve the problem. The pdf.js team is independent from the ngx-extended-pdf-viewer project, so they may change their API at any point in time, no matter what my interface says. So providing an interface is definitely useful, but it's no protection against unexpected API changes.

**Comment by ishanuda** [comment]
Hi, Thank you for the reply,
I will check and confirm with the mentioned links working status with my configurations further.
regards

**Comment by ishanuda** [comment]
Hi,
As you mentioned, link 1 and 4 work for me as well, but not the link 2 and 3 as in the image attached,
Is there a way to enable these external links in the viewer?

![image](https://user-images.githubusercontent.com/8893919/73066042-0b793f00-3ecb-11ea-8e90-f38dd985fcd4.jpg)

Thank you very much.

**Comment by stephanrauh** [comment]
Sorry for the long delay. Well, I just saw your links don't work in the original pdf.js project, either (https://mozilla.github.io/pdf.js/web/viewer.html). So you should address your bug in the Mozilla project. ngx-extended-pdf-viewer modifies the original project to some extends, but it doesn't go deeper than a little facepaint.

Come to think about it - I'm not sure if it's possible to implement links to files on your disk. Sure, there's the `file://...` protocol. But this doesn't work well for relative paths. You'd need to put the fully qualified pathname in the PDF file. I don't think that works well in real-life. When one of the files is moved to another folder, the link breaks. Possibly that's why the Mozilla team chose not to implement this feature.

**Comment by ishanuda** [comment]
Hi,
Thank you for the information,

I could dig a little about the problem in PDF.js issues and found the following.

[Relative links to pdfs, not working](https://github.com/mozilla/pdf.js/issues/8771)

Here they have a solution with caution.
Is it a good idea to provide some interface to access/pass base RUL through the `ngx-extended-pdf-viewer`, so that the links will be resolved?

regards

**Comment by stephanrauh** [comment]
After adding several interfaces, I'm closing the ticket now. The typescript interfaces aren't complete yet, and they never will be. That'd be a huge task. But I've added the entire API ngx-extended-pdf-viewer is using. That should cover most usecases.
