### ISSUE TITLE
locale.properties does not load if we have different folder structure. 

### ISSUE THREAD

**Issue by roopeshkurian** [stephanrauh/ngx-extended-pdf-viewer#1922]
Thank you for releasing the new version. 

In the new version (18.1.4) of ngx-extended-pdf-viewer if I use the same folder structure as you mentioned in the documentation everything works well. But if I change the output folder and assets location, it is not loading locale.properties. 
I think I found a similar bug you fixed before. 
Please refer to the following bug report. 
https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/548

I am also facing the exact same issue. 

Version of ngx-extended-pdf-viewer is 18.1.4 

It will load the PDF file. But gives a 404 error for locale.properties. 

Thanks in advance.

**Comment by stephanrauh** [comment]
I'm afraid the library is not flexible enough to support arbitrary folder structures. You can move the assets folder to a different URL by configuring `pdfDefaultOptions.assetsFolder`, but the locale folder has to be a subfolder of the assets folder. You can omit most of the locales if you don't need them, but then, it doesn't make much of a difference, because only the files the user really needs are downloaded.

<img width="298" alt="grafik" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/3045767/ae7b4866-9bb7-4f32-93a6-97c2a37bc812">

Alternatively, you can embed the translations in your `index.html` (or any other HTML file loaded prior to the PDF viewer), as described in https://pdfviewer.net/extended-pdf-viewer/i18n.

Does this help you?

Best regard,
Stephan

**Comment by roopeshkurian** [comment]
Dear Stephan,

I am able to load other pdfviewer files from the assets folder. But nothing is loading from the locale folder.  But it was working well in earlier versions like 18.0.0, and 18.0.1
I don't understand why its not loading anything from locale sub folder. 

Can you please help me? 

Thank you
