### ISSUE TITLE
Property [ignoreKeyboard] don't stop CTRL+Mousewheel from zooming the PDF

### ISSUE THREAD

**Issue by Dragonfist07** [stephanrauh/ngx-extended-pdf-viewer#193]
Hallo,

I have embedded the pdf-viewer and would still like to zoom the entire page with CTRL + Mousewheel and not the PDF in the viewer. I hoped that [ignoreKeyboard] is the option to make that happen, but unfortunately that's not the case. Is it meant to be like that or is it a bug? And is there an other way to make that happen?

Best regards,
Jonas

**Comment by stephanrauh** [comment]
Well, I didn't implement this feature simply because I don't own a mouse. :) My computer has a great trackpad, when I started pair programming some time ago, I actually felt clumsy with the mouse at first. Can you believe that?

Back to topic. What did you try to do? Something like `[ignoreKeyboard]="'CTRL+Mousewheel'"`?

Mouse wheel support works a bit different in pdf.js, so that approach is doomed to fail. But I wonder if it's so intuitive I should implement it nonetheless. More likely I'll implement a dedicated attribute, or document how to suppress the feature using the underlying API of pdf.js.

Until I've made up my mind, you can do this:
```TypeScript
((window as any).PDFViewerApplication.supportedMouseWheelZoomModifierKeys = {};
````

I didn't try this yet (remember: no mouse!), but I'm pretty sure it does the trick. Please report back if I'm right or wrong.

Thanks in advance,
Stephan

**Comment by Dragonfist07** [comment]
Thank you for your fast reply!

At a time when the majority use smartphones and laptops, I can understand that. Unfortunately, my application is only used on the desktop and therefore cannot do without this feature, but I guess my requirement is a rare case. 

Yes, I tried `[ignoreKeyboard] = "true"`. And also with `[ignoreKeys] = "CTRL"`. I have to admit I haven't dealt with pdf.js that much yet.
`window.PDFViewerApplication.supportedMouseWheelZoomModifierKeys = {};` or `window.PDFViewerApplication.supportedMouseWheelZoomModifierKeys = {ctrlKey: false, metaKey: false};` did not work.

But thanks for the tip. I want to deal with it again in the next few days and maybe I can catch the key event in the dom beforehand.

Best regards,
Jonas

**Comment by stephanrauh** [comment]
While I'm still undecided about `ignoreKeyboard`, I've implemented `[acceptKeys]="['Ctrl+WHEEL']"` and `[ignoreKeys]="['Ctrl+WHEEL']"`. At least I hope so. I'm going to run a test tomorrow, when I can lend a mouse. As to my experience, no feature ever runs without testing. :(

Be that as it may, you can test the feature at https://pdfviewer.net/keyboard or by updating to ngx-extended-pdf-viewer 2.0.0-alpha.9.

Enjoy!
Stephan

**Comment by stephanrauh** [comment]
Version 2.0.0-alpha.10 has landed, and it finally brings a working implementation of `[acceptKeys]="['Ctrl+WHEEL']"` and `[ignoreKeys]="['Ctrl+WHEEL']"`.

Enjoy!
Stephan
