### ISSUE TITLE
Add attributes to set the color, width, and size of the text editor and the ink editor

### ISSUE THREAD

**Issue by stephanrauh** [stephanrauh/ngx-extended-pdf-viewer#1941]
### Discussed in #1927 

<div type='discussions-op-text'>

<sup>Originally posted by **PatrickZimmerer** October 27, 2023</sup>
Is there a way to change the default options for Annotations when using the "FreeTextEditor" and the "DrawEditor"? I tried manipulating the input fields with plain JS and the values on the slider changed but as soon as I click the PDF it gets reset to the editors' default values.</div>

**Comment by Tweniee** [comment]
Is this related to #1884 ? @stephanrauh

**Comment by stephanrauh** [comment]
Yes, you're right, the tickets are related.

**Comment by PatrickZimmerer** [comment]
@Tweniee is there any updates on this? Also is there a way I could assist you?

**Comment by PatrickZimmerer** [comment]
@Tweniee I have looked into the code a couple of times, and also looked into pdf-js where there is defaultOpacity, defaultThickness, etc. but I don't have a clue on how to manipulate this on our end. Would you have time for a quick meeting to show me what you have done already and what is left to do?

**Comment by Tweniee** [comment]
@PatrickZimmerer you have to use this, have a look and do let me know you understand it or not.
ihttps://github.com/stephanrauh/pdf.js/blob/6d319357c859554a7ca5b3355405fd1195b45c0f/web/annotation_editor_params.js#L36-L60

**Comment by engrmehdi** [comment]
Hi is there any way to add image programmatically instead of adding from browse file.

**Comment by PatrickZimmerer** [comment]
@Tweniee @stephanrauh I have forked and cloned the project as well as cloned the showcase into a folder pdf, I basically did all the steps in the [how-to-build](https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/main/projects/ngx-extended-pdf-viewer/how-to-build.md) but on the last step ```npm run ts``` it fails because of the imports of ```fs``` & ```sass``` in ```compile-sass.ts``` here is the error:
`(node:74161) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
.../pdf/ngx-extended-pdf-viewer/compile-sass.ts:1
import * as fs from 'fs';`

Any Ideas on how to get this running would be appreciated.

**Comment by stephanrauh** [comment]
@PatrickZimmerer Oops, sorry, that's my fault. Currently, I'm trying to configure Jest, and that has side-effects. If you pick up my latest commit, `npm run ts` works again.

**Comment by PatrickZimmerer** [comment]
@stephanrauh quick heads up, the error got resolved with your changes but I'd adjust the how-to-build.md, since I had to add the myPdf.js folder and clone the listed link below to run `npm run ts` successfully, so it shouldn't be marked as optional in the image, or mentioned below, that if this folder + needed files (used in `extract-version.js` line 8 ) are missing it won't start.

The error would be `Error: ENOENT: no such file or directory, open '../mypdf.js/web/ngx-extended-pdf-viewer-version.js'`

**Comment by stephanrauh** [comment]
@PatrickZimmerer Thanks for the hint. I did it the other way round: `extract-version.js` shouldn't break if mypdf.js isn't there.

**Comment by PatrickZimmerer** [comment]
@stephanrauh this sounds good, I got the project running but I have no clue on how to change the default values in the editors let alone passing it from ngx-extended-pdf-viewer to pdf.js
I tried the file mentioned above by tweenie and setting fixed values but nothing seems to apply even after restarting the preview.
Do you have any hints?

**Comment by stephanrauh** [comment]
I might have a look after Christmas.

**Comment by madhuputtam1992** [comment]
Hi All, 

Any Update on this?

I am also looking for same functionality and facing same issue I tried manipulating the input fields but as soon as I click the PDF it gets reset to the editor's default values.

**Comment by stephanrauh** [comment]
No, I'm afraid not. At the moment, I'm reading legal papers and wonder what the European Cyber Security Act means for this project. That's currently my top priority.
https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CONSIL:ST_17000_2023_INIT

**Comment by stephanrauh** [comment]
I'm closing this ticket now because I don't think I'll ever manage to address it.
