### ISSUE TITLE
A new approch needed

### ISSUE THREAD

**Issue by Tweniee** [stephanrauh/ngx-extended-pdf-viewer#1952]
Hi @stephanrauh, as the package continues to grow and you're actively seeking contributions from the community, I'd like to bring up a concerning issue. It's quite inconvenient that even after making a small change, we have to repeatedly run these commands to see the impact:

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/93429474/4b6e5a29-3dc7-4d28-8fed-e2341e463734)

Exploring a more efficient approach would be beneficial, especially for new developers trying to understand and contribute to the codebase. I hope you can consider this perspective.

**Comment by stephanrauh** [comment]
This part of the documentation still exists? I wasn't aware of that. But first things first: thank you very much into learning how to modify and build the library, and - if I'm lucky - learning how to contribute. Much appreciated!

I've streamlined my workflow several versions ago. Nowadays, I usually run merely two scripts:

- `npm run full` compiles pdf.js, ngx-extended-pdf-viewer, and the showcase. Plus, it starts the showcase.
- `npm run ts` does the same without compiling pdf.js. That's a useful script if you've modified the TypeScript code, but not the base libraries.

I'm a bit unhappy with these script because they're not as fast as I'd like them to be. But at least they are simple!

**Comment by stephanrauh** [comment]
BTW, I'm always open to suggestions. If you've got a complaint, fire away. If my hints help you, please tell me about it, too, so I know I can close the ticket.

**Comment by stephanrauh** [comment]
To-dos left:
- [ ] remove / update `how-to-build.md`

**Comment by Tweniee** [comment]
Thank you for the information. I'm currently utilizing these statements in my CLI. 
`cd .. && cd ngx-extended-pdf-viewer && npm run showcase && cd .. && cd extended-pdf-viewer-showcase && ng s -o`
because this command lets me keep in one terminal and i can run single script all at once.

I'm curious if there's a way to enable hot reload specifically for TypeScript files and not the original library. Any insights on that?

> This part of the documentation still exists? I wasn't aware of that. But first things first: thank you very much into learning how to modify and build the library, and - if I'm lucky - learning how to contribute. Much appreciated!
> 
> I've streamlined my workflow several versions ago. Nowadays, I usually run merely two scripts:
> 
> * `npm run full` compiles pdf.js, ngx-extended-pdf-viewer, and the showcase. Plus, it starts the showcase.
> * `npm run ts` does the same without compiling pdf.js. That's a useful script if you've modified the TypeScript code, but not the base libraries.
> 
> I'm a bit unhappy with these script because they're not as fast as I'd like them to be. But at least they are simple!

**Comment by stephanrauh** [comment]
I'm missing hot module reloading badly! Actually, it did work in the early Angular versions. With contemporary Angular, you have to deactivate the compiler cache, but I think I already did this because otherwise the `ng s` command ignores the update `node_modules` folder.

In theory, there's a npm command the does the trick. Unfortunately, I've never been able to wrap my head around `npm link`. If you figure out how to use it, please tell me!
