### ISSUE TITLE
Zoom out and Rotation Issue with custom annotation tool markings

### ISSUE THREAD

**Issue by madhuputtam1992** [stephanrauh/ngx-extended-pdf-viewer#1954]
Hi,

I have implemented some custom annotation tools but facing issue with zoom and rotation.

**Zoom Out Issue: only when zoom scale is less than 75%,  if zoom scale is greater than 75% then I am able to resize  my annotation markings based on current zoom scale perfectly.**

And Please suggest me how I can rotate my annotation markings based on page rotation angle.?

My custom tool markings also should work same as built in annotation marking which are available in ngx.

**Or suggest me how can I add my annotation markings(canvases) also to the built in annotation marking list?**

**Comment by stephanrauh** [comment]
@madhuputtam1992 You've opened the ticket in the showcase repository. I've moved it to the library repository because that's my principal to-do list.

**Comment by stephanrauh** [comment]
To be honest, I don't know enough about how to implement annotation tools to answer your question. However, the source code of the built-in tools isn't that difficult. So I'd like to point you to this sourcecode, hoping you'll find the answer over there: https://github.com/mozilla/pdf.js/tree/master/src/display/editor

**Comment by stephanrauh** [comment]
If my hint helps you, please tell me, so I know I can close the ticket.

**Comment by madhuputtam1992** [comment]
Dear @stephanrauh ,

I hope this message finds you well. I am currently facing a challenge with appending annotation markings in my project, and I would appreciate your expert insights to help resolve the issue.

Initially, I appended my annotation markings using the following code snippet:
const viewerContainer = document.querySelector('.pdfViewer') as HTMLElement;
viewerContainer.appendChild(this.drawCanvas);

This approach presented an issue when zooming out to a scale less than 80%, and to address it, I made the following modification:
const annotationEditorLayer = document.querySelector('.annotationEditorLayer') as HTMLElement;
annotationEditorLayer.appendChild(this.drawCanvas);

While this adjustment resolved the zooming issue, it introduced a new problem—I am now unable to draw any annotation markings on pages other than the first one.

I would greatly appreciate any guidance or suggestions from the community to help me overcome this challenge and ensure that annotation markings can be drawn on all pages successfully.

Thank you in advance for your assistance.

**Comment by stephanrauh** [comment]
Now I see! I'm a bit surprised the PDF viewer respects your custom annotations at all. I have to admit your approach is clever. With a little effort, you'll be able to get it up and running.

The little effort - probably - boils down to redrawing your custom annotations when the event `(annotationsRendered)` or `(pageRendered)` is fired. However, you need to adjust your canvas to the zoom factor and the rotation. Neither ngx-extended-pdf-viewer nor pdf.js can help you with that. They don't even know about your custom annotations.

That's why I'm surprised you've managed to achieve so much. You're circumventing the rendering engine of pdf.js.

That probably also explains your "first page only" problem. pdf.js renders its pages lazily. Maybe you it hasn't rendered the page you want to annotate yet.

Or maybe it's that you didn't take the structure of the DOM tree into account. `.pdfViewer` covers the entire PDF. Such a PDF file consists of multiple `.page` elements. Each of them has - optionally - an `.annotationEditorLayer`. It also may have a `.textLayer` and an `.annotationLayer`. It depends on the PDF document. The only `<div>` that's always there is the `.canvasWrapper`. Or rather, it's always there when the page is visible. Lazy loading means that most `.page` `<div>` tags are empty skeletons.

Open your browsers "elements" viewer and inspect the DOM.

**Comment by stephanrauh** [comment]
I'm closing the ticket now. I hope I've been able to shed some light on your issue. If not, keep asking!

Best regards,
Stephan
