### ISSUE TITLE
Flipbook side bar changes resolution of the document

### ISSUE THREAD

**Issue by redrubytech** [stephanrauh/ngx-extended-pdf-viewer#1955]
I was going through this plugin for using in one of my project. It works well without any major issue.
But recently i noticed that when we click on the side bar to view the document outline, then the  default resolution of the document display is getting distrubed.
![Screenshot from 2023-11-16 16-09-47](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/150144685/c297a7de-2c8a-47d6-8658-b574d7de3d34)
Attached is a screenshot which can be shown in the default demo page.
The document page gets cut and only a portion of the document is visible.
Is it a known bug or how to fix this

**Comment by stephanrauh** [comment]
... ading insult to injury, you even show it in my showcase. :) Of course, that's great news, because it means I can reproduce the bug easily. Only - it doesn't show on my machine. So I need your help to reproduce and fix the bug. How can I reproduce it? What's your screen resolution?

Actually, maybe the PDF document is the culprit. Many PDF documents set the zoom factor when you click a thumbnail. IMHO that's a bad idea, but the PDF standard allows you to do so, and many authors do so without even knowing. As far as I remember, the PDF document you've shown in the screenshot is one of the "evil ones" (for want of a better word).

**Comment by redrubytech** [comment]
Hi,
My screen resolution is  1360x768  and am running Ubuntu 22.04 on wayland.
I noticed that the problem is lying with the way the book mode is loaded. It is reproducible with any type of PDF.
The plugin first loads the PDF document with a defined size (fit to page in my case) and when we click on the sidebar , to draw that widget the bookmode is getting shrinked / adjusted. At that time the page cutting issue is coming.
[Uploading Screencast from 17-11-23 10:47:45 AM IST.webm…]()

Attached is the sample screencast i recorded for your better understanding.

**Comment by stephanrauh** [comment]
@redrubytech I'm afraid your link to the screencast is broken.

As for the ticket: I suspect the "fit to page" bit is the problem, especially if my theory is correct that clicking the PDF thumbnails modifies the zoom factor.

**Comment by redrubytech** [comment]
Apologies for the late reply.
Attached is the proper screencast for your reference.
[Screencast from 17-11-23 10:47:45 AM IST.webm](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/150144685/e886852b-8337-4568-af83-2d1a05250a74)

**Comment by stephanrauh** [comment]
That rings a bell. Try setting `pdfDefaultOptions.ignoreDestinationZoom=true`. That should fix your issue.
