### ISSUE TITLE
PDF with form during print/download is empty

### ISSUE THREAD

**Issue by peopledrivemecrazy** [stephanrauh/ngx-extended-pdf-viewer#1969]
I am currently using `18.0.0-beta.10` because the viewer crashes if a checkbox depends on a script (https://github.com/mozilla/pdf.js/issues/16863).

Printing or downloading only shows a blank form; sometimes it works, and sometimes it doesn't. I am not able to reproduce this bug consistently. Updating to the latest version breaks the patch released with `18.0.0-beta.6`.

Using 18.1.6 and  18.1.7 breaks the form, but it contains the filled information when printing.

Related to #1917 #1887

**Version info**
- 18.0.0-beta.6

I would like the forms to work as before with printing. Sorry, I am not able to pin the issue down for you correctly.

**Comment by peopledrivemecrazy** [comment]
Upon further inspection, without binding the formData using this [form](https://www.forms.ssb.gov.on.ca/mbs/ssb/forms/ssbforms.nsf/FormDetail?OpenForm&ACT=RDR&TAB=PROFILE&ENV=WWE&NO=014-4422-84) checks all checkboxes, this doesn't happen with the Mozilla pdfjs viewer.

**Comment by stephanrauh** [comment]
I'm confused. If you need the bugfix, why do you stick to the old version? The bugfix should also be available in the newer versions.

I'll examine the checkbox problem (#1920) first - maybe that solves the other problems, too.

**Comment by peopledrivemecrazy** [comment]
Sorry for the confusion. The newer version indeed has the bug fix but contains the checkbox problem. I am using the old version only right now because it can fill the form correctly and preview it, but only during print is it blank.

Thanks for your response 🚀

**Comment by stephanrauh** [comment]
So I guessed correctly. :) Usually, print problems are CSS problems, but in your case, I'm not sure. Your bug description sounds a bit differently.

**Comment by peopledrivemecrazy** [comment]
I will set up a test repo.

**Comment by stephanrauh** [comment]
Please update to version 18.1.8. Now the checkboxes behave as they should.

**Comment by peopledrivemecrazy** [comment]
Haha! Brilliant, @stephanrauh; I was setting up an example repo, which downloaded `18.1.8.`. I was testing now.

**Comment by peopledrivemecrazy** [comment]
As I was testing with both `bleeding-edge` and without it, a particular set of checkboxes remained checked
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/3922469/5d786fc9-4d51-4524-a0d4-7b7b22c04860)

[repo here](https://github.com/peopledrivemecrazy/ngx-extended-pdf-viewer-1969)

**Comment by stephanrauh** [comment]
Thanks for the repo. It helped me to find the issue quickly. PDF checkboxes are very confusing. For example, this particular checkbox is a radiobutton in disguise.

**Comment by stephanrauh** [comment]
@Calixteman I've stumbled upon a line you've changed recently:

https://github.com/mozilla/pdf.js/blob/5781e722bf1c56168b5cbd8d4b40184d30381a71/src/display/annotation_layer.js#L1548

Does this work for checkboxes that are radiobuttons in disguise? Like the checkboxes in the PDF file mentioned above: checking one of the three checkboxes unchecks the other two. What about this version?

```js
    if (typeof value === "string") {
      // The value has been changed through js and set in annotationStorage.
      value = value === data.exportValue; // <<< modified line
      storage.setValue(id, { value });
```

**Comment by stephanrauh** [comment]
@peopledrivemecrazy Your bug fix has landed with version 18.1.9.

**Comment by calixteman** [comment]
It was 2 years ago...
If I remember correctly, this stuff is used when a checkbox is rendered but have been modified when the page wasn't rendered.
I just read again the [specs](https://opensource.adobe.com/dc-acrobat-sdk-docs/pdfstandards/PDF32000_2008.pdf#page=448&zoom=auto,-410,760) about checkboxes and we should have a `Off` and in our code we try to be sure to have one:
https://github.com/mozilla/pdf.js/blob/5781e722bf1c56168b5cbd8d4b40184d30381a71/src/core/annotation.js#L3162-L3230
So since `Off` is the only "sure" thing, we rely on it.
And in looking in the js side:
https://github.com/mozilla/pdf.js/blob/5781e722bf1c56168b5cbd8d4b40184d30381a71/src/scripting_api/field.js#L655-L661
and especially the setter in the radio class:
https://github.com/mozilla/pdf.js/blob/5781e722bf1c56168b5cbd8d4b40184d30381a71/src/scripting_api/field.js#L589-L606
I think the value should be correct.
I created this pdf:
[test_cb.pdf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/13453572/test_cb.pdf)
and it behaves the same way in Firefox and Acrobat.
That said if you manage to create a pdf which demonstrates the opposite, I'm fine to change my mind.

**Comment by peopledrivemecrazy** [comment]
@stephanrauh, thank you so much for this fix. I'm sorry for not getting back to you sooner. I tested it, and it works!
