### ISSUE TITLE
Drag-and-Drop Components with Position Recognition

### ISSUE THREAD

**Issue by caeldev1** [stephanrauh/ngx-extended-pdf-viewer#1974]
For now we can just add image, text... as annotation to the pdf

A feature that allows users to place and manipulate custom components on a separate layer within the PDF using ngx-extended-pdf-viewer is very handful

Drag-and-Drop: The ability to drag and drop custom components onto the PDF viewer.

Resizing: A feature to resize the custom components for better placement and visibility.

Position Recognition: The capability to recognize the position of these components within the PDF, including the page index.

Enabling the placement of interactive elements on top of the PDF pages. It could be particularly useful for scenarios where additional information or interactive widgets need to be associated with specific parts of the document.

With custom components overlaid on the PDF and obtain their positions within the document.

It would be challenging but very helpful and handful

**Comment by stephanrauh** [comment]
That's beyond the scope of my library, but maybe it's a useful addition for pdf.js. @Calixteman Sorry for pinging you every day - but maybe here's an idea for pdf.js. In particular, dragging and dropping images to a PDF file.

**Comment by stephanrauh** [comment]
@caeldev1 Using `PdfViewerService.getSerializedAnnotations()` you can implement the position recognition yourself. Combine that with `PdfViewerService.removeEditorAnnotations()` and `PdfViewerService.addEditorAnnotation()` to implement the resize feature. 

If you do, please keep in mind that these method use an internal API of pdf.js that may break after an update. In fact, this happened several versions ago. Plus, I can't document the data structures of the serialize annotation because I'm not familiar with them.

Here are some demos: https://pdfviewer.net/extended-pdf-viewer/export-annotations

**Comment by stephanrauh** [comment]
Reluctantly, I'm closing this ticket now. I hope I've given you enough hints to enable to implement the features yourself.

Best regards,
Stephan
