### ISSUE TITLE
Zoom option automatically changes to "page width"

### ISSUE THREAD

**Issue by paucls** [stephanrauh/ngx-extended-pdf-viewer#1994]
**Describe the bug**
Zoom option automatically changes to "page width" when user navigates to a different page clicking on the left sidebar pdf table of contents.

**Steps to reproduce**
1. When pdf is loaded select "Automatic Zoom" (or any numeric value) zoom option dropdown.
2. Navigate to any section of the pdf using the the left sidebar. Then the zoom option changes to "Page width" automatically not keeping the value user selected previously.

**Version info**
Version of ngx-extended-pdf-viewer 18.1.4

**Demo PDF file**
Any file with a table of content.

**Comment by stephanrauh** [comment]
Try setting `pdfDefaultOptions.ignoreDestinationZoom=true`. That should fix your issue.

The root cause of your issue is that the author of the PDF document defined it this way. They activated a setting the sets the resolution when clicking a thumbnails. I suppose most PDF authors aren't even aware of this setting.

**Comment by paucls** [comment]
Hello all,

how should I set pdfDefaultOptions.ignoreDestinationZoom=true ?
looking at https://pdfviewer.net/extended-pdf-viewer/options it is not clear to me where to change that option.

**Comment by paucls** [comment]
I managed to fix the issue with your recommendation.
Many thanks.
