### ISSUE TITLE
Print function generate only the first sheet

### ISSUE THREAD

**Issue by iAnathema** [stephanrauh/ngx-extended-pdf-viewer#202]
Print function generate only the first sheet
Version of ngx-extended-pdf-viewer 2.0.0.alpha 2

 - OS: Windows 10
 - Browser: Chrome
 - Version 79.0.3945.130

![Capture](https://user-images.githubusercontent.com/22446001/73669013-c72d3200-4674-11ea-99a0-942ffb2c4f7d.PNG)

**Comment by stephanrauh** [comment]
Yeah... printing causes a lot of trouble. There are several tickets on this bugtracker covering print. It's almost always a problem with your CSS code. So I need more details. Which CSS framework are you using?

**Comment by iAnathema** [comment]
Nebular v.4.6.0

**Comment by nd1226** [comment]
I am also facing the same issue. When I am trying to print a page, Its coming as empty. I'm try using base64 ,src : https://vadimdez.github.io/ng2-pdf-viewer/assets/pdf-test.pdf 
![image](https://user-images.githubusercontent.com/42302752/73929754-fc9d7e00-4907-11ea-8243-647f632c2dd2.png)

**Comment by stephanrauh** [comment]
Printing is always a pain with pdf.js. Cutting a long story short, it's almost always your CSS code. The PDF viewer generates the PDF pages as a hidden list of images at the end of the HTML document. A media query inverts visibility: everything is hidden except the images. As it turns out, there are many ways to break algorithm.

Funny thing is the vertical line. That's a new one. I don't have a clue where this comes from.

Please have a look at #170, #164, #152, and #148. They contain several bug patterns that may help you to debug and solve your issue.

Oh, and please tell me when you've managed to solve your bug. You can also send me a reproducer (i.e. a small but complete example running out-of-the-box without forcing me to install anything) if you're still struggling with the bug.

**Comment by stephanrauh** [comment]
Sometimes adding this simple CSS snippets to the global `styles.css` helps:

```css
@media print {
  #printContainer > div {
    display: inline;
    overflow-y: visible;
  }
}
```

**Comment by stephanrauh** [comment]
@iAnathema @nd1226 Hi folks, did you manage to solve the issue?

I didn't hear from for for more than a week, so I'll close the ticket.

Best regards,
Stephan
