### ISSUE TITLE
Incorrect initial state of form checkboxes in some cases

### ISSUE THREAD

**Issue by mikalai-sihnevich** [stephanrauh/ngx-extended-pdf-viewer#2052]
**Check this first**
- Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.html?  - **No**
- Does the bug also happen on https://pdfviewer.net/simple? - **Yes**
- Can you write a reproducer based on a freshly created project? - <a href="https://github.com/mikalai-sihnevich/ngx-extended-pdf-viewer-checkboxes">Repo here</a> with test pdfs

**Describe the bug**
Something wrong with the initial display of checkboxes in PDF form.

For example, PDF form has a few checkboxes (which act as radio buttons).
If the second such checkbox (or third, ...) is initially checked it is showing as unchecked.
The same pdf is displaying correctly in another PDF viewers (like Adobe Acrobat reader, Mozilla pdf.js showcase).

**Version info**
- 19.0.4, 18.1.14

**Demo PDF file**
<a href="https://github.com/mikalai-sihnevich/ngx-extended-pdf-viewer-checkboxes/blob/main/src/assets/TestAcroForm3_no.pdf">TestAcroForm3_no.pdf</a>

**Comment by stephanrauh** [comment]
Special kudos for providing a reproducer!

**Comment by stephanrauh** [comment]
I think this is a corner-case I can't solve. These checkboxes aren't checkboxes. In reality, they are radio buttons in disguise. You could solve the problem by modifying the PDF file:

- Either you convert the check boxes to radio buttons. In this case, ngx-extended-pdf-viewer knows that it should use the export value. In other words, the `(formValues)` event emits the strings "Yes" and "No".
- Or you set the export values to "true" and "false". 

The problem is that ngx-extended-pdf-viewer renders the first checkbox called "checkbox1", detects that is does not have the export value "Yes", and stores the value `checkbox1=false`. A short time later, it detects the second checkboc with the same field name, looks up in its internal storage, and sees that there already a field value: `checkbox1=false`. The export value of the second checkbox is `"No"`, which is not the same as `false`, so it concludes that the Angular programmer wants to override the default value stored in the PDF file.

I'm sorry for the unsatisfactory answer. When I implemented the forms API, I wasn't aware of the mess the PDF file format is. I naively assumed that a checkbox is a a checkbox, so the only values are `true` and `false`, but in Adobe country, that's not quite true.
