### ISSUE TITLE
V19 - Rxjs backward compatibility (aka: get rid of the dependency on RxJS)

### ISSUE THREAD

**Issue by raphael22** [stephanrauh/ngx-extended-pdf-viewer#2077]
Using function from rxjs 7 introduce a compatiblity issue.
https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/19.0.6/projects/ngx-extended-pdf-viewer/src/lib/pdf-notification-service.ts#L2

**Error**
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/3912356/807f5500-23ad-46bb-a166-e73ce2aa35a6)

**Version info**
- 19

**Comment by stephanrauh** [comment]
What's stopping you from upgrading to RxJS 7?

**Comment by stephanrauh** [comment]
RxJS 7 has been release three years ago. The newest bug-fix release of RxJS 6 is also three years old. So I strongly recommend updating.

**Comment by stephanrauh** [comment]
I hear your pain, and I feel it. However, this is a non-commercial project. I'm doing it in my leisure time, and there's never enough leisure time... so I'm afraid I can only support a limited range of versions.

Talking of which, if I was to offer commercial support, would you pay me for bringing back compatibility to RxJS 6?

**Comment by stephanrauh** [comment]
When I looked into the source code this evening, I was in for a surprise. First, the dependency on `firstValueFrom()` is gone. It seems I've addressed your issue but forgot to modify the declaration in the `package.json`. When you update to the next version 20.5.0, your issue is gone.

Second, I saw that I don't really need RxJS. There are only two events, one of them internal, and both of them can be replaced by signals. That works even in Angular 16, if I'm not mistaken. So I'll probably drop RxJS with version 21.

**Comment by stephanrauh** [comment]
Version 20.5.0-alpha.4 has landed. It reduces the required RxJS version to 6.0.

**Comment by stephanrauh** [comment]
To dos left:
- [ ] remove the last remaining `Subject` in version 21

**Comment by stephanrauh** [comment]
Version 21.0.0-alpha.5 removes the dependency on RxJS entirely. I'll probably publish it later today.

Enjoy!
Stephan
