### ISSUE TITLE
Add universal support

### ISSUE THREAD

**Issue by ebondu** [stephanrauh/ngx-extended-pdf-viewer#213]
When using angular Universal with this lib, an error occurs because window does not exists on the server side

Server side rendering should ignore the lib to prevent undefined errors

Testing window object before to use it could be a possible solution

**Comment by stephanrauh** [comment]
Sound reasonable... it's a pity I don't have a node.js server, so I can't use Angular Universal. Can you send me a simple demo project? I know it's demanding a lot, especially since you've already spent time to send me a pull request. But it'd be just great!

Thanks in advance (even if you decline)
Stephan

**Comment by ebondu** [comment]
It should quite simple to test with a basic universal demo project, by adding the pdf viewer component on the demo page. You should see the 'undefined' error on window object. BTW I tested with the alpha 12 and no more errors on server side and pdf rendering ok on browser side.
