### ISSUE TITLE
How to get exception body message to the variable?

### ISSUE THREAD

**Issue by wider2** [stephanrauh/ngx-extended-pdf-viewer#2160]
When client trying to load corrupted PDF with the PdfViewer
we can see an Error Notes in cosole.log
That's right, but how to handle this information? I need to show this data in other UI div fields.

It could be different types of exception, but I expected to see some kind of [onError]="handleException($event)"

Sample:

Invalid or corrupted PDF file.

PDF.js v3.5.553 (build: 31d818330)
Message: The PDF file is empty, i.e. its size is zero bytes.
(anonymous) @ main.d10d90949a3fa4eb.js:1
viewer-3.5.553.min.js:23 Uncaught (in promise) InvalidPDFException
reportitem:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()

 viewer-3.5.553.min.js:23 Uncaught (in promise) InvalidPDFException {message: 'The PDF file is empty, i.e. its size is zero bytes.', name: 'InvalidPDFException', __sentry_captured__: true, stack: 'Error\n    at BaseExceptionClosure (http://localhos…/localhost:4200/assets/viewer-3.5.553.min.js:1:16'}

**Comment by wider2** [comment]
I think I have found the solution
Just need to call right method like this
(pdfLoadingFailed)="showError('pdfLoadingFailed', $event)"

**Comment by stephanrauh** [comment]
That's correct. At least that's the way I want it to be. Unfortunately, pdf.js uses so much asynchronous code it's impossible to follow all the event flows. In other words, I'm not sure if `(pdfLoadingFailed)` catches every error. If you run into a bug not reported by `(pdfLoadingFailed)`, you can catch and analyze the console logs. I've tried to describe this approach here: https://pdfviewer.net/extended-pdf-viewer/filtering-console-log.

(I'm writing "tried" because I'm afraid the documentation is a bit confusing, but I don't know how to improve it).

**Comment by stephanrauh** [comment]
I'm closing the ticket now because I believe you've managed to solve it yourself. If you've still got open questions, just add your comments below, and re-open the ticket as seems fit.
