### ISSUE TITLE
PDF Signature Validation and Custom HTML Injection

### ISSUE THREAD

**Issue by o-sirenko** [stephanrauh/ngx-extended-pdf-viewer#2167]
Hello, thank you so much for this amazing library. 
I have one question: is it possible to inject a custom HTML element into a PDF file and export it as part of a Blob?

I need to render the PDF file in the app and, upon clicking the Download button, export the PDF file as a Blob. Typically, I have PDF forms where users can input data into form fields and then download the PDF file. The issue is that I need to validate the download button and enable it only if the user has signed the document. So I can render the PDF file and add annotations like pencil or text drawing using the ngx-extended-pdf-viewer, but I can't validate whether the user has signed the PDF file or not.

In my old app, I use the "signature_pad" library to add the signature as an image to the HTML document. 
Is it possible to inject, for example, an HTML button element into the PDF file, generate the signature image using the "signature_pad" library, and then pass the image to the PDF file? 
Ultimately, I aim to download the PDF file as a Blob with my signature in a specific place within the PDF file.
Perhaps there is a simpler way to validate the signing of the PDF file, but unfortunately, I haven't found one yet. 
The user doesn't use an E-Signature; having a drawing feature to add a signature is sufficient.

**Comment by stephanrauh** [comment]
Whow, that's a difficult question, and an interesting one. I haven't understood everything, so I'm trying to break it down step-by-step. Correct me where I'm wrong!

- Injecting HTML in a PDF file: well, no, I don't think that's possible. I'm not sure. The PDF specification is a huge book, and I haven't read it yet. However, I believe HTML and PDF are two different cups of tea.
- However, I don't think you want to add the HTML button to the PDF file. More to the point, I don't want you to modify the PDF file. I'd prefer you to add the button to the PDF viewer instead of adding it to the PDF file. In theory, you could add the button to the annotation layer, so it'd look like a native part of the PDF file. But I don't want you to do so. I believe PDF files are all about trust. I want you to show the PDF file exactly the way the PDF author intended it to be seen. More likely than not, that's rubbish in your particular use-case, but it makes sense for me because I'm trying to cover the use-cases of countless other developers.
- However, as long as it's obvious the button is your addition, I'm fine with it. So either a custom toolbar or the `[customFreeFloatingBar]` might be your friends. Have a look at https://pdfviewer.net/extended-pdf-viewer/custom-toolbar.
-  I haven't seen the "signature-pad" library in action yet, but it sounds like a great tool, and if I understand you correctly, you've already figured out how to add images to the PDF file. If not, check out #2148: I haven't tried it myself yet, but I hope the discussion tells you how to add an image to the PDF file. Or rather, to the annotation layer of the PDF file. Technically speaking, that's a difference because the annotation layer is an addition to the PDF file, but few user's will notice.
- After solving all those challenges, downloading the Blob shouldn't be a problem. The showcase demo https://pdfviewer.net/extended-pdf-viewer/export-file shows you how to do it.

Oh, and I've just seen this is your first issue you've opened on GitHub. I feel very honored!

Best regards,
Stephan

**Comment by o-sirenko** [comment]
Hello Stephan, you're right, I need to add the signature as an image to the PDF viewer instead of to the PDF file.
Thank you so much for the suggestions, I will try implementing them in my app.

Yes, it was my first issue :-)

Best regards, 
Alex

**Comment by o-sirenko** [comment]
Hello @stephanrauh, tell me please, is it possible to show the values in the read-only form input fields in the PDF viewer if I set the read-only type to some of my form input fields in the PDF editor. 
I use [(form-data)] to pass data from the server to the pdf-viewer.
Currently, I'm unable to view the values of my read-only form input fields within the pdf-viewer. However, if I export the PDF file as a Blob, I'm able to see the values of my read-only input fields.

<img width="733" alt="Screenshot 2024-02-22 at 22 00 58" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/75850702/32157bec-05aa-4282-a4ce-2840b90c4d18">
<img width="744" alt="Screenshot 2024-02-22 at 22 01 40" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/75850702/0c5d6224-18d9-467f-b128-85c25e55a27f">

**Comment by stephanrauh** [comment]
Good question. Probably it depends on your PDF file. Please open your browsers developer tools and inspect the annotation layer. If you click on an input field, you'll see an HTML `<input>` field in the DOM inspector. What happens if you click a read-only field? Is it a real `<input>` field? Or is it simply a drawing in the underlying canvas?

**Comment by o-sirenko** [comment]
Thank you, I see that the read-only input fields have the attribute [hidden], perhaps some additional attribute is coming from the original pdf file and the pdf viewer tries to adjust pdf configs therefore I can't see the values.
Fortunately, it can be fixed through the CSS.

**Comment by stephanrauh** [comment]
I've found a line in the source code of pdf.js that might hide read-only fields. However, I can't say for sure because I don't have a PDF file with read-only files at hand, so I can't debug. Nonetheless, if CSS solves you issue, I'd say that solution is good enough. Maybe there's a reason why pdf.js hides the fields, so I don't want to change that lightheartedly.

**Comment by stephanrauh** [comment]
BTW, I suppose you've managed to solve both issues, so I'd like to close this ticket.

Best regards,
Stephan
