### ISSUE TITLE
blob open in new tab 

### ISSUE THREAD

**Issue by sathiyam-optisol** [stephanrauh/ngx-extended-pdf-viewer#217]
Hi @stephanrauh  
I need your help.
How to open blob in new tab window. Using ngx-extended-pdf-viewer
I'm used this code for open blob in new tab window.

` const openBlop = new Blob([body], { type: 'application/pdf' });
        const fileURL = URL.createObjectURL(openBlop);
        window.open(fileURL, '_blank');`

**Comment by stephanrauh** [comment]
Are you looking for this? 
https://stackblitz.com/edit/angular-open-window?file=src%2Fapp%2Fapp.component.ts
https://mentormate.com/blog/create-modal-window-with-angular-cdk/
https://medium.com/angular-in-depth/angular-cdk-portals-b02f66dd020c

I didn't manage to get it up and running with my Angular 9 showcase yet. There are breaking changes in Angular 9, maybe that's the reason. 

In any case, this approach looks a little exotic to me. Why don't you simply open a new window and use the native PDF viewer of the browser?

**Comment by sathiyam-optisol** [comment]
Thank you for your response @stephanrauh . 
I am do with old way the open new tab blob.
`const openBlop = new Blob([body], { type: 'application/pdf' }); const fileURL = URL.createObjectURL(openBlop); window.open(fileURL, '_blank');`
Currently not changed. It's worked.

**Comment by stephanrauh** [comment]
You've piqued my curiosity. I've managed to open a new window controlled by the same Angular application: https://github.com/stephanrauh/angular-open-window

However, opening the PDF viewer in the new window turned out to be difficult. Mozilla's PDF viewer stores many variables in the global variable `window`. The new window is a different window, so it doesn't share these global variables. I suppose it's possible to solve this challenge with a little stubbornness, but it's not that easy.

I've published my unfinished work in this branch: https://github.com/stephanrauh/extended-pdf-viewer-showcase/tree/open-PDF-in-a-new-window

**Comment by afridi26** [comment]
Hey, supporting the feature of opening pdf in a new tab. I really need this feature because I don't want to open pdf on the same page but when a user clicks on the link I want to open a new tab and display the pdf.

Such feature is already provided by [ng2-pdfjs-viewer](https://github.com/intbot/ng2-pdfjs-viewer) using attribute `[externalWindow]` can you provide support for it? Any updates?
