### ISSUE TITLE
Change page on scroll end with scrollMode="3" ?

### ISSUE THREAD

**Issue by farisshomali** [stephanrauh/ngx-extended-pdf-viewer#2189]
I'm trying to change the page when user swipe up/down...

so when the scroll event is completed we can call pdfService.scrollPageIntoView(currentPage+1)

i tried that using HostListener but it didn't work..

  @HostListener('window:scroll', ['$event'])
  onScroll(event: Event) {
    this.scrolling = true;
    clearTimeout(this.timeout);
    this.timeout = setTimeout(() => {
      this.scrolling = false;
    }, 200);
  }
  
  Any ideas ?

**Comment by stephanrauh** [comment]
I guess it doesn't work because you can't scroll in page view mode. Try detecting the swipe gesture instead. It doesn't have a nice integration with Angular, so you need a more bare-boned approach, but it's pretty straight-forward:

https://dev.to/this-is-learning/detect-swipes-with-reactive-programming-1bph

https://angularindepth.com/posts/1256/gestures-in-an-angular-application (but I'm not sure if Hammer.js is still the tool of choice in 2024 - please double-check this)

The library already has support for gestures, so I hope there's no conflict, but I don't think so.
