### ISSUE TITLE
PDF viewer crashing mobile browsers

### ISSUE THREAD

**Issue by tim-musgrove-vcs** [stephanrauh/ngx-extended-pdf-viewer#220]
I am using this pdf viewer to view multiple PDFs that are stored in AWS S3. Part of the functionality is to switch between different pdfs that correspond to different dates. These PDFs are fairly colorful and detailed, but the size is about 100kb and they are only one page. The issue is that on desktop browsers it works fine, but on most smartphone browsers the pdf viewer causes the browser to crash with "Aw Snap" message or other related message. The pdf will render correctly before it causes the crash. The only browser that works on mobile is firefox. I have seen that this has been an issue with pdf.js for a long time. I have confirmed that it is the pdf viewer that causes the issue, but I don't see this issue when loading some simpler test pdfs. The pdfs I am using can't be shared. Using ^1.8.4

**Comment by stephanrauh** [comment]
Whow. I can only guess - when you're talking about "mobile devices", you're referring to Android?

Well, if that's an unsolved problem of pdf.js, there's nothing I can do about it. I've modified pdf.js in many places, but that's far beyond my reach. If you're opening the PDF files with https://mozilla.github.io/pdf.js/web/viewer.html, does the error still happen?

If not, maybe updating to pdf.js 2.4 might help. I could do that for you. Otherwise, I don't see any option except closing the ticket reluctantly without solution.

**Comment by tim-musgrove-vcs** [comment]
Now that I look it's also happening in that pdf,js web viewer.

**Comment by tim-musgrove-vcs** [comment]
Yes, android and IOS.

**Comment by stephanrauh** [comment]
> Now that I look it's also happening in that pdf,js web viewer.

What a pity. Just out of curiosity: Do you have a ticket number, so I can have a look what's going wrong?

> Yes, android and IOS.

Thing is there's no real Firefox on iOS. When I checked last time, the Firefox browser on iOS used the same rendering engine as Safari. So I assume the PDF file crashes Firefox on iOS, too. :(

Best regards,
Stephan
