### ISSUE TITLE
Adding/Viewing Comments in a PDF

### ISSUE THREAD

**Issue by ptatoChi** [stephanrauh/ngx-extended-pdf-viewer#2276]
Hi, I've been using this library for a while. I like that it has now the ability to highlight, add stamps (image) and draw.

Im wondering if we could add comments too? I tried it in some pdf viewers native to some browsers (edge, mozilla) and i can add and view comments.
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/11557985/1728c7b3-32e3-4d29-819c-585ac7acb919)

Would it be possible for this library to have that too?

**Comment by stephanrauh** [comment]
Generally speaking: yes, this is possible - but I'm afraid I can't do it in my limited leisure time. So you've got two options. You can implement comments yourself and send me a pull request. I know that's not what you want to hear, but hey, this is an open-source project, so it was worth a try! :)

The other option is you talk to @calixteman, offer them a couple of beers (or coffee, or cake, or whatever), and convince them to implement this feature in pdf.js. BTW, I assume you, @calixteman, are reading this - adding comments seems to be a popular feature. This is already the second or third feature request.

Talking about pdf.js: are you sure you've seen the comment function in Firefox? ngx-extended-pdf-viewer is using pdf.js, which is also the PDF engine of Firefox, and I tend to use a more current version of pdf.js. So it's unlikely that Firefox already supports comments. Or did I miss the feature? pdf.js is so incredibly versatile that this is possible, too, but my gut feeling says comments aren't there yet.

Oh, there's a third option. At the moment, I don't find it, but if you dig into the current discussions or issues, you'll see that another user implemented comments themselves using a third-party PDF editor library and some clever programming. If you find the corresponding ticket, please tell me, because I'd like to mention the idea in the showcase.

**Comment by stephanrauh** [comment]
I'm keeping this issue open for a few days, but I won't implement the feature myself. If there's no volunteer, I'll reluctantly close the ticket after a while.

**Comment by ptatoChi** [comment]
Thank you, @stephanrauh :D Ill try too look into your suggestions. Thank you so much

**Comment by stephanrauh** [comment]
I'm closing the ticket now. If anyone's willing to offer a pull request, go for it!
