### ISSUE TITLE
ngx-extended-pdf-viewer not working after angular upgrade.

### ISSUE THREAD

**Issue by manzoorsharif123** [stephanrauh/ngx-extended-pdf-viewer#2325]
Hi Stephan.

After updating Angular version from 6.3 to 17, PDF viewer is not not working and not showing any content in UAT environment.
In dev / local it is working perfectly fine.

**Describe the bug**
See the screenshot

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/108550245/8f86fe4a-d21d-4558-b06b-a64449acaca2)

**Version info**
- Version of ngx-extended-pdf-viewer = 19.7.1

**Demo PDF file**
Many errors happen with specific PDF files only. So please add a PDF file (after checking the copyright of the PDF file first!)

[Leadership Grant.pdf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/15195242/Leadership.Grant.pdf)

**Comment by stephanrauh** [comment]
You need to configure your server such that it detects *.mjs files as JavaScript files. I've described this for several servers here: https://pdfviewer.net/extended-pdf-viewer/troubleshooting

I'm not sure why my library switches to ES5 files. Maybe that's because I've raised the minimum required browser version, and your browser is older. Or maybe updating to version 20.0.1 helps. One of the versions I've published didn't detect the correct browser version correctly. However, as far as I remember, I quickly uploaded a patch version fixing this bug.

BTW, sorry for answering late - I was busy during the last couple of days.

**Comment by stephanrauh** [comment]
As usual, I'd appreciate your feedback. I've closed the bug because I believe my hints help you, but it'd be nice to know for sure.
