### ISSUE TITLE
The bcmap file is lost for specific Japanese PDFs.

### ISSUE THREAD

**Issue by kmt-t** [stephanrauh/ngx-extended-pdf-viewer#2344]
I apologize for my limited English and insufficient explanation. I have created an issue in the Kavita project with more details.

https://github.com/Kareadita/Kavita/issues/2970

I cannot share the problematic PDF publicly due to copyright restrictions.

**Comment by stephanrauh** [comment]
I've opened one of my few Japanese PDF files that load a bcmap in the showcase. It looks OK to me. Does Kavita add the bcmap to the assets folder, and it the application correctly configured so it can load the bcmap? Please check the network tab for errors.

<img width="2041" alt="image" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/3045767/4fae0a48-fdb7-4d6e-b408-8c3fb6a5a1dd">

**Comment by stephanrauh** [comment]
OK, I just saw that you did check the URL and the assets folder. It seems your installation puts the files into the wrong folders. There's a property to configure the file of the CMAP files (`pdfDefaultOptions .cMapUrl`), but I suppose it's besser to investigate why the file is copied to the root folder instead of the assets folder.

**Comment by kmt-t** [comment]
Thank you for your kindness.

I will request to close this ticket once the communication on the Kavita side is concluded.

**Comment by stephanrauh** [comment]
That's great news!
