### ISSUE TITLE
Support for Angular 18

### ISSUE THREAD

**Issue by krausep** [stephanrauh/ngx-extended-pdf-viewer#2351]
**Is your feature request related to a problem? Please describe.**
It is not related to a problem, it's a feature request.

**Describe the solution you'd like**
I'd like for `ngx-extended-pdf-viewer` to support Angular 18.

**Describe alternatives you've considered**
I haven't considered any alternatives.

**Additional context**
Angular 18 was made generally available on May 22, 2024. I've enjoyed using `ngx-extended-pdf-viewer` and would like to update my application to Angular 18. Please let me know if there is a preferred way to raise this request. Thank you for maintaining this library!

**Comment by stephanrauh** [comment]
Version 20.5.0-alpha.1 supports Angular 18. I've called it an alpha version because I did some non-trivial changes and I want to test it for a while, but everything seems to be working, so I guess it'll become a regular version soon.

The older versions are also compatible to Angular 18, but I didn't declare that in the package.json, so you need to use a force install (`npm install --force ngx-extended-pdf-viewer`).
