### ISSUE TITLE
ngx-extended-pdf-viewer giving 404 not found error.

### ISSUE THREAD

**Issue by Jammy1299** [stephanrauh/ngx-extended-pdf-viewer#2369]
I have updated my ngx-extended-pdf-viewer to version 19.4.1 and my angular application to version 16.

The ngx-extended-pdf-viewer is working fine in local. But when I am deploying this to environment I am getting this error.

![pdf issue](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/172570949/9d89d58a-57b4-4132-8860-b3326f7f2571)

And In network tab I can see this

![pdfissue2](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/172570949/32cd793a-fe13-4836-b805-0fce957db3f8)

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/172570949/59308b1f-d38c-4c16-abdc-98e955f052be)

extra assets label in adding in the URL.

I am using chrome browser.

**Comment by stephanrauh** [comment]
Yes, there's an extra `assets/` in the URL when the viewer tries to load the worker into the main thread. But it should never reach that line. So let's focus on the first attempt to load it. Your screenshot says the file is blocked. Blocked by what?

BTW, a workaround is to load the `pdf.worker*.mjs` yourself. For instance, you can add a `<script>` tag to the `index.html`. However, that's not a good solution because it costs performance and because the version number of the file changes with every release.

**Comment by Jammy1299** [comment]
I have downgraded to version 18.1.14 and now Its working with my angular version 16.
Can we make it to work with version 19?
Also why this issue only coming in production but not in local.

**Comment by agrube** [comment]
Are you encountering an error that looks something like this?

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/1392839/569dc64d-dd26-4c13-a540-66c505cfc880)

If so, you're having a CORS issue on your production server that is blocking the worker file. Make sure your `workerSrc` is defined and specifies `'self'` so it doesn't attempt to fall back onto the `childSrc`.

**Comment by stephanrauh** [comment]
@Jammy1299 The issue happens in only production because you're using a different server in production. Usually, you also have a firewall and other security measures in production. When you say it works again after downgrading, you'll want to check whether your server has a problem with `*.mjs` files. On the other hand, that's unlikely because the other JavaScript files are loaded correctly.

**Comment by stephanrauh** [comment]
Did you manage to solve the issue?

**Comment by alpozgur** [comment]
Did you add .mjs to server mime/types as text/javascript
