### ISSUE TITLE
add signature panel in viewer to view signature information

### ISSUE THREAD

**Issue by insinfo** [stephanrauh/ngx-extended-pdf-viewer#2391]
### Feature description

add signature panel in viewer to view signature information like Certificate/PEM

![image](https://github.com/mozilla/pdf.js/assets/12227024/d8951231-3266-4b1e-bd05-e747eafb6799)

### Other PDF viewers

![image](https://github.com/mozilla/pdf.js/assets/12227024/c0605f2f-a53a-4874-a546-6d2d687815ae)

**Comment by stephanrauh** [comment]
As much as I'd love to do that - it's a great idea! - that's way beyond my skill set. I don't know anything about cryptography. I'd happily accept pull request - but then, this kind of features should be implemented in the base library, so every Firefox user benefits from it. I'd like to send you to https://github.com/mozilla/pdf.js/issues/. If you open a bug over there, make sure you're referring to Firefox, and don't mention my project. That's because the goal of the pdf.js project is to provide a viewer for Firefox. Nothing less and nothing more. They allow third-party users like me to do crazy stuff like embedding pdf.js as an Angular library - but that's not it's primary purpose, so they tend to refuse issues if they link to ngx-extended-pdf-viewer.
