### ISSUE TITLE
Support pdfjs legacy build

### ISSUE THREAD

**Issue by thanhchung06** [stephanrauh/ngx-extended-pdf-viewer#2401]
release 20.x move to pdf 4 which case error Promise.withResolvers is not supported when open by old android webview. 
As suggested by https://stackoverflow.com/questions/78415681/pdf-js-pdfjs-dist-promise-withresolvers-is-not-a-function, we should use legacy pdfjs.

Need an option to configure ngx-extended-pdf-viewer using pdfjs legacy build

**Comment by stephanrauh** [comment]
Please try `[forceUsingLegacyES5]="true"`. If that doesn't solve the issue, I'm afraid I have to ask you to downgrade until you find a compatible version. However, I don't support old versions, so there are no bugfixes. Neither are there security fixes. This is a leisure-time project, and there's never enough leisure time, so I have to focus on making the majority of users happy. I hate that - I want everyone to be happy! - but there's only so much a guy can do.

In theory, you can force my viewer to use a different version of pdf.js, such as the ones published by Mozilla. However, I doubt that works well because my custom build contains many customizations and bug fixes. I know several developers successfully did that, but there's no guarantee the native pdf.js build is going to work.

**Comment by stephanrauh** [comment]
BTW, this reminds me of this discussion: https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/2337#issuecomment-2197521395. I'm not entirely sure because I haven't tried it yet, but it should be possibly to polyfill `Promise.withResolvers()`.
