### ISSUE TITLE
Error Loading PDF Viewer on Azure App Service

### ISSUE THREAD

**Issue by rmdorsey** [stephanrauh/ngx-extended-pdf-viewer#2457]
This error is very similar to what's described here: https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/2176

The PDF viewer is displaying PDFs fine locally, but when it's deployed to production on Azure it's not displaying the PDF.  

I'm seeing this error in the browser console:
"Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec."
![image](https://github.com/user-attachments/assets/26f00168-039c-4cf4-92dd-4ad57712db96)

I've attempted to fix the issue by doing the following:
a) I've added this to my web.config file:
![image](https://github.com/user-attachments/assets/0ba5e904-9ee7-4aa2-954e-3e31068a2965)

b) I've added this to angular.json:
![image](https://github.com/user-attachments/assets/fdf24e53-4402-4073-9e37-35f6e1a9a498)

Thanks for all that you do!
Matt

**Comment by stephanrauh** [comment]
Just to be sure, have a look at the response when the browser if fetching the pdf*.mjs file. If there's an mistake with your `angular.json`, you'll see the `index.html` instead of the expected JavaScript file. 

If it's really a MIME type problem, have a look at https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/2196#issuecomment-2005853323. There seems to be a UI to configure the MIME types.

There's also a StackOverflow article, but I'm afraid it only adds to the confusion:
https://stackoverflow.com/questions/77780497/mime-type-of-mjs-file-from-azure-app-service-is-text-plain-only-in-productio

**Comment by stephanrauh** [comment]
If you've found a solution, would you mind to tell me so I can close the ticket?

**Comment by rmdorsey** [comment]
Still working to resolve this one.  I've got a thread going with Azure and will hopefully have a screen share session with them soon.  Here's the q&a I've got going: https://learn.microsoft.com/en-us/answers/questions/1840483/azure-app-service-is-failing-to-load-a-module-scri

**Comment by rmdorsey** [comment]
Azure support asked me to change the .mjs file to .js...  Is that possible?

**Comment by stephanrauh** [comment]
No, that's not possible. I already tried. There are several import statement I'd have to replace with something else, and it seems to be a lot of work.

BTW, mjs files aren't new, so I wonder why server manufacturer don't support them by default.

**Comment by stephanrauh** [comment]
The most elegant solution would be to import the *.mjs files in an Angular component. As far as I remember, we've already discussed this in #2337.

**Comment by rmdorsey** [comment]
I gave up on their app service (linux os), but I was able to get it working on their _**static**_ web app service.  Thanks!

**Comment by stephanrauh** [comment]
OK - that's slightly disappointing. I really hope there's a solution to the root problem. However, it seems you've found a solution, and that makes me happy!

Best regards,
Stephan

**Comment by bh3605** [comment]
If anyone stumbles along this issue and is using an Azure Web App, this web.config will work for you as it did for me. The `.mjs` and `.ftl` mappings will get you working.
```
<configuration>
    <system.webServer>
        <staticContent>
            <mimeMap fileExtension=".json" mimeType="application/json" />
            <mimeMap fileExtension=".importmap" mimeType="application/importmap+json" />
            <mimeMap fileExtension=".mjs" mimeType="application/javascript" />
            <mimeMap fileExtension=".ftl" mimeType="text/html" />
        </staticContent>
        <rewrite>
            <rules>
                <rule name="Main Rule" stopProcessing="true">
                    <match url=".*" />
                    <conditions logicalGrouping="MatchAll">
                        <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                    </conditions>
                    <action type="Rewrite" url="/" />
                </rule>
            </rules>
        </rewrite>
    </system.webServer>
</configuration>
```

**Comment by AboubakrNasef** [comment]
deploying on azure as  linux app service didn't work for me  because it completly ignores the web.config i didn't find any good way to get the mime types work 
so i've switched to azure static web site  then you can define the mime types as you want in the 
staticwebapp.config.json
////
  "mimeTypes": {
////
    ".mjs": "text/javascript",
////
  }
////

how can we add this to the docs so any body can use it in future

**Comment by stephanrauh** [comment]
@AboubakrNasef I've added a "Azure Static Web Apps" section to https://pdfviewer.net/extended-pdf-viewer/troubleshooting.
