### ISSUE TITLE
Missing icon: assets/images/annotation-paperclip.svg

### ISSUE THREAD

**Issue by cristicotet** [stephanrauh/ngx-extended-pdf-viewer#2486]
Icon available at the following address (missing from \ngx-extended-pdf-viewer\assets\images\)

https://mozilla.github.io/pdf.js/web/images/annotation-paperclip.svg

version affected: 21.1.0 (and older)

steps to reproduce: open PDF with attachments

**Comment by stephanrauh** [comment]
The icon isn't there because I've inlined it in the CSS code. I can see the paperclip in the showcase. Please navigate to https://pdfviewer.net/extended-pdf-viewer/two-way-binding, set the input field above the button to 3, click the button and compare your screen to both your application and to this screenshot. Is the paperclip missing?

<img width="1529" alt="image" src="https://github.com/user-attachments/assets/d30bf2a6-0765-4a25-b29f-f43b41963153">

**Comment by stephanrauh** [comment]
I wasn't aware of that feature. Fun fact: neither Apple Preview nor Google Chrome show the icon.

**Comment by stephanrauh** [comment]
Don't worry, I don't want to remove the feature. The only reason why I didn't support it is that I wasn't aware of it, so I didn't see any point in shipping images nobody's missing.

As for making requests to arbitrary resources - I don't see how this might happen, with the exception of JavaScript embedded with the PDF file. However, I'm not the export on this topic. Better reach out to the pdf.js team.

**Comment by stephanrauh** [comment]
Version 21.1.2 has just landed and solves the issue.

Enjoy!
Stephan
