### ISSUE TITLE
Search for word/phrase in TextLayer and return the relevant HTMLSpanElements

### ISSUE THREAD

**Issue by rmdorsey** [stephanrauh/ngx-extended-pdf-viewer#2488]
I'd like to be able to search for a word or phrase within the TextLayer and get back the relevant HTMLSpanElements so that I can modify their styling (such as giving them a highlight).  

I reviewed this page and see that your demo is looping through all span elements in the text layer and applying a highlight: https://pdfviewer.net/extended-pdf-viewer/textlayer

I've attempted to also loop through all span elements matching each one to the word/phrase I'm looking for, but I'm noticing that the majority of words within a phrase are split up and sometimes the words themselves are even split.  This makes doing a simple match very difficult.  Once I do find the phrase I'm looking for I then apply a style to it (similar to what you're doing on the demo page).  

I'd like a simple way to search for a phrase of words and to get the relevant TextLayer portion back so that I can modify the styling.

Thank you!

**Comment by stephanrauh** [comment]
I've implemented a prototype at https://pdfviewer.net/extended-pdf-viewer/find. At the moment, it's work in progress - the documentation is probably not good enough yet, but maybe you can guess my idea.

**Comment by stephanrauh** [comment]
Version 21.2.0 has landed. If I've understood you correctly, my solution is pretty close to your idea. I've added a secondary find controller that's only accessible via the API. You can select between the two find controllers using the attribute `useSecondaryFindcontroller`. The default controller influences the buttons and fields the users sees, the secondary find controller does not. And both add different CSS classes to the highlights.

Please note that I've modified the demo that modifies highlighted spans. The old demo was broken. Now there's a new (currently internal) event `renderedtextlayerhighlights` you can use. If this approach turns out to be useful, we can officially expose this event as an Angular attribute.
