### ISSUE TITLE
PDF Search Results based on words

### ISSUE THREAD

**Issue by NaivedyaMishra1** [stephanrauh/ngx-extended-pdf-viewer#2489]
Hi,

Could you please help me with below issue/feature.

When I search for a keyword in PDF viewer document with two words  for eg. 'Curb Weight' the keywords  should be highlighted when together or separate i.e. 'curb', ‘weight’, ‘weights', 'curb weight’.

Is there any way to implement the above, please let me know. Thanks

**Comment by stephanrauh** [comment]
Yes, that's possible. At the moment, the UI doesn't support this, but the programmatic API allows you to use regular expressions.

The tickets #2488 and #2339 deal with a refurbishment of the find functionality. Maybe I'll add the multi-word search to the UI again. I'm closing this ticket now because there are already two related tickets and because there's a partial solution.
