### ISSUE TITLE
Add support for any angle in Rotation for stamp annotations

### ISSUE THREAD

**Issue by Bharatvk** [stephanrauh/ngx-extended-pdf-viewer#2517]
```
export type StampEditorAnnotation = {
  annotationType: 13;
  pageIndex: number;
  bitmapUrl: string | Blob;
  rect: Array<number>; // [left, bottom, right, top]
  rotation: 0 | 90 | 180 | 270; // in degrees
};
```

Currently, in the above interface , the rotation parameter only accepts 0, 90, 180 and 360 degrees. it would be really helpful if we can pass 45 degrees or 60 degrees as an input for the rotated annotation

the pdf js express has a support for drag rotation, however its a paid library. 

Just wanted to check if this would be feasible in the future.

**Comment by stephanrauh** [comment]
I'm afraid that's no possible, at least not for me. If I'm not mistaken, the 90-degree-steps are baked in the pdf.js source code. Changing that would lead me in merge hell: updating to newer versions of pdf.js wouldn't be fun.

If ChatGPT is correct, the PDF format allows for arbitrary angles. So maybe that's something you can suggest to the pdf.js team. Please open a ticket here: https://github.com/mozilla/pdf.js/issues (and try to find a reason why this is something every Firefox user needs, because pdf.js is basically the project providing the native PDF viewer of Firefox).
