### ISSUE TITLE
Can I only upgrade to a newer version of pdfjs?

### ISSUE THREAD

**Issue by subhaneet-maitri** [stephanrauh/ngx-extended-pdf-viewer#2572]
I am currently using ngx-extended-pdf-viewer version 10 in angular 12.0.1. Currently I am not able to update to a newer version of angular. The issue I am facing is that some texts in my pdf are not showing in this version but works in newer version of this library. I verified that this is an issue with pdfjs. My inquiry is, can we upgrade just the pdfjs version to a newer version while keeping this base ngx-extended-pdf-viewer. 
I have tried changing the assets to use version 3.11 of pdfjs but it does not work and just shows the toolbar without any error. Is there a way to make pdfjs version 3.xx work with ngx-extended-pdf-viewer version 10?

**Comment by stephanrauh** [comment]
I suppose the answer consists of two parts:

- Where did you get the new version of pdf.js? If you're using the original pdf.js distribution of the Mozilla team, it might work, but some features are broken. I don't recommend that. It's better to extract the pdf.js files from a newer version of ngx-extended-pdf-viewer.
- Are there any error messages in the console or the network tab? My best guess is you've replaced the pdf.js files, but now they have different file names. You need to override `pdfDefaultOptions.getVersionSuffix` to fix that.

Even so, there's always a chance you run into compatibility problems. Every version of ngx-extended-pdf-viewer has been created with a particular version of my fork in mind. Updating usually works because I rarely implement breaking changes, but you never know. In particular, if you're updating from a major version of pdf.js to another major version, things will almost certainly break.

I hope that helps, even though I'm not as encouraging as I'd like to be!

Best regards,
Stephan

**Comment by subhaneet-maitri** [comment]
> I suppose the answer consists of two parts:
> 
>     * Where did you get the new version of pdf.js? If you're using the original pdf.js distribution of the Mozilla team, it might work, but some features are broken. I don't recommend that. It's better to extract the pdf.js files from a newer version of ngx-extended-pdf-viewer.
> 
>     * Are there any error messages in the console or the network tab? My best guess is you've replaced the pdf.js files, but now they have different file names. You need to override `pdfDefaultOptions.getVersionSuffix` to fix that.
> 
> 
> Even so, there's always a chance you run into compatibility problems. Every version of ngx-extended-pdf-viewer has been created with a particular version of my fork in mind. Updating usually works because I rarely implement breaking changes, but you never know. In particular, if you're updating from a major version of pdf.js to another major version, things will almost certainly break.
> 
> I hope that helps, even though I'm not as encouraging as I'd like to be!
> 
> Best regards, Stephan

Thank you for your response. 

1. I got the new pdfjs version from a CDN and replaced the pdfjs, viewer, worker and sandbox with the new versions. I will try with the newer pdfjs versions from the library itself.
2. There was no error messages in the console at all. It just showed the toolbar with some broken styles and a blank canvas which made debugging very difficult.

I was also considering creating a wrapper for pdfjs and implementing some of the functionality from the library but it might take a bit too long. 
I will just try to use a newer version of pdfjs from this library and hope it works.
