### ISSUE TITLE
simple demo doesn't work in Microsoft Edge :: Unable to load PDF file and viewer is broken

### ISSUE THREAD

**Issue by dhimanmohit2548** [stephanrauh/ngx-extended-pdf-viewer#261]
**Check this first**
- Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.htm?
**No**
- Does the bug also happen on https://pdfviewer.net/simple?
**Yes**

**Describe the bug**
The pdf viewer is broken in Microsoft Edge may be it is using the `viewer.js` insted of `viewer-es5.js`
I already tried to configure for microsoft Edge `defaultOptions.workerSrc = './assets/pdf.worker-es5.js';` but it didn't worked. Although the same thing works well in IE11.

**Version info**
- Version of ngx-extended-pdf-viewer: **3.0.0**
- Version of the JavaScript files pdf.js, pdf-worker.js and viewer.js (currently: default files vs. version 2.2 preview files)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Microsoft Edge
 - Version: Microsoft Edge 42.17134.1.0 Microsoft EdgeHTML 17.17134

**To Reproduce**
Try to open https://pdfviewer.net/simple in the Edge and you will see that the PDF is not loaded.

**Comment by stephanrauh** [comment]
Do you know when your Edge versions have been released?

Since January 15, 2020 Microsoft Edge is based on Chromium. So I'm reluctant to add additional logic for a browser that's soon to be replaced by a Chrome clone.

BTW, I'm pretty sure that even the old Edge doesn't need the ES5 files. I don't have a Windows PC. Can you give me a screenshot of the error message?

**Comment by dhimanmohit2548** [comment]
Stephan Rauh, thanks for providing prompt reply, much appreciated! 
I was able to solve this which I will list at the end but as asked by you I am attaching the screenshots below:

- after installing module and with no additional configuration
![Screenshot_9](https://user-images.githubusercontent.com/16471865/79430063-01f10600-7fe6-11ea-89f8-d9ed2e110bdc.png)

- here I configured the `defaultOptions.workerSrc = './assets/pdf.worker-es5.js';`
![Screenshot_10](https://user-images.githubusercontent.com/16471865/79430207-38c71c00-7fe6-11ea-84c8-ab968a1ced60.png)

- here with the previous configuration i.e `defaultOptions.workerSrc = './assets/pdf.worker-es5.js';` and adding the scripts in the angular.json file 
` "scripts": [
     "node_modules/ngx-extended-pdf-viewer/assets/pdf-es5.js",
    "node_modules/ngx-extended-pdf-viewer/assets/viewer-es5.js",
],`

 and it actually worked but some errors in the console :)

![image](https://user-images.githubusercontent.com/16471865/79434135-901bbb00-7feb-11ea-9a29-fe2eb400fab4.png)

Let me know further things you require, thanks!

**Comment by dhimanmohit2548** [comment]
how can I disable it then?

**Comment by stephanrauh** [comment]
You can't. I just wonder if that info help you to find a polyfill.

**Comment by stephanrauh** [comment]
@dhimanmohit2548 Your bugfix has landed with version 3.2.1. When you update, you can remove the special configuration in the `angular.json` and `defaultOptions`. Now Edge runs the same code as Internet Explorer (because there are many very old versions out there). I've also added a polyfill, so the warning you've reported should be a thing of the past.

Best regards,
Stephan

**Comment by dhimanmohit2548** [comment]
@stephanrauh Thanks for making the changes, you are a very active author I have ever met, much appreciated! Thanks!
