### ISSUE TITLE
Help: Advanced usage of the library or direct usage of the underlying pdfjs

### ISSUE THREAD

**Issue by Minecraftschurli** [stephanrauh/ngx-extended-pdf-viewer#2621]
I am currently using this library to implement a pdf viewer, now we need to implement a feature that requires us to either but additional elements between and next to pages or to use the underlying pdfjs instance to render the pages manually.

I already found this issue #606 but couldn't fugure out how to get access to the getDocument function.

Is there some feature in this library with which I can accomplish this task that I just didn't find in the docs or do I need to access pdfjs manually or even include my own copy of pdfjs to accomplish this?

**Comment by stephanrauh** [comment]
The way to access the low-level API has changed recently. Before version 20, you could simply access a global variable. The current version don't define this global variable. That's a good thing - less memory leaks, for example - but it also means you have to listen to a signal:

```ts
  private PDFViewerApplication!: IPDFViewerApplication | undefined;

  constructor(public notificationService: PDFNotificationService) {
    effect(() => {
      this.PDFViewerApplication = notificationService.onPDFJSInitSignal();
    });
  }
  ```
After receiving the signal, you can use `this.PDFViewerApplication` to access the low-level API of pdf.js.

Please keep in mind that this API changes every once in a while. The vast majority of the code is remarkably stable, but you never know which parts are modified without notice.

**Comment by agalper** [comment]
Is it possible to access pdfjs before the pdf viewer has been loaded with a document?

I would like to just query for how many pages are in a PDF, but the PDF is not loaded into the viewer. The onPDFJSInitSignal does not fire and thus this.PDFViewerApplication remains undefined.

What do you suggest?

**Comment by stephanrauh** [comment]
@agalper You can leave `[src]` empty (e.g. `undefined`). That allows you to use pdf.js before loading the document. 

But that doesn't solve your challenge: you want to retrieve information about the PDF file without loading it. That's not possible, because ngx-extended-pdf-viewer is about viewing PDF files. Everything else is a bonus.

If your application has a backend, you can easily solve the issue there. That requires an additional REST API call, but it's more efficient because you get rid of a lot of network traffic.
