### ISSUE TITLE
TypeError: Promise.allSettled is not a function

### ISSUE THREAD

**Issue by Prasanth-FrontendDeveloper** [stephanrauh/ngx-extended-pdf-viewer#263]
**Check this first**
- Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.htm?
- Does the bug also happen on https://pdfviewer.net/simple? **Yes**

**Describe the bug**
After loading the pdf file in ngx-extended-pdf-viewer it's showing an error in the console like **TypeError: Promise.allSettled is not a function**

**Version info**
- Version of ngx-extended-pdf-viewer - **3.0.0.**
- Version of the JavaScript files pdf.js, pdf-worker.js and viewer.js (currently: default files vs. version 2.2 preview files) - I have just added the scripts in angular.json.
**"scripts": [
              "node_modules/ngx-extended-pdf-viewer/assets/pdf.js",
              "node_modules/ngx-extended-pdf-viewer/assets/viewer.js",
              "node_modules/ngx-extended-pdf-viewer/assets/pdf.worker.js" ]**

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] - **Chrome**

**To Reproduce**
Can you provide a reproducer? That's a small and simple but complete project demonstrating the bug.

Otherwise, please tell me how to reproduce the behavior:

**Demo PDF file**
Many errors happen with specific PDF files only. So please add a PDF file (after checking the copyright of the PDF file first!)

**Screenshots**
![IMG_20200413_223128](https://user-images.githubusercontent.com/61708858/79351919-decb4580-7f56-11ea-9d82-bf028c150037.png)

**Additional context**

**Comment by stephanrauh** [comment]
Please update to a current version of zone.js. The old versions of zone.js are like a polyfill, just the other way round: they wrap functions like `Promise` in order to add additional features. Too bad it took some time to support the full range of modern ES2015 methods.

So all you need to do is to update to a modern version of zone.js. When I did that, the update went flawlessly.

**Comment by Hilaire-Bouaddi** [comment]
stephan is right ! Also `npm update zone.js` won't update zone.js to the most recent version. You actually have to specify a version name `npm update zone.js@0.10.3`

**Comment by jasonmonroe** [comment]
Still having a problem with ng2-pdf-viewer. I get this error when I upload pdfs:

pdf.js:7221 Uncaught (in promise) TypeError: Promise.allSettled is not a function
    at MessageHandler._deleteStreamController (pdf.js:7221)
    at MessageHandler._processStreamMessage (pdf.js:7160)
    at Worker.MessageHandler._onComObjOnMessage (pdf.js:6817)
    at ZoneDelegate../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Object.onInvokeTask (core.js:4736)
    at ZoneDelegate../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:422)
    at Zone../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:195)
    at ZoneTask../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:498)
    at invokeTask (zone.js:1744)
    at Worker.globalZoneAwareCallback (zone.js:1781)

**Comment by stephanrauh** [comment]
@jasonmonroe Did you add the polyfills? In particular, did you update to `zone.js 10.x`?

By the way, if you're interested in `ng2-pdf-viewer`, this is the wrong bugtracker.  :)

**Comment by jasonmonroe** [comment]
I gave up and removed it.  Decided to use the HTML5 <embed> tag instead. :(

**Comment by hengqu4** [comment]
![f3c4538a0893190a946c296f91c7373](https://user-images.githubusercontent.com/45166927/95989792-4e19e780-0e5d-11eb-9cdd-19332c6ff17c.png)
Uncaught (in promise) TypeError: Promise.allSettled is not a function
    at MessageHandler._deleteStreamController (message_handler.js:555)
    at MessageHandler._processStreamMessage (message_handler.js:489)
    at MessageHandler._onComObjOnMessage (message_handler.js:92)
_deleteStreamController @ message_handler.js:555
_processStreamMessage @ message_handler.js:489
MessageHandler._onComObjOnMessage @ message_handler.js:92
util.js:328 Warning: TT: undefined function: 3
2message_handler.js:555 Uncaught (in promise) TypeError: Promise.allSettled is not a function
    at MessageHandler._deleteStreamController (message_handler.js:555)
    at MessageHandler._processStreamMessage (message_handler.js:489)
    at Worker.MessageHandler._onComObjOnMessage (message_handler.js:92)

I have tried npm **update zone.js@0.10.3** , but it is still wrong

**Comment by hengqu4** [comment]
![d8b3f6df016c502832dfbe6db5d4b92](https://user-images.githubusercontent.com/45166927/95990706-6cccae00-0e5e-11eb-9da0-54be93872570.png)
In order to solve`Failed to load PDF file`,
I added `pdfjs.GlobalWorkerOptions.workerSrc = `https://cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;`

![f3c4538a0893190a946c296f91c7373](https://user-images.githubusercontent.com/45166927/95990525-37c05b80-0e5e-11eb-9d7d-490259e270a1.png)
I have tried `npm update zone.js@0.10.3` , but it is still wrong

**Comment by hengqu4** [comment]
![d8b3f6df016c502832dfbe6db5d4b92](https://user-images.githubusercontent.com/45166927/95990887-a69db480-0e5e-11eb-8713-426de3339c6c.png)
In order to solveFailed to load PDF file,
I added ```pdfjs.GlobalWorkerOptions.workerSrc = https://cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;```

I have tried `npm update zone.js@0.10.3` , but it is still wrong
![f3c4538a0893190a946c296f91c7373](https://user-images.githubusercontent.com/45166927/95990882-a43b5a80-0e5e-11eb-8a54-d15b751cdbc4.png)

**Comment by hengqu4** [comment]
In order to solveFailed to load PDF file,
![d8b3f6df016c502832dfbe6db5d4b92](https://user-images.githubusercontent.com/45166927/95990887-a69db480-0e5e-11eb-8713-426de3339c6c.png)
I added ```pdfjs.GlobalWorkerOptions.workerSrc = https://cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;```

I have tried `npm update zone.js@0.10.3` , but it is still wrong
![f3c4538a0893190a946c296f91c7373](https://user-images.githubusercontent.com/45166927/95990882-a43b5a80-0e5e-11eb-8a54-d15b751cdbc4.png)

**Comment by stephanrauh** [comment]
@hengqu4 This looks like Google Chrome. You say you're already using zone.js 0.10.3? Strange.

You can try to use the es5 versions of the files (i.e. `pdf-es5.min.js`, `pdf.worker-es5.min.js`, and `viewer-es5.min.js`.

BTW, if you're using ngx-extended-pdf-viewer, it's a bad idea to use the original pdf.js files from Cloudflare. I've modified the files from Mozilla, so you'll miss a couple of bug fixes and new features.

**Comment by Aslam97** [comment]
Installing `zone.js 0.11` nor `zone.js 0.10` doesn't solve the problem. as @stephanrauh said to use `es5`. so I changed this

```js
import * as pdfjsLib from 'pdfjs-dist/build/pdf';
pdfjsLib.GlobalWorkerOptions.workerSrc = 
   'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.7.570/pdf.worker.min.js';
```

to this

```js
import * as pdfjsLib from 'pdfjs-dist/es5/build/pdf';
pdfjsLib.GlobalWorkerOptions.workerSrc = 
   'https://cdn.jsdelivr.net/npm/pdfjs-dist@2.7.570/es5/build/pdf.worker.min.js';
```

and the error gone.

but when I try what you said **it's a bad idea to use the original pdf.js files from Cloudflare**. I decided to change workerSrc from **CDN** to **pdfjs-dist** and got this warning message **Warning: Setting up fake worker**
