### ISSUE TITLE
Changing Zoom Level causes Page Change if previous Page still partly visible (custom toolbar)

### ISSUE THREAD

**Issue by jontze** [stephanrauh/ngx-extended-pdf-viewer#2637]
This bug only appears when using a custom toolbar. The custom toolbar interacts programmatically with the `input` and `outputs` of the `ngx-extended-pdf-viewer` component to change the zoom level or change the page. The bug doesn't appear with the default toolbar that comes with the PDF viewer.

I created an example application that can be used to reproduce the bug: [jontze/ngx-extended-pdf-viewer-scroll-on-zoom-bug](https://github.com/jontze/ngx-extended-pdf-viewer-scroll-on-zoom-bug)

**Version info**
- Discovered on `21.3.8`
- Also reproducible on `22.0.0-alpha.5`

**Reproduction Steps**
1. Subscribe to changes to the `pageChange` output event
2. Scroll to another side of the PDF (e.g. 3, 4, ...) but so that the previous page is still slightly visible at the top of the PDF viewer (screenshots below)
3. Now set the zoom level programmatically via the `zoom` input property

_You can check the example application for further details._

**Expected behaviour**
- PDF viewer should zoom the current view (e.g. in/out)
- `pageChange` event should not emit as only the zoom was changed

**Actual behaviour**
- PDF viewer zooms in/out according to the zoom level
- `pageChange` output event emits two times quickly after another. First time with the previous page number (the one that was partly still visible at the top of the PDF viewer) and the second time with the current page number

**Demo PDF file**
I used the PDF file that comes with the library installation via `ng add`: https://github.com/jontze/ngx-extended-pdf-viewer-scroll-on-zoom-bug/blob/main/public/assets/pdfs/Bootstrap-vs-Material-Design-vs-Prime-vs-Tailwind.pdf 

**Screenshots**
The previous site of the pdf is still visible at the top. There's a custom toolbar on top of the pdf viewer. The `page` state is reported as the second page.
![image](https://github.com/user-attachments/assets/9dc5f21d-2556-4cf5-ae49-852cedb117e5)

After we clicked on the zoom button in the custom toolbar, the `pageChange` event emits beside the changed zoom level and therefore we jump to the beginning of the first page.
![image](https://github.com/user-attachments/assets/5f0f3409-d150-4b77-aaa8-453335650085)

---

**Possible Solutions and Workarounds**

I think this might be just a timing issue. As the component emits two pageChange events quickly after another (about 10ms apart). The first one with the previous page and the second one with the current page. To workaround this I was actually able to read the correct page number via the `NgxExtendedPdfViewerService` on every emitted page change event with a mimimal delay and like this ignore the returned `page` that the `pageChange` output emitted:

```ts
 // Called on every emittion of the `pageChange` output
 onPageChange(pageNumber: number) {
    console.debug("NgxExtendedPdfViewer: PageChange ", pageNumber)
     // Workaround
     setTimeout(() => {
      const pageFromSerivce = this.pdfService.currentPageIndex(); // NgxExtendedPdfViewerService
      if(pageFromSerivce != null) {
        // This component signal state to keep the page number in the custom toolbar in sync with the page in the PdfViewer
        this.pdfCurrentPage.set(pageFromSerivce + 1)
       }
     }, 0)
  }
```

This might be related to one of these issues:
- https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/595 (closed as no reproducible example was given)
- https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/573 (looks like the same behaviour but for the built-in toolbar, maybe this just needs to be adjusted to also work with custom toolbars as well?)

---

Thanks for your effort on this project! ❤️

**Comment by stephanrauh** [comment]
The custom toolbar has nothing to do with it. I've been able to reproduce the bug even after deleting the custom toolbar.

The culprit is the combination of
```html
(pageChange)="onPageChange($event)"
```
and
```ts
onPageChange(pageNumber: number) {
    this.pdfCurrentPage.set(pageNumber);
}
```

The event `(pageChange)` is called when the page number is already changing. For example, it's called when the user scrolls. The general idea is to update the page number if you're exactly between the two pages. In your case, multiple pages are shown simultaneously, so the algorithm is confused and updates the page number a bit early.

For some reason, `(pageChange)` is also triggered when the zoom level changes. Now, your event listener `(pageChange)` updates the page number - and that seems to trigger unexpected side effects. If you update the page number via `[page]`, and the page number differs from the previous page number, the viewer scrolls to the top of the page. That's basically what you're observing.

What I can't explain is why the viewer jumps to the previous page. I assume that's a complicated interference caused by changing the page number and the zoom level simultaneously. A large part of these algorithms runs asynchronously, so surprises are to be expected. And it explains why your workaround works.

Cutting a long story short: just drop the event listener `(pageChange)="onPageChange($event)"`. You don't need it. If you need it for some reason, make sure you don't update `[page]` when processing `(pageChange)`.

**Comment by stephanrauh** [comment]
By the way, thanks a lot for providing the reproducer and for investing a lot of research before submitting the ticket! That helps me to understand the problem quickly.

**Comment by jontze** [comment]
Thanks for taking such a detailed look! @stephanrauh 

> Cutting a long story short: just drop the event listener (pageChange)="onPageChange($event)". You don't need it. If you need it for some reason, make sure you don't update [page] when processing (pageChange).

My problem is that I my custom toolbar also offers support for pagination and that's why I need to ensure that the displayed current page in the custom toolbar is always in sync with the current page of the pdf viewer. That's why I need to listen to the `pageChange` event listener to get page updates.

---

With your hints I dived a little bit deeper and found something interesting. The `pageChange` event seems to be called outside of the angular change detection cycle.

I created another branch on the reproducer repo to showcase this ( https://github.com/jontze/ngx-extended-pdf-viewer-scroll-on-zoom-bug/tree/regular-angular-change-detection ). Without usage of the OnPush ChangeDetection and Signals you'll get the infamous "Expression has changed after it was checked"-Error (https://angular.dev/errors/NG0100), if you follow the reproduction of the steps as before.

Therefore, I could fix both variants of the reproducer (regular ChangeDetection without Signals and OnPush ChangeDetection with Signals) by calling the ChangeDetection manually at the end of the callback assigned to the `pageChange` event.

```ts
 onPageChange(pageNumber: number) {
  // ...
 // this.pdfCurrentPage = pageNumber; OR
 // this.pdfCurrentPage.set(pageNumber);
  this.cd.detectChanges();
}
```

However, I can still see two emissions of the `pageChange` event:
```
NgxExtendedPdfViewer: PageChange  1 <-- Called inside ChangeDetection (?)
NgxExtendedPdfViewer: PageChange  2 <-- Seems to be called outside ChangeDetection (NG0100 Error), unless detectChanges() is called manually
```
---

**Suggestions**

I could imagine that this behaviour might be fixed by ensuring that all sources that can emit the `pageChange`  inform the ChangeDetection about this. Possible where the binding between pdf.js and the Angular Wrapper happens.  However, still not sure about the first emission. 🤔

**Comment by stephanrauh** [comment]
It's called without Angular noticing? Strange. I was sure my implementation is fail-safe:

```ts
    PDFViewerApplication.eventBus.on('pagechanging', (x: PageNumberChange) => {
      if (!this.pdfScriptLoaderService.shuttingDown) {
        // hurried users sometimes reload the PDF before it has finished initializing
        this.ngZone.run(() => {
          const currentPage = PDFViewerApplication.pdfViewer.currentPageNumber;
          const currentPageLabel = PDFViewerApplication.pdfViewer.currentPageLabel;

          if (currentPage !== this.page) {
            this.pageChange.emit(currentPage);
          }
          if (currentPageLabel !== this.pageLabel) {
            this.pageLabelChange.emit(currentPageLabel);
          }
        });
      }
    });
```

I have to modify it in order to support zone-less application, but that's another day's story.

**Comment by stephanrauh** [comment]
I suspect the problem is still the combination of
```html
(pageChange)="onPageChange($event)"
```
and
```ts
 onPageChange(pageNumber: number) {
    this.pdfCurrentPage = pageNumber;
}
```
The `(pageChange)` event is triggered when the page changes. `this.pdfCurrentPage=pageNumber` changes the page. This, in turn, triggers `(pageChange)`, which calls `this.pdfCurrentPage=pageNumber`, which - well, you get the idea. It's an infinite loop. You only get away with it because the event is only triggered if the new page number differs from the old one.

In most cases, this approach works well. However, when you're changing the zoom level, that also has an impact on page numbers - and it's asynchronous code, so it's possible that events are processed in the wrong order. That may result in the "Expression has changed after it was checked" error we all love.

**Comment by jontze** [comment]
> In most cases, this approach works well. However, when you're changing the zoom level, that also has an impact on page numbers - and it's asynchronous code, so it's possible that events are processed in the wrong order. That may result in the "Expression has changed after it was checked" error we all love.

Yeah, totally agree on that. Since we just wrap around the `pagechanging` event from pdf.js in this library, the falsy emission of the previous page number after setting the zoom programmatically would need to be fixed in pdf.js to resolve this behaviour.

Thanks for the exchange @stephanrauh ! It really helped me to investigate the root cause further.  😄

**Comment by shaikh-taheer** [comment]
i am facing this 

<img width="1888" height="693" alt="Image" src="https://github.com/user-attachments/assets/5569b28b-5a39-48b8-9e6c-d039e495f8b3" />

<img width="1898" height="462" alt="Image" src="https://github.com/user-attachments/assets/e3b8335c-93b6-4e0c-ad7a-816cf682ba72" /> ui breaking in the dev environment and working fine
in the local what could be the issue here how to resolve this?

-- please focus on the page number
