### ISSUE TITLE
Make range requests load all the data

### ISSUE THREAD

**Issue by subhaneet-maitri** [stephanrauh/ngx-extended-pdf-viewer#2682]
Hi, currently in our application we are using ngx-extended-pdf-viewer verion 10.0.0. We are using range requests and it works like we need for the most part, but we have one issue where the range request stops loading new data until the user has scrolled to the last loaded pages and then it resumes loading again. Is there any way we can make it so the library continues loading the pages regardless of if the user has scrolled? Any help will be much appreciated, thanks.

**Comment by stephanrauh** [comment]
It may be an issue for your application - but that's precisely the intended behavior. The idea is there's no point in reading pages the user never reads. Maybe they stop reading after page 1, so why should the PDF viewer load page 999?

The viewer uses caching for rendering. It renders a couple of pages in advance. Most readers read the document linearly, so that's usually a good guess. I'm not entirely sure, but I guess the range requests match the pre-rendering strategy. More to the point, they're cause by pre-rendering.

Maybe https://pdfviewer.net/extended-pdf-viewer/prerendering give you additional insight on the topic.

The PDF viewer also supports streaming, which seems to be an alternative to range request. Unfortunately, I don't know what streaming does, precisely, and whether it's an alternative or an addition to range requests.
