### ISSUE TITLE
Don't see the pdf in iOS devices.

### ISSUE THREAD

**Issue by sergiio-sjr** [stephanrauh/ngx-extended-pdf-viewer#2685]
I am developing an application in Ionic, and this application has the plugin ngx-extended-pdf-viewer implemented. The application receives a PDF and displays it; however, in iOS versions earlier than 17, it is not displayed. The plugin remains gray and does not show the PDF. This issue does not occur on Android devices or more recent versions of iOS. Additionally, I have debugged the error in the console and have only obtained the following information: TypeError: Promise.withResolvers is not a function. (In 'Promise.withResolvers ()', 'Promise .withResolvers' is undefined)

**Version info**
- Version of ngx-extended-pdf-viewer: 21.4.0 (Also in other versions)

**Comment by luke-rogers** [comment]
Settings `pdfDefaultOptions.needsES5 = true;` and passing `[forceUsingLegacyES5]="true"` into the component should solve this.

**Comment by stephanrauh** [comment]
I think it suffices to set the attribute `[forceUsingLegacyES5]="true"`. In version 19 and 20 (or so) I'd accidentally deleted the attribute, so the only option was using `pdfDefaultOptions.needsES5="true"`, but now the attribute is back.

I don't understand why iOS causes so much trouble with `Promise.withResolvers()`. I've added code that detects whether this function is supported or not, but my browser switch doesn't work reliably.

I'll close this ticket because I believe Luke's hint solves your issue. If not, don't hesitate to tell me.
