### ISSUE TITLE
Text layer DOM formatting

### ISSUE THREAD

**Issue by rachanamaria** [stephanrauh/ngx-extended-pdf-viewer#282]
I am trying to search the content of the text layer through DOM using selector **$('div.textLayer').textContent**, the content is coming mixed like eg: "**ABC Corporation LtdThis is the company name**", in the HTML page it has ` <span>ABC Corporation Ltd</span><span>This is the company name</span>. `
So the HTML page rendered looks like **ABC Corporation Ltd This is the company name**, `space is added in the page.`

So, when i try to find **ABC Corporation Ltd** it is not finding any matches.
So, while creating the div.textLayer with all the spans , add a new line before every span element.
This will not affect the view in the HTML page.
**_For html without formatting_**
```
<html>
<div> this is a div</div><div>this is another div</div>
</html>.

```
![image](https://user-images.githubusercontent.com/35720010/80307761-c70e7f80-87e8-11ea-9c57-4f2097ed4455.png)

<hr />

**_For html with formatting_**
```
<html>
<div> this is a div</div>
<div>this is another div</div>
</html>.

```
![image](https://user-images.githubusercontent.com/35720010/80307779-e2798a80-87e8-11ea-925c-9db24c6b2591.png)

**Comment by stephanrauh** [comment]
@timvandermeij I think that's your domain. How do you like the idea? Is it a good idea to add a carriage return between the `<span>`s of the textlayer?

@rachanamaria I'd suggest using `innerHtml` instead of `textContent`. You can get rid of the `<span>`s with a clever regular expression and `replaceAll()`. Something along this line:

```
const rawText = $('div.textLayer').innerHtml
                                                          .split("</span>")
                                                          .join("\n")
                                                         .replaceAll(/<span(.*)>/, ''); // the regex need some refinement
```

**Comment by timvandermeij** [comment]
PDF.js switched from `div` to `span` to avoid unnecessary newlines when copy/pasting text; see https://github.com/mozilla/pdf.js/pull/10197#issuecomment-439698939 for the patch and its result. However, it's not perfect and in fact text selection for PDF files is _very_ complicated to get right, contrary to what one might expect. This is because text is not represented in PDF files as actual text, but instead as absolutely positioned glyphs, meaning that PDF.js needs to have heuristics to determine where to put spaces for text selection and where not, which often goes wrong. In fact, most open issues for PDF.js are related to text selection; see https://github.com/mozilla/pdf.js/labels?sort=count-desc.

I'm not an expert on text selection so I can't say for sure, but I don't think a carriage return would be a problem in this case.

**Comment by stephanrauh** [comment]
@rachanamaria I suggest using the workaround. Does this work for you?
