### ISSUE TITLE
Customizing color, icons, other download types

### ISSUE THREAD

**Issue by avarndell** [stephanrauh/ngx-extended-pdf-viewer#32]
Is there a way to change the icon and icone size and add the ability to download as csv?

**Comment by stephanrauh** [comment]
That's three questions. :)

1) How to change the icons: have a look at the CSS file. For example, there's the download icon. There's a CSS rule for that:
```CSS
.secondaryToolbarButton.download::before {
    content: url('data:image/png;base64,...');
  }
```
You can override this rule in your own CSS file. 

2) Icon size: that's a bit more difficult, because increasing the icons automatically requires you to push down the PDF file. Apart from that, it's a simple application of CSS again.

3) Download as CSV: I'm awfully sorry, that's not possible. We're talking about PDF files. CSV downloads are useful for files with a simple structure, such as Excel files. PDF files can be anything, including books with a lot of illustrations. And I doubt there's a useful way to convert the, say, Gutenberg bible to a CSV file.

I'll close the ticket for now. Don't hesitate to answer if there's still an open question. I'm still listening, even if the ticket is closed.

**Comment by stephanrauh** [comment]
@MathDad69 Sure. I tried to answer your question in #2723. If it doesn't answer your questions, don't hesitate to ask (and do it over there, that's easier for all of us).

**Comment by stephanrauh** [comment]
Anyone who's reading this: since version 20 (give or take a few), toolbar buttons are rendered differently. In previous versions, you could modify them using CSS, but nowadays, it's baked into a dedicated Angular component for every toolbar button and menu item. See the documentation at https://pdfviewer.net/extended-pdf-viewer/customization and the discussion at #2723.
