### ISSUE TITLE
Filename for download

### ISSUE THREAD

**Issue by dadepra** [stephanrauh/ngx-extended-pdf-viewer#35]
Hi Stephan how I can define the filename when user click over download button? Now is always using document.pdf

**Comment by stephanrauh** [comment]
@dadepra Dieison, please apologize my delayed response. I've been moving to another town, and that project soaked all my available resources like nothing good.

"download.pdf" is a fallback kicking in if there's no URL. If the `[src]` attribute is a simple string, the filename is derived from the URL.

I can only guess. Do you display your PDF file from a blob or a REST service?

**Comment by stephanrauh** [comment]
OK, you won't answer me, so I'll proceed as best as I can without your guidance. Sigh!

Brainstorming:
- If the PDF viewer is used in non-embedded mode, the URL also determines the browser window title.
- I don't want to call the new attribute `filename`because that might be confused with `[src]`. Maybe `downloadFilename`is both intuitive and non-confusing?

**Comment by stephanrauh** [comment]
Since version 0.9.19, there's a new attribute called `[filenameForDownload]`.

**Comment by ChangAlanCL** [comment]
> Since version 0.9.19, there's a new attribute called `[filenameForDownload]`.

very glad I found this. only if native chrome pdf download could be this easy.
