### ISSUE TITLE
Github README and releases should match what is seen on npmjs.com

### ISSUE THREAD

**Issue by JWess** [stephanrauh/ngx-extended-pdf-viewer#36]
It would be nice if Github's README had all the helpful information from the NPM README. Can they not be one and the same?

Also, why not have your releases and changelog managed in Github?

**Comment by stephanrauh** [comment]
As for the README: Let me ponder about that. You're mostly right. The GitHub project also contains a test project. That's why there are two different README file. But that shouldn't be the user's concern. I guess I'll merge the README files after a good night's sleep. :)

As for the releases: you're right. I just didn't think about this. Consider it done with the next release!

**Comment by stephanrauh** [comment]
There are two README files and no easy way to change that. So now the root README file points to the npm README file. That should avoid any confusion in future.
