### ISSUE TITLE
Zoombar for smaller screensize device.

### ISSUE THREAD

**Issue by mukeshrawat02** [stephanrauh/ngx-extended-pdf-viewer#370]
I have a requirement to customise the toolbar and adding the close button and pdf title in the bar itself. This is done using your https://pdfviewer.net/custom-toolbar which I found very helpful. But now the problem is I want to show the zoombar at the bottom for mobile. I cannot see any option to create a footer where I can add `<pdf-zoom-toolbar ></pdf-zoom-toolbar>` in your documentation. 

I just wanted to check, is this can be done? I am attaching the screenshot which I am trying to achieve. So far I am able to done the header part. 

<img width="269" alt="Screen Shot 2020-06-27 at 23 27 59" src="https://user-images.githubusercontent.com/3429202/85933426-bd7bc380-b8ce-11ea-92e9-e0898061cdf0.png">

**Comment by stephanrauh** [comment]
I suppose you can achieve this with a clever CSS rule. But that might be difficult because the zoom bar is always part of the toolbar, so you can push the zoom bar to the bottom of the toolbar, but not to the bottom of the surrounding div. You might circumvent this using JavaScript, e.g. a combination of `@HostListener('window:resize', ['$event'])` and `(pdfLoaded)`. The idea being the JavaScript sets `position:absolute` and calculates the height of the window so it can set the CSS inline style like `top: 245px`.

In a future version I can make the entire HTML file configurable. It just never crossed my mind somebody might want to do such a radical change. But sure, why not!

**Comment by stephanrauh** [comment]
Your feature has landed with version 4.1.0. I've added a live demo at https://pdfviewer.net/custom-toolbar (select "floating zoombar").

Enjoy!
Stephan
