### ISSUE TITLE
PDF not Loading in Microsoft edge

### ISSUE THREAD

**Issue by bhawin-boom** [stephanrauh/ngx-extended-pdf-viewer#371]
**Check this first**
The project is a wrapper around Mozilla's PDF viewer, so maybe your bug is caused by the base library. Please check this first by answering these three questions:
- Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.htm? (If so, please open the issue at Mozilla's bugtracker).
- Does the bug also happen on https://pdfviewer.net/simple?
- Can you write a reproducer based on this template project? https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/master/template

**Describe the bug**
I have implemented this plugin in my local system and the plugin is working like a charm in all the browsers except Microsoft Edge .
![image](https://user-images.githubusercontent.com/3766507/85958962-25a5d480-b9b7-11ea-8b86-b672fa038fb8.png)

**Version info**
- Version of ngx-extended-pdf-viewer
Pdfjs version : 2.6.48

**Desktop (please complete the following information):**
 - Browser [basically Internet Explorer, Edge, or any other browser]
Microsoft Edge
![image](https://user-images.githubusercontent.com/3766507/85959037-5e45ae00-b9b7-11ea-8792-277aedaad7f2.png)

**To Reproduce**
I Took the plugin from Github and started implementing in my app
   _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 8.1.3
Node: 12.14.0
OS: win32 x64
Angular: 8.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.3
@angular-devkit/build-angular     0.801.3
@angular-devkit/build-optimizer   0.801.3
@angular-devkit/build-webpack     0.801.3
@angular-devkit/core              8.1.3
@angular-devkit/schematics        8.1.3
@ngtools/webpack                  8.1.3
@schematics/angular               8.1.3
@schematics/update                0.801.3
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.35.2

If you really can't provide me a reproducer, please tell me how to reproduce the behavior:
God to Microsoft Edge , open the viewer with the pdf present on my local assets folder.

**Screenshots**
![image](https://user-images.githubusercontent.com/3766507/85959123-02c7f000-b9b8-11ea-8e1c-dca7d31b44c3.png)
![image](https://user-images.githubusercontent.com/3766507/85959172-605c3c80-b9b8-11ea-8abf-c98ac3bd47be.png)

**Thank you!**
I know from experience how much work filling a form like this is. It's always tedious and annoying. But it helps me to focus on the important points and to speed up development. So thank you very much for your understanding and your patience!

**Comment by stephanrauh** [comment]
Maybe Edge doesn't cope with the JavaScript files. Can you check whether pdf.js or pdf-es5.js is loaded, please?

I've modified the viewer recently so it always loads the es5 files with Edge - but maybe the browser detection isn't reliable enough yet.

Thanks in advance,
Stephan

**Comment by bhawin-boom** [comment]
Hi @stephanrauh ,

I can cnofirm on myside that pdf-es5.js is loading .

I have debuggedthe issue more further and got out that,
![image](https://user-images.githubusercontent.com/3766507/86133244-aa066d80-bb05-11ea-8a11-0391482c265c.png)

window.PDFViewerApplicationOptions = pdfjsWebAppOptions.AppOptions;

![image](https://user-images.githubusercontent.com/3766507/86133298-b985b680-bb05-11ea-9bfc-fb7274b182be.png)


Seems like the appOptions is not getting loaded.

**Comment by stephanrauh** [comment]
That's entirely unexpected. This week, I'm busy doing other things, but I'm positive I can work on your issue next week. Can you send me a reproducer? A little program based on https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/master/template?

Thanks in advance,
Stephan

**Comment by bhawin-boom** [comment]
Ok,I will do that in sometime , but ,just to let you know that this error is occurring in Microsoft edge version <= 40 .
Above version 40 ,its flowing  like butter .

**Comment by donovan-duplessis** [comment]
Hi Stephan,

I can confirm that I am experiencing this error in IE 11 too (exact same as the screenshot bhawin-boom posted.  We are using 4.0.0-alpha.5.

Regards,
Donovan

**Comment by stephanrauh** [comment]
That's good news, because I can run a test with IE11. I've tried the entire showcase. No error. Can you send me a reproducer?

**Comment by stephanrauh** [comment]
@donovan-duplessis Can you tell me the precise error message? The screenshot above only shows a higher-level exception, but the root cause is collapsed.

**Comment by donovan-duplessis** [comment]
@stephanrauh Hi, sorry for the late response.  I don't have the exception on-hand, I had the same error as the initial screenshot from @bhawin-boom .  The problem is I am on a Mac and rarely get access to the IE browser.  I will try and see if I can spawn up a VM to test in IE 11.  What I did do is then immediately revert back to v3.7.2 and everything worked again in IE as it should.

**Comment by donovan-duplessis** [comment]
@stephanrauh Hey Stephan.  I think I may have given you the run-around here.  I just managed to download the IE 11 + Edge VM from [https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) and installed 4.0.0-alpha.9, and everything is working 100% in IE.  I am not sure what then happened originally, apologies.

I have taken a screenshot of the IE 11 console output for you, there is a warning about #find_fuzzy, I am not sure if that is intentional.

[https://www.dropbox.com/s/hkz8ry2lm6oqjjx/Screenshot%202020-07-06%20at%2016.55.17.png?dl=0](https://www.dropbox.com/s/hkz8ry2lm6oqjjx/Screenshot%202020-07-06%20at%2016.55.17.png?dl=0)

Cheers and thanks for a great library,
Donovan

**Comment by stephanrauh** [comment]
> The problem is I am on a Mac and rarely get access to the IE browser.

Same here... I feel your pain! Running the VM is an option, but it's sluggish, so it's a pain, too - at least on my good old 2015 MacBook.

As for the #find_fuzzy message: you're right, I should do something about it, at least in the few languages I speak fluently enough. Thanks for reminding me!

**Comment by stephanrauh** [comment]
I'm closing the ticket now because I don't know how to reproduce it. I assume MS Edge is one of the evergreen browsers that are updated frequently, so I believe I get away ignoring the old versions. If you're stuck with on old MS Edge version, you should talk to your IT department and tell them about security risks. I'd even do that for you. :)
