### ISSUE TITLE
How to make the PDF blurred when the user has hit a paywall and don't want to show the PDF content?

### ISSUE THREAD

**Issue by dschmitt-fc** [stephanrauh/ngx-extended-pdf-viewer#384]
**Is your feature request related to a problem? Please describe.**
On certain sites, when a user is viewing a document that requires a paid subscription, the site will blur the PDF and show a modal telling them to get access (the paywall). Here is an example: 
![image](https://user-images.githubusercontent.com/55400391/86362493-5ac65700-bc43-11ea-9370-e770e5487152.png)

**Describe the solution you'd like**
This is probably outside the scope of this library so please feel free to close/ignore this, but I am wondering if you know of a way to make this happen. I have searched Stack Overflow, pdf.js API, and other resources, but I can't find anything about how this is done. The example screenshot above also has the PDF display the first page without blur and blurs all pages after (ideal implementation). Most results when I search this talk about how the PDF looks blurry which is unrelated to what I'm trying to implement. I know it can't just be a simple CSS implementation because you could just remove that in dev tools.

**Comment by dschmitt-fc** [comment]
After doing more research it seems like if I want to do something like this I'll have to convert the PDF text on the backend before serving it to the client and so it's out of the scope of this library. Sorry!

**Comment by stephanrauh** [comment]
You've piqued my curiosity. As much as I hate paywalls, it's an interesting technical challenge. You about this?

```CSS
p.blur-text {
   filter: blur(5px);
   user-select: none;
   pointer-events: none;
}
```

https://www.frontendhero.dev/tutorial/blurred-paywall-area/

**Comment by dschmitt-fc** [comment]
@stephanrauh I'm not a fan of paywalls either but it's something I have to implement :) Thanks for responding and linking the tutorial! I don't know why I couldn't find something like that. Using those CSS properties is sort of what I imagined as the easiest implementation, but couldn't a user just delete the CSS class to remove the blur and get around the paywall? 

I inspected the page from which I got the screenshot (https://www.scribd.com/document/243696124/1-Co-v-the-Deportation-Board). It looks like it serves a single HTML document. When the user has access, the entire document content is in the HTML responses. When there is a paywall, there is a script for each page of the document that sets whether the page is blurred or not (sets blurred to false for first page and true for the rest), then I guess it somehow fetches server generated HTML to show just the first page and blur the rest, but I can't figure out how.

Right now I make an API request to fetch the document as a blob and put it in the `ngx-extended-pdf-viewer` element src, but I think I have to find a node.js library to help do some server side processing if I want a blurred PDF.

**Comment by stephanrauh** [comment]
Yes, you're right. People like me are pretty adept in removing the offending CSS code. That's why the paywall-protected site have begun to deliver only a fraction of the page to the client.

Mind you: no matter what you do, after sending the PDF file to the client, you've given up control over it. You can make it difficult to access it. That protects you from the average script kiddie. In most cases, that's good enough. But if you really want to protect your intellectual property, you just have to sit on until until the customer pays. In other words: you need a server-side solution.

Some time ago, I searched for npm packages doing just that. As far as I remember, it's easy to use a library to deliver the first page of the PDF file. I didn't search for Java solutions, but I guess there's a library matching your use case, too.
