### ISSUE TITLE
Styles from the library being applied globally to the application which uses it

### ISSUE THREAD

**Issue by rjs-picturepark** [stephanrauh/ngx-extended-pdf-viewer#435]
**Describe the bug**

Some of the styles from this library are being applied globally to any application that uses it, namely the styles from these files are an example.

ngx-extended-pdf-viewer.component.css: https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/916d003fbe66ef541840518a0d14116c32219a6d/projects/ngx-extended-pdf-viewer/src/lib/ngx-extended-pdf-viewer.component.css

viewer-with-images: https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/916d003fbe66ef541840518a0d14116c32219a6d/projects/ngx-extended-pdf-viewer/src/lib/viewer-with-images.css

I checked and the bug is happening on https://pdfviewer.net/simple

It seems to me that the issue is due to an incorrect usage of the ViewEncapsulation none.
https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/916d003fbe66ef541840518a0d14116c32219a6d/projects/ngx-extended-pdf-viewer/src/lib/ngx-extended-pdf-viewer.component.ts#L57

Using view encapsulation none will cause the contents of both the above mentioned files to be added directly to the header of the document, thus overriding the css of the entire application 

**Version info**
- Version: 4.1.0

**Desktop**
 - Browser: Chrome 84.0.4147.125
 

**To Reproduce**
In order to check the issue inspect the body tag which has the ".body" class and verify that the styles being applied to that class will be the styles present in https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/916d003fbe66ef541840518a0d14116c32219a6d/projects/ngx-extended-pdf-viewer/src/lib/viewer-with-images.css#L422-L427

Reproducible repo: https://github.com/rjs-picturepark/Issue_435

**Screenshots**

Without the body class on the body tag. 
![image](https://user-images.githubusercontent.com/58807904/90264652-50ee6100-de49-11ea-9fe0-3eda9031ef66.png)

With the body class on the body tag. 
![image](https://user-images.githubusercontent.com/58807904/90264727-6c596c00-de49-11ea-8122-fbc2ec7f1ee4.png)

**Comment by stephanrauh** [comment]
That's true. When I started the project, it was a deliberate design design. It made sense at the time. But you're right, now I could embrace local CSS. It's just that it's a lot of tedious work.

So I'd like to ask you if that's a serious problem to you? When starting the project, I've introduced CSS classes like `.body´ and `.html` because it seemed unlikely someone else uses the same classes.

**Comment by rjs-picturepark** [comment]
The problem aren't those classes in specific, in my case it's the thumbnail classed that are interfering with the styles of the project, but those are just the ones i noticed and it's in the early stages of the project which will only increase in size.
There is an alternative to the tedious work of scoping all the css to the correct places, you can keep the view encapsulation as is and scope it directly to a class or an id. 

encase all of the library html in a class like so ".ngx-extended-pdf-viewer" then make it that all the global css is under that class, .ngx-extended-pdf-viewer { global css... }. This way you escape the work of scoping everything correctly but keep the functionality of the global css being only global to the library itself.

**Comment by stephanrauh** [comment]
Yes, maybe that's what I should do. In any case, it's a good strategy! I'm slighly worried because it's a breaking change (someone out there may rely on the CSS classes I've defined), but semantic versioning give me a loophole. I'll probably get away with it by increasing the major version number.

Let me ponder about it a night or two! :)

**Comment by rjs-picturepark** [comment]
Hello just wanted to check if there were any development on this issue and or if you decided that it should be fixed or not. 
If it is the case that you were not able to work on this due to time constraints i could possibly create a PR for it if you decided to implement it.

**Comment by stephanrauh** [comment]
Pull requests are always welcome! However, I still wonder how to deal with the breaking change.

I know many developer use CSS snippets to modify the look and feel of the PDF viewer. Most of them use it to hide widgets, and I've even seen a dark theme.

Is it possible to implement an attribute like `[viewEncapsulationMode]="emulated"`? Or is it possible to modified the `ViewEncapsulationMode` of `NgxExtendedPdfViewerComponent` from a parent component?

If both options are impossible, I'd like to announce the breaking change during the `npm install`. The problem is that Angular considers this as a security risk, so we'd have to circumvent the security mechanism of Angular. That's possible (I think), but it doesn't feel good. :)

Be that as it may, feel free to send me a pull request!

Thanks in advance,
Stephan

**Comment by stephanrauh** [comment]
The feature ships with version 5.0.0. I didn't use Angular's `ViewEncapsulation`. Instead, I added the CSS class `ngx-extended-pdf-viewer` to almost every rule (apart from a few rules dealing with printing and possibly a few rules for RTL languages).
