### ISSUE TITLE
Allow percentage unit for height option

### ISSUE THREAD

**Issue by dorthrithil** [stephanrauh/ngx-extended-pdf-viewer#45]
Currently setting `[height]="'100%'"` will result in the pdf not being displayed as the container has a height of zero. This can be easily fixed by also setting the `.zoom` container to `height: 100%`.

**Comment by stephanrauh** [comment]
@dorthrithil I've published a new version (0.9.16) which should do the trick. Please test it and report back.

(Problem is it doesn't work in my test case: setting the height to 100% always causes the height to be 0px. I believe that's caused by my Material Design tabs. But it's really disturbing, so I'd appreciate to hear from you).
