### ISSUE TITLE
Why was ignoreResponsiveCss removed, how can I enable it? 

### ISSUE THREAD

**Issue by gotwig** [stephanrauh/ngx-extended-pdf-viewer#451]
Title says everything, when its mobile my buttons just get display: none, the docs still list the option but its removed.

When I use NG-Deep it still doesnt work, I dont know why, even important doesnt work, even tho its applied it doesnt work

I need custom icons on mobile...

**Comment by stephanrauh** [comment]
I suppose the easiest way is to implement a custom toolbar. It's just a bit tedious because it amount to copy all the component you need to your project. For example, to copy the rotate buttons, you'd have to copy https://github.com/stephanrauh/ngx-extended-pdf-viewer/tree/master/projects/ngx-extended-pdf-viewer/src/lib/toolbar/pdf-rotate-page and to remove the CSS class `hiddenXLView` from the HTML snippet.

However, simple CSS should do the trick, too. The CSS code is inserted dynamically here: https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/8a61417f9ca831bf375c6336f57ebe5a61d89b02/projects/ngx-extended-pdf-viewer/src/lib/dynamic-css/dynamic-css.component.ts#L29

You're right, `/deep/` won't work, because these rules are global CSS. You can modify them in the `styles.css`. I'd like to set the `ViewEncapsulationMode` back to the default, but that's a breaking change - see #435. However, in your case, it's easier to deal with global CSS rules, I think.

**Comment by stephanrauh** [comment]
As for your question: I've replace the JavaScript-based approach of the `ignoreResponsiveCss` era by an approach that works faster and smoother. I didn't expect any incompatibility. My best guess is your CSS can be easily fixed by adding selectors - but I can't tell for sure because I don't know your code.

**Comment by stephanrauh** [comment]
As always, I'd like to ask you to report back so I know I can close the ticket. If you've still got trouble, don't hesitate to ask me, either!

Best regards,
Stephan

**Comment by gotwig** [comment]
was able to do it with css ;D thx

**Comment by stephanrauh** [comment]
Awesome!
