### ISSUE TITLE
Enable "highlight all" from search by default?

### ISSUE THREAD

**Issue by gotwig** [stephanrauh/ngx-extended-pdf-viewer#455]
Hey, I want to do my findbar as easy as possible but want the highlight all functionality by default, can you help ?

And also can I prevent the search from jumping to the first result automaticly? the jump seems to be not very precise, sometimes the scroll offset is over the matched element so you dont see it

Danke :D

**Comment by stephanrauh** [comment]
As for the second question: no, I don't think I can do anything about it. You're right, the jump isn't precise. The team at Mozilla's did a great job to make it as precise as possible, but it seems to be a very hard problem.

**Comment by stephanrauh** [comment]
To activate the highlight option by default you can add an `AfterViewInit` handler to the parent component. The method is called when the PDF viewer has been rendered. So you can find the ID of the checkbox and set it via JavaScript.

Alternatively, you can define your own custom findbar. There's a demo at https://pdfviewer.net/custom-toolbar. The demo is a bit flaky, but that's because the PDF viewer doesn't play well with the dynamic theme switch. Your application won't have that problem.

The implementation of the findbar is here: https://github.com/stephanrauh/ngx-extended-pdf-viewer/tree/master/projects/ngx-extended-pdf-viewer/src/lib/toolbar/pdf-findbar. Just copy the components you want to modify to your project and use them instead of the standard components in the custom findbar.

**Comment by stephanrauh** [comment]
I'll close the ticket now, but like always, I'm still listening. Don't hesitate to re-open the ticket if you've got questions.

Bis bald! :)
Stephan
