### ISSUE TITLE
Load multiple pages with [page] attribute option

### ISSUE THREAD

**Issue by Jeya-Prakash** [stephanrauh/ngx-extended-pdf-viewer#50]
I want to set page ranges (like  3-5) for a 7 page PDF document which is already rendered in the PDF viewer. How to achieve this with [page] attribute ?

**Comment by stephanrauh** [comment]
The [(page)] attribute controls which page is shown first when the PDF is loaded (or when the attribute changes). Hence it takes a simple number. 

What do you want to achieve with the page range? Does "3-5" mean that the first pages are excluded from the PDF viewer, so you can't scroll to these pages?

**Comment by Jeya-Prakash** [comment]
Yes.. 3-5 range means user will only have to see the 3rd, 4th, 5th page from original 7 page document. I am expecting same as how google chrome print range works.

**Comment by stephanrauh** [comment]
After an hour of Googling, I believe that Mozilla's PDF.js library doesn't support that feature. ngx-extended-pdf-viewer is a simple wrapper around PDF.js, so that's bad news.

However, I can offer a workaround. Have you discovered the Hummus library already? Among many things, it can generate PDF files consisting of a few pages of the original file. As far as I can see, it's a server-side library.

https://github.com/galkahana/HummusJS/wiki/Embedding-pdf

**Comment by Jeya-Prakash** [comment]
Thanks man, will look into it 😊
