### ISSUE TITLE
Passing in formgroup element into viewer to allow for angular to populate fields

### ISSUE THREAD

**Issue by texteng** [stephanrauh/ngx-extended-pdf-viewer#511]
**Is your feature request related to a problem? Please describe.**
I really like the new form field fields feature.  I have been trying to integrate this package into my company's platform. We would like to get information from our database to populate the form fields in the PDF document.

**Describe the solution you'd like**
When creating a reactive form in angular, the way to pass data into the pdf document is through a formgroup.  Forms look like the code below.
`<form [formGroup]="reactiveForm" (ngSubmit)="onSubmit()" novalidate>`
It would be nice if we could pass in a **formGroup** from the component that hosts the pdf-viewer. Therefore it would be easy to pass in and save data from the pdf form. 

**Describe alternatives you've considered**
I tried to wrap the whole component with form tags, but that didn't work. I am a junior dev. I am trying...

**Comment by stephanrauh** [comment]
Your proposal is similar to #499. I like the idea of using a form group. I'm not sure it's possible, because there doesn't seem to be a way to guess the internal names of the PDF form fields. So I need your help.

@texteng Would you mind to examine the form fields of your PDF files? Open the PDF file in the showcase htts://pdfviewer.net or your own application. Open the browser console window. The form data is stored in `PDFViewerApplication.pdfDocument.annotationStorage`. That's basically a hash table (plus some metadata). I'm interested in the names of the keys. Are they just random gibberish, as my test PDF file indicates?

![image](https://user-images.githubusercontent.com/3045767/96334710-1be1d300-1073-11eb-852b-78a768d4cd9c.png)

**Comment by texteng** [comment]
This is what I got for my data.  
![Screenshot 2020-10-17 at 10 40 03 AM - Display 1](https://user-images.githubusercontent.com/39864899/96347180-a0c5f000-1065-11eb-948b-0e072cff8f8a.png)

If one looks at the input field in the control, the pdf field name can be found.  
![Screenshot 2020-10-17 at 10 48 35 AM - Display 1 - Edited](https://user-images.githubusercontent.com/39864899/96347303-6b6dd200-1066-11eb-9c0f-a63de1f1095d.png)
I am pretty new to angular, and have only experimented with the pdf.js library recently. One could assume that we could take the attribute of the "name" field and create a formControlName field in the input field.  I know it is more complicated than that, but maybe that helps.

The pdf used for testing.  I modified to have the form fields named the way I want them to in acrobat.
[oklahoma-motor-vehicle-power-of-attorney-form modified.pdf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/5395969/oklahoma-motor-vehicle-power-of-attorney-form.modified.pdf)

**Comment by stephanrauh** [comment]
That's clever!

**Comment by texteng** [comment]
Thanks!  I will take a look at it.

**Comment by stephanrauh** [comment]
@texteng Well, currently it's really just of proof of concept. You can pass a hash mao of keys and values to the PDF viewer, and it fills the values into the form fields if the keys match. There's no two-way binding. It doesn't even update the form fields if the hash map changes.

**Comment by texteng** [comment]
> @texteng Well, currently it's really just of proof of concept. You can pass a hash mao of keys and values to the PDF viewer, and it fills the values into the form fields if the keys match. There's no two-way binding. It doesn't even update the form fields if the hash map changes.

I have found in situations, two way binding isn't necessary.  I believe if you pass a formgroup object from the app to the component.  You can still subscribe to that formgroup directly in the app.

**Comment by stephanrauh** [comment]
I think I've got your message - but this approach doesn't work here. The form fields of the PDF viewer are entirely decoupled from everything Angular does. They have to be, because pdf.js is the PDF viewer of Firefox, so it has been developed without Angular in mind. So my approach simply copies the values into the form fields when the Angular viewer is initialized. The next steps are to implement `onblur` or `onchange` events and to implement an `ngChange` method.

At the moment, I don't have a clue how to implement support for reactive and template-driven forms. That's going to be some interesting and exciting research!

**Comment by texteng** [comment]
i am new at this, but if you need any help, I would love to do so.

**Comment by stephanrauh** [comment]
@texteng That's very kind of you, thanks! Maybe you drop me an e-mail (webmaster1 at beyondjava.net). 

You're right, I could use a helping hand. I'm not sure this particular ticket is a good starting point - IMHO it's too advanced - but there are several things you (and everybody else who's interested) can do to support this project:

- Find out how to implement a custom directive supporting reactive or template-driven forms. Maybe there are blogs or tutorials on the topic. Maybe it's a good approach to analyze how the Angular team have implemented directives like `[ngModel]`. In any case, I believe it's important to support both approaches. According to the blogosphere, everybody and the grandma loves reactive forms, but I suspect the blogosphere is biased and template-driven forms are more popular then expected.
- Answer tickets created by other users. That'd be a great help to me. It takes a surprising amount of time to understand and answer questions.
- Test the new features I'm publishing
- Read the documentation and tell me what's wrong or misleading. I'm sure there's a lot of confusing stuff out there! You can also send me pull requests to https://github.com/stephanrauh/extended-pdf-viewer-showcase.
- Finally, I also appreciate pull request to https://github.com/stephanrauh/ngx-extended-pdf-viewer or even https://github.com/stephanrauh/pdf.js. But that's demanding a lot, so I didn't start with it. :)

**Comment by stephanrauh** [comment]
I've implemented two-way binding. For some reason, this prevents editing the form fields, so I can't publish the prototype on npm today. I'm positive I'll manage tomorrow.

**Comment by texteng** [comment]
I am sorry for not responding earlier.  Thanks for getting the binding done. I will send you and email now before i forget.

**Comment by stephanrauh** [comment]
You've got my e-mail address? Just in case: webmaster1 at beyondjava dot de

**Comment by stephanrauh** [comment]
Please check out version 5.2.0-alpha.0. I've called the attribute `[(formDataSneakPreview)]`. When I've finally decided what the API looks like, I'll rename the attribute to `[(formDataSneak)]`. The source code of the showcase has a running demo: https://github.com/stephanrauh/extended-pdf-viewer-showcase/tree/master/src/app/forms

**Comment by stephanrauh** [comment]
The key to supporting `[formGroup]` or `[(ngModel)]` seems to be implementing the interface `ControlValueAccessor`. However, the AcroForm can have any number of input fields, so we need to create Angular-aware input fields dynamically. So I guess it's OK to forget about `ControlValueAccessor` and add a shadow `<input [formGroup]="acro.form.name">` to each input field of the form in the PDF field.

That's some advanced Angular magic, so I'm reluctant, but it sounds useful. Plus, I've done similar stuff to implement my blog, so maybe it's not as scary as it sounds.

More information about `ControlValueAccessor`: https://medium.com/@tarik.nzl/angular-2-custom-form-control-with-validation-json-input-2b4cf9bc2d73

**Comment by stephanrauh** [comment]
@texteng Just saw your sentence about being a junior dev and wanted to send you a "heads up":

>I tried to wrap the whole component with form tags, but that didn't work. I am a junior dev. I am trying...

Even a senior developer might run into this trap. It looks tempting. Thing is Angular is doing some sophisticated magic. Angular-aware input fields are created and managed by Angular. Too bad pdf.js has been developed without Angular in mind. It's just the PDF viewer of Firefox. ngx-extended-pdf-viewer builds a bridge between these two worlds. That's why the task is so difficult (and why it's so interesting).

**Comment by texteng** [comment]
The things we do avoid post our email addresses up online. I misread it the first time. Hopefully not this time.

**Comment by texteng** [comment]
I found this article for a different library. it might be helpful. https://medium.com/factory-mind/angular-pdf-forms-fa72b15c3fbd

**Comment by stephanrauh** [comment]
Thanks! That's a clever approach. The difference is that it replaces the AcroForm fields, while we want to use them. The official Angular documentation uses the same approach to implement dynamic forms: https://angular.io/guide/dynamic-form

(To be honest, when he wrote his article, Jonny Fox could use the built-in ActroForm support of pdf.js because it wasn't released yet).

**Comment by stephanrauh** [comment]
I've decided not to change the API of ngx-extended-pdf-viewer. I don't manage to find an intuitive API. But I might add a demo to the showcase, based on the ideas of Jonny Fox. That's not exactly what you've asked for, but I hope it's close enough. Exposing the annotation data object sounds like a promising way to add value to the library.

**Comment by texteng** [comment]
Thanks!

**Comment by stephanrauh** [comment]
The feature has landed with version 5.2.1, so I'll close the ticket now.
