### ISSUE TITLE
pdf.min.js is undefined on 'bleeding edge'

### ISSUE THREAD

**Issue by codr36** [stephanrauh/ngx-extended-pdf-viewer#520]
**Check this first**
- Does the bug also happen on https://pdfviewer.net/simple? **yes**
- Can you write a reproducer based on this template project? https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/master/template **yes**

**Describe the bug**
First off, thanks for the package. It's a great wrapper and I find it quite useful. Now, onto the problem.
Following the setup tutorial, I used the 'bleeding edge' version of assets and my viewer didn't work that way. 
It seems that the file https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/master/projects/ngx-extended-pdf-viewer/src/bleeding-edge/pdf.min.js is undefined, breaking the viewer at runtime (app tries to fetch said file - see network tab). No errors thrown which can be confusing.

**Version info**
- Version of ngx-extended-pdf-viewer
5.2.0-alpha.0

**Comment by stephanrauh** [comment]
Please navigate to https://pdfviewer.net/pdfjs-versions. That's the demo of the "bleeding edge" viewer, using version 5.2.1 I've published a couple of minutes ago.

Does the error occur on there, too? If not, I assume you've run into a configuration error. I just don't know which one because I don't know your project.

**Comment by stephanrauh** [comment]
@codr36 Any news? Did you manage to solve the issue?

If I don't hear from you, I'll close the ticket in a couple of days. As much as I'd like to help you, I can't solve a problem I can't reproduce. So I need you help!
