### ISSUE TITLE
assets folder does load the locale.properties when assetFolder is changed 

### ISSUE THREAD

**Issue by nileshdevdas** [stephanrauh/ngx-extended-pdf-viewer#548]
Bug Report :

While creating a angular build we are using the --deploy-url /xx
We have updated the assetsFolder to point to xx/assets .
Everything seems to work great except the locale.properties is still being searched in /assets/locale/locale.properties and not in /xx/assets/locale.properties while the viewer.js pdf.js and other are picked correctly from the given location post adding the assets folder. We end up getting a lot of locale related warning and issues in the browser console when we load the pdf. The PDF Viewer works okay however the local support does not as the locale.properties is not pointing to the correct folder.

![image](https://user-images.githubusercontent.com/24402152/98810536-6aea1080-2445-11eb-8f02-8c19578e4386.png)

![image](https://user-images.githubusercontent.com/24402152/98810632-83f2c180-2445-11eb-805b-c2359f8ce7b1.png)

**Comment by stephanrauh** [comment]
Solving the bug is one thing - top on my priority list! - but I'd like to offer you a workaround. If you only need to support one language, or a few languages, I recommend inlining the language files. The documentation is a bit hidden. Navigate to https://pdfviewer.net/i18n and open the right-most tab (the one titled "index.html (optional)".

I've prepared JSON files you can simply add to your `index.html` - or any other HTML file that's guaranteed to be loaded before ngx-extended-pdf-viewer is used. The advantage of inline is improved performance (two requests less!). The disadvantage is you only support the languages you've decided to add to your HTML file.

**Comment by stephanrauh** [comment]
I've found the bug, but solving it isn't as easy as it should be. It seems I've run into a weird corner case of Angular. I'll fix the bug this week-end.

BTW: can somebody tell me why this href is empty? `<link [href]="localeFolderPath+'/locale.properties'"  />` 
When I replace "href" with any other attribute, it works. What's going on?

**Comment by stephanrauh** [comment]
Solved the issue. The bugfx has landed with version 6.0.0-beta.2. You can verify it by navigating to https://pdfviewer.net/pdfjs-versions. The language files are now loaded from the bleeding-edge branch, which has several translations missing in the older 2.6 branch of pdf.js.

May I ask you to test the feature and tell me if it's solved on your machine, too?

Thanks in advance,
Stephan

**Comment by stephanrauh** [comment]
BTW, I intend to make it a final version during this week-end or early next week. IMHO, the library is production-ready. I just love being able to introduce breaking changes. :)

**Comment by nileshdevdas** [comment]
Stephan,

That realy a great news let me integrate and check this out will push the
feedback by tommorow

Nilesh
