### ISSUE TITLE
UnknownErrorException: The API version "2.6.405" does not match the Worker version "2.6.404" (in production-build only)

### ISSUE THREAD

**Issue by OV2012** [stephanrauh/ngx-extended-pdf-viewer#553]
viewer stopped working in production after upgrading from version **4.1.2** to the current **6.0.0** .
on the localhost works fine.
any idea what is causing this issue ?

**Screenshots**
![image](https://user-images.githubusercontent.com/1809404/99378364-a06c7f00-28c7-11eb-95ce-98d14f080902.png)

**Comment by stephanrauh** [comment]
More often than not, it's the browser cache.

**Comment by stephanrauh** [comment]
Does clearing the browser cache solve the problem? I suppose I should add the version number to the worker.js, but it's difficult because it's just a library I'm using.

**Comment by OV2012** [comment]
hi,
sorry for the delayed response.
but unfortunately, it doesn't help.
any idea for a workaround?

**Comment by stephanrauh** [comment]
Let's start diagnosing the issue thoroughly:

1. use the non-minified libraries so you can read them easily: `[minifiedJSLibraries]="false"`. (That's slower, so it's not a good idea on the long term, but it gives your more insight).
2. If it's a browser cache issue, the problem is probably already gone now. :)
3. Check the version number in the files pdf.js and pdf.worker.js. They should both be identical. Currently that's 2.6.405. Simply run a test search for "2.6." in the source code displayed in the browser's developer tools.
4. If the versions are different, and if clearing the cache doesn't work, check the files pdf.js and pdf.worker.js in your `node_modules/ngx-extended-pdf-viewer/assets` folder. Are the correct versions of the files there?
5. Maybe it's also a problem when copying the assets folder from the `node_modules` folder to your application's `assets` folder. Does your application ship the correct versions of pdf.js and pdf.worker.js?

**Comment by OV2012** [comment]
ok. i am investigating  now ... :)

**Comment by OV2012** [comment]
first of all thank you very much for the premiums support!!
i found the problem and it was in our release-setup (azure devops).
viewer works now  and you can close this issue.
sorry again for the noise! :)

**Comment by stephanrauh** [comment]
That's great news! I'll try to rename the files, nonetheless. Every time I update pdf.js I run into the same error message, and who knows how many regular visitors of the showcase share this fate...

**Comment by stephanrauh** [comment]
Starting with version 7.0.0, the JavaScript file names contains the version number. So the dreaded caching problems are gone.

Enjoy!
Stephan
