### ISSUE TITLE
Get pdf as blob after user fills out form fields?

### ISSUE THREAD

**Issue by dancastellon** [stephanrauh/ngx-extended-pdf-viewer#558]
I'm not sure if this is the right place for this question but - Is it possible with this tool to allow the user to edit form fields in a PDF, then instead of downloading the modified file, export it as a blob so that it can be uploaded to a server?

**Comment by ChaseC99** [comment]
I was wondering the same thing!

I also tried [extracting an image](https://pdfviewer.net/export) of the PDF but unfortunately it doesn't include the data inputed into the form fields.

**Comment by stephanrauh** [comment]
Actually, download BLOB is surprisingly easy:

```typescript
import { IPDFViewerApplication } from 'ngx-extended-pdf-viewer';

  public async download(): Promise<void> {
    const PDFViewerApplication: IPDFViewerApplication = (window as any).PDFViewerApplication;
    const data = await PDFViewerApplication.pdfDocument.getData();
    const blob = new Blob([data], { type: "application/pdf" });
    console.log(blob);
  }
```

**Comment by stephanrauh** [comment]
The form isn't part of the PDF file. It's just a HTML layer above the PDF file. So there's no easy way I can add the form data to the extracted image. 

With some effort, you can implement it yourself. You can extract the image, get the form data from PDFViewerApplication.pdfDocument and paint them into the extracted image. This article shows how to get the form data, the type of the form fields and the position of the fields: https://medium.com/factory-mind/angular-pdf-forms-fa72b15c3fbd

**Comment by stephanrauh** [comment]
@dancastellon  @ChaseC99 I've added the download-as-BLOB feature to `NgxExtendedPdfViewerService`. For some reason unknown the user input doesn't seem to be part of the BLOB. That's weird because I'm using exactly the same code pdf.js uses - or at least I thought so. Maybe you can have a look at the new API and check if the user input is really missing. Until now, I've only checked the size of the BLOB, so I'm not sure.

Here's the live demo: https://pdfviewer.net/forms

**Comment by ChaseC99** [comment]
I played around with the new API and your suspicion was correct; the user input was missing... 
However after taking a look at pdf.js, I realized that we just need to call `.saveDocument` instead of using `.getData`! 

```diff
- const data = await PDFViewerApplication.pdfDocument.getData(); 
+ const data = await PDFViewerApplication.pdfDocument.saveDocument(PDFViewerApplication.pdfDocument.annotationStorage);
```

For reference, here's a link to that line: https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/5df98c85a003adeaaaa36bdb49245ba601787148/projects/ngx-extended-pdf-viewer/src/lib/ngx-extended-pdf-viewer.service.ts#L282

**Comment by stephanrauh** [comment]
Great! I've merged your PR and published it as version 7.0.0-beta.2.

Enjoy!
Stephan

**Comment by ChaseC99** [comment]
Awesome! Thanks for your hard work on this library 🙌

**Comment by dancastellon** [comment]
Wow that was quick. Thanks for this and for this awesome library!
