### ISSUE TITLE
Include PdfJs libs via webpack

### ISSUE THREAD

**Issue by kleinph** [stephanrauh/ngx-extended-pdf-viewer#57]
Is there a simpler way to include the PdfJs assets? In my _angular.json_ config I do not have the fields mentioned in the docs (I have an empty `architect` property to be exactly).

Is it possible to just copy the assets with webpackCopyPlugin over to the dist folder?

Thanks!

**Comment by stephanrauh** [comment]
Sounds like you're using an older version of Angular, or your project started with an older version and has migrated incompletely. In other words: I don't know how to help you simply because I don't have the same project setup.

For some reason, Angular doesn't support Webpack scripts since a couple of versions (Angular 6 or so). It uses Webpack under the hood, but it doesn't expose the Webpack scripts, so you can't modify them. That's why Manfred Steyer wrote his [ngx-build-plus](https://github.com/manfredsteyer/ngx-build-plus) project. This project *should* allow you to use the Webpack copy plugin with Angular 6, 7, and probably even Angular 8.

Back to your question: yeah, sure, you can use any tool to copy the asset folders. The only thing that matters is that they're there at runtime. A simple option might be to write a npm script - something like `postbuild` - to execute a Windows or Unix copy script. Or to call Webpack to perform some extra magic.

(As you may or may not know, commands like `npm run build` actually call three scripts: `npm run prebuild`, `npm run build`, and `npm run postbuild`, in that order. The idea is to use one of the standard commands and to add the copy script to a `post` script).

I'll keep the issue open for a moment. Please tell me if you managed to implement one of these ideas, so I can add it to the documentation and to the showcase I plan to create.

**Comment by kleinph** [comment]
Thanks for the quick response!

The project was generated with a tool called jHipster and since upraded to
Angular 7 with no problems. Webpack is directly used (I think instead of
the normal Angular tooling).

Nonetheless I think it is just enough to know where the assets are expected
(relative to the bundle).

I will report back about my progress.

Stephan Rauh <notifications@github.com> schrieb am Mi., 8. Mai 2019, 21:53:

**Comment by stephanrauh** [comment]
Today I've managed to have a look at JHipster. You're right, these guys simply replace the Angular tooling by their own webpack scripts. 

Actually, that makes copying the files even simpler. The file `webpack.common.js` already calls the `CopyWebpackPlugin` to copy  a lot of files. You can either simply add my file list there, or add another file `custom.webpack.common.js` calling the `CopyWebpackPlugin`.

I suppose the second approach is better because it makes updating to a new version of JHipster easier.

**Comment by stephanrauh** [comment]
Well, that was a lot more difficult than expected. Simply copying the files isn't enough. You have to copy the JS files to the project, modify them and include them in a files of your project (such as `app.main.ts`).

Part of the problem is that JHipster uses a different module system.

Be that as it may - I've added a step-by-step description to the project readme. You'll find it on npm within a few minutes. Alternatively, just click the link above this text to read the commit.

**Comment by kleinph** [comment]
Thank you very much for the afford. I will try this later.

**Comment by stephanrauh** [comment]
When you've tried, please tell me if it works. Otherwise, feel free to re-open the ticket.
