### ISSUE TITLE
IE11 support has been dropped

### ISSUE THREAD

**Issue by stephanrauh** [stephanrauh/ngx-extended-pdf-viewer#570]
I've given up supporting IE11 actively. However, I happily accept pull requests. I can also solve IE11 bug if you tell me what is broken. The last couple of errors threw an exception without any clue what the offending line is. In such a case, I need your helping hand!

**Comment by stephanrauh** [comment]
Update: the base library, pdf.js, has dropped support for IE11. In particular, their ES5 build produces code that's incompatible to Internet Explorer. I don't see any simple bug fix, so I've reluctantly decided to officially drop support for Internet Explorer 11.

**Comment by Wisdomb33r** [comment]
Hi @stephanrauh ,

Could you please indicate in this topic what is the last version known to be compatible with Internet Explorer ? I searched your project README guide and changelog, but I could not find which major version is breaking the IE compatibility. There is a paragraph indicating the compatibility has been dropped, but it does not indicates in which branch or version.

The current version I'm using is 5.1 and is compatible (mostly). Due to a display bug with 5.1 I'm currently digging (missing characters when viewing specific PDF files under IE), I'd like to update to the latest compatible version. I had no success so far with 8.3.0 (just get a `Syntax Error` without much useful information). I'll start downgrading version till I find one which still works on IE, but it would be nice to have an "official" information according to your knowledge (I suppose related to a pdf.js version upgrade).

Thank you for your time with this very good library and best regards.

**Comment by stephanrauh** [comment]
In a nutshell: IE11 support is broken since version 8.0. At least I believe so.

It's hard to tell. IE11 incompatibility caught me by surprise. But I'm almost certain that version 6.2 still worked with IE11. I remember implementing an IE11 specific bugfix at the time. Version 7.0.0-beta.5 also rings a bell. 

I believe IE11 compatibility was broken with version 8.0.0-beta.3. You've asked for the major version, so it's version 8 that introduced the breaking change. However, IE11 support was always a bit fragile.

Hope that helps!
Stephan

**Comment by Wisdomb33r** [comment]
@stephanrauh Thanks for the "officiel" information. I tried several versions within my project and the current status is :

- Version 5.3 is displaying correctly most of the PDF files (but with character display bug for some of them, upgrading from 5.1 did not solve it)
- Versions 6.1.0 and 7.3.2 are crashing, but I do not understand why yet. It might be related to incompatibility within my project rather than ngx-extended-pdf-viewer or pdf.js being incompatible with Internet Explorer. Cannot tell because up to now the lib simply crashes.
- Versions 8.3.0 and 9.0.0-alpha.7 are crashing within pdf.js : `SCRIPT1002: Syntax Error pdf-2.7.673-es5.min.js (22,321)`. This message seems consistent with your observations that Mozilla's lib might have trouble with IE. At least this 2.7.673 build.

Just btw, would you have an idea for this error message within versions 6.x and 7.x : 
```
Uncaught (in promise): SyntaxError
Error: Uncaught (in promise): SyntaxError
   at resolvePromise (http://localhost:4200/polyfills-es5.js:1326:17)
   at resolvePromise (http://localhost:4200/polyfills-es5.js:1269:11)
   at Anonymous function (http://localhost:4200/polyfills-es5.js:1395:11)
   at ZoneDelegate.prototype.invokeTask (http://localhost:4200/polyfills-es5.js:776:9)
   at onInvokeTask (http://localhost:4200/vendor.js:125564:9)
   at ZoneDelegate.prototype.invokeTask (http://localhost:4200/polyfills-es5.js:776:9)
   at Zone.prototype.runTask (http://localhost:4200/polyfills-es5.js:526:13)
   at drainMicroTaskQueue (http://localhost:4200/polyfills-es5.js:992:15)
   at ZoneTask.invokeTask (http://localhost:4200/polyfills-es5.js:874:13)
   at invoke (http://localhost:4200/polyfills-es5.js:857:13)
```
It is within the polyfills compiled by Angular (version 10.1.6 at the moment with zone.js 0.10.3). That's very difficult to understand, especially with the debugger tools of the damn old Internet Explorer... if by chance you have an insight, I would be very grateful :-)

**Comment by stephanrauh** [comment]
I'm not sure, but updating to zone.js 0.11.4 might help. Older versions of zone.js often cause trouble.

**Comment by jpike88** [comment]
@stephanrauh this could be better in the sense that the pdf-es5.mins.js contains arrow functions and causes IE11 to error, spamming our error reporting tool. IE11 should at least fail silently instead of throwing a syntax error.

**Comment by kemsky** [comment]
@jpike88, you could try to minify pdfjs files using `terser` and set ie8/safari 10 flags:

```
    --ie8                       Support non-standard Internet Explorer 8.
                                Equivalent to setting `ie8: true` in `minify()`
                                for `compress`, `mangle` and `format` options.
                                By default Terser will not try to be IE-proof.

    --safari10                  Support non-standard Safari 10/11.
                                Equivalent to setting `safari10: true` in `minify()`
                                for `mangle` and `format` options.
                                By default `terser` will not work around
                                Safari 10/11 bugs.
```

**Comment by stephanrauh** [comment]
@kemsky Do you happen to know how to do this with the gulp file? https://github.com/stephanrauh/pdf.js/blob/bleeding-edge/gulpfile.js

I'm sure it's possible but I haven't managed to find out what needs to be done. BTW, ngx-extended-pdf-viewer itself also needs to be compiled for IE11.

**Comment by stephanrauh** [comment]
Starting with Angular 13, Angular itself dropped support for IE11. So let's close this ticket.
