### ISSUE TITLE
[Bleeding edge branch] Printing is broken in the sneak-preview version of pdf.js

### ISSUE THREAD

**Issue by stephanrauh** [stephanrauh/ngx-extended-pdf-viewer#586]
Currently, the bleeding edge branch prints a hardcopy of the entire screen instead of printing the PDF file.

This ticket is a follow-up of #581.

**Comment by stephanrauh** [comment]
Solved with version 7.1.1.

**Comment by b-mi** [comment]
Version 8, still prints a hardcopy of the entire screen instead of printing the PDF file. Android, actual version, chrome. I tried bleeding-edge and non bleeding-edge version. Please, how to set this library to print pdf correctly from android browser? Thanks.
![photo_2021-11-30_15-09-17](https://user-images.githubusercontent.com/26021541/144062616-bc2e5790-90a3-4c45-b725-b8d5936d8df5.jpg)
