### ISSUE TITLE
Migration: Script does not exist

### ISSUE THREAD

**Issue by EinfachHans** [stephanrauh/ngx-extended-pdf-viewer#614]
**Describe the bug**
I upgraded the Library from Version `5.3.0` to `7.3.1`. When building i get this Error now: 

**Script file node_modules/ngx-extended-pdf-viewer/assets/pdf.js does not exist.**

Currently i  have this in my **angular.json** under scripts, which now causes the error:
```json
{
  "input": "node_modules/ngx-extended-pdf-viewer/assets/pdf.js"
},
{
  "input": "node_modules/ngx-extended-pdf-viewer/assets/viewer.js"
}
```

Is there any migration Guide, anything i'm missing here?

**Comment by stephanrauh** [comment]
I've added the version number to the files. That's better because it solves many caching errors, but of course it also breaks your `angular.json`. I suppose you can simple add wildcards:

```json
{
  "input": "node_modules/ngx-extended-pdf-viewer/assets/pdf-*.js"
},
{
  "input": "node_modules/ngx-extended-pdf-viewer/assets/viewer-*.js"
}
```

BTW, you may also think about using the minified version of the files. Debugging these files isn't fun, but debugging is probably not your use-case, so you'll benefit from the performance boost.

**Comment by EinfachHans** [comment]
Wildcard doesn't work for me 🤔 I added the min Version now but have to include the version code also so now i need to change this whenever you update the version 😒
