### ISSUE TITLE
ngxEFV 8.0.0.beta(1|2) tries to load the wrong lib of pdf-*.min.js

### ISSUE THREAD

**Issue by fscarponi** [stephanrauh/ngx-extended-pdf-viewer#627]
**Describe the bug**
The last version of ngxEFV tries to load the wrong lib of pdf-*.min.js
require 2.6.423 but download 2.6.424
the problem does not affect ngxEFV 7.* 

**Version info**
8.0.0.beta2 and 8.0.0.beta1

**Desktop (please complete the following information):**
all
 
**Smartphone (please complete the following information):**
haven't checked

**To Reproduce**
basic iter

**Demo PDF file**
every pdf

**Screenshots**
![Error](https://user-images.githubusercontent.com/36624359/105819767-e70de200-5fb8-11eb-8ac5-285568645bba.PNG)
![Dowloaded libs](https://user-images.githubusercontent.com/36624359/105819866-0f95dc00-5fb9-11eb-9c30-9ae01cddc0df.PNG)

**Additional context**
No other pdf libs are in the project except this

**Comment by stephanrauh** [comment]
Stupid me! :) At least now I know why this happens every once in a while, so I can avoid bug.

I've fixed it with version 8.0.0-beta.3.

BTW, the next release is going to update the pdf.js version. So the default branch feature pdf.js 2.7 and the bleeding edge branch features pdf.js 2.8.

**Comment by hellojt9040** [comment]
I am also getting this type of issue.
But the problem is the issue only available after deployment.
In  local it's working fine

![image](https://user-images.githubusercontent.com/41210284/113674913-6239f580-96d8-11eb-873d-774a16340478.png)

My ngx-extended-pdf-viewer version is ^8.1.1

![image](https://user-images.githubusercontent.com/41210284/113681144-44bc5a00-96df-11eb-9a82-213a8af3c60a.png)


![image](https://user-images.githubusercontent.com/41210284/113681024-26565e80-96df-11eb-870b-742b7954254d.png)

**Comment by stephanrauh** [comment]
Sounds like a caching problem to me. Does the problem occur each time you've updated ngx-extended-pdf-viewer?

**Comment by hellojt9040** [comment]
Sorry that was a silly mistake from my side.
