### ISSUE TITLE
Print not working

### ISSUE THREAD

**Issue by pavansai1122** [stephanrauh/ngx-extended-pdf-viewer#642]
print option in the header not working. Displaying blank preview
![Screenshot from 2021-02-09 10-33-41](https://user-images.githubusercontent.com/37793936/107318234-4f34eb80-6ac2-11eb-9ca7-c64cc0eb0c11.png)

**Comment by stephanrauh** [comment]
I don't think so. Just navigate to http://pdfviewer.net and you'll see printing works like charm. See the screenshot below.

I suggest you do this:

- Clone the showcase (https://github.com/stephanrauh/extended-pdf-viewer-showcase/), run `npm install` and `ng s -o` and you'll see printing also works on your machine.
- Examine your project, compare it to the showcase, and find out what the difference it. It's either a JavaScript error or an interference with your CSS.
- If you're still stuck, please take five minutes to describe precisely what you're doing. Simply telling me your application has a bug doesn't get you anywhere because I don't know your application.

Best regards,
Stephan

![image](https://user-images.githubusercontent.com/3045767/107420712-7ff43f80-6b19-11eb-80b5-a5e3946bd5bc.png)

**Comment by stephanrauh** [comment]
I've went over the print CSS again. When you update to version 9.0.0, your bug should be gone.
