### ISSUE TITLE
Error: startCleanup: Page X is currently rendering

### ISSUE THREAD

**Issue by kemsky** [stephanrauh/ngx-extended-pdf-viewer#645]
**Describe the bug**
We are receiving crash reports:

```
Error: startCleanup: Page 5 is currently rendering.
  at ? (/Content/cg/js/angular/assets/viewer-2.6.423.min.js:22:55931)
```

I was only able to find related code in the minified version of viewer (why it is not present in original version?):
```
            startCleanup() {
                return this.messageHandler.sendWithPromise("Cleanup", null).then(() => {
                    for (let e = 0, t = this.pageCache.length; e < t; e++) {
                        const t = this.pageCache[e];
                        if (t) {
                            if (!t.cleanup()) throw new Error(`startCleanup: Page ${e + 1} is currently rendering.`)
                        }
                    }
                    this.commonObjs.clear();
                    this.fontLoader.clear()
                })
            }
```
I don't even know if it is critical or not.

**Version info**
- Version of ngx-extended-pdf-viewer - 7.3.2

**Desktop (please complete the following information):**
 - Browser Chrome
 
**Smartphone (please complete the following information):**
 - Device: PC

**To Reproduce**

There is no reliable way to reproduce, but it happens quite often.

My best guess is that it happens when users do fast open/close and pages are still rendering when onDestroy is triggered https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/30933c416106a2ac642027e28ab5bf94cdd4db92/projects/ngx-extended-pdf-viewer/src/lib/ngx-extended-pdf-viewer.component.ts#L1308

**Comment by stephanrauh** [comment]
Well, the code is in the original code, indeed. Look here: https://github.com/stephanrauh/pdf.js/blob/201a42ae38099f216fb99615b7f196d9f10a29d2/src/display/api.js#L2744

**Comment by stephanrauh** [comment]
I don't think the bug is critical. I agree with your best guess that this happens when users close the PDF viewer while it's still rendering. If that's true, it's a memory leak, but probably not even a bad one. However, if you're observing problems after running the application for a long time, this might be the reason.

I'm going to call this bug a "nuisance" until anyone convinces me it's really bad. On the other hand, it might be easy to fix, so chances are I'm going to address this bug soon. 

The comment of the `cleanup()` method sheds some light on the problem:

```js
  /**
   * Cleans up resources allocated by the document on both the main and worker
   * threads.
   *
   * NOTE: Do not, under any circumstances, call this method when rendering is
   * currently ongoing since that may lead to rendering errors.
   *
   * @returns {Promise} A promise that is resolved when clean-up has finished.
   */
```

**Comment by kemsky** [comment]
@stephanrauh, the biggest problem with this bug is that it triggers unwanted Sentry reports. 

Currently, I'm testing hackish solution which subscribes to page render start/stop events (for some reason component exposes only pagerendered event but there is also pagerender) and delays cleanup.

**Comment by stephanrauh** [comment]
Yeah, that's sort of the approach I'd do, too. Tell me how it works out!

Actually, my idea was to implement the improvement / bug fix in pdf.js itself. I imagined keeping a list of the resource to clean up and to retry cleaning up with a timeout if an exception is raised. I suppose your approach is more elegant. I was just worried about race conditions. What happens if the new document is rendered, and the pages are stored in the same array as the original pages? I'm not sure if that's likely, but that's something I'd like to examine.

**Comment by stephanrauh** [comment]
@kemsky Any news? Does you hackish approach work?

**Comment by kemsky** [comment]
@stephanrauh, I'm going to patch the `cleanup` method and wrap it into try/catch :)

**Comment by stephanrauh** [comment]
Maybe it's also a good idea to call `cleanup()` a fraction of a second later if it fails at first attempt.

**Comment by stephanrauh** [comment]
I'm adding `(pageRender)` to version 9.0.0. Thanks for pointing this out!

**Comment by stephanrauh** [comment]
`(pageRender)` has just landed with version 9.0.0-alpha.1.

**Comment by stephanrauh** [comment]
@kemsky Any news?

**Comment by kemsky** [comment]
@stephanrauh, currently my workaround looks like this:

```ts
    public onPdfLoaded(): void {
        const src = this.pdfSrc;
        const pdfViewer = (window as any).PDFViewerApplication;

        if (pdfViewer != null && pdfViewer.pdfViewer != null && pdfViewer.pdfDocument != null && pdfViewer.pdfThumbnailViewer != null) {
            pdfViewer.cleanup = () => {
                try {
                    pdfViewer.pdfViewer.cleanup();
                    pdfViewer.pdfThumbnailViewer.cleanup();
                    if (pdfViewer.pdfViewer.renderer !== 'svg' && pdfViewer.pdfDocument != null) {
                        pdfViewer.pdfDocument.cleanup().catch((e: any) => {
                            console.error('PDFViewerApplication.pdfDocument.cleanup caught exception', src, e);
                        });
                    }
                    console.info('[PDFViewerApplication] cleanup success', src);
                } catch (e) {
                    this.reportError(e, 'PDFViewerApplication.cleanup caught exception');
                }
            };
        } else {
            this.reportError(new Error('Can not apply PDFViewerApplication patch'), 'Can not apply PDFViewerApplication patch');
        }
    }
```

Currently, no errors were reported, also it does not seem to affect users, so I think that a better way to deal with it is to add this error to exclude list in Sentry:

```js
Sentry.init({
   ingoredErrors: [/startCleanup: Page \d+ is currently rendering/]
});
```

**Comment by kemsky** [comment]
@stephanrauh, I think we can close this issue.

**Comment by stephanrauh** [comment]
Your workaround inspired me to implement a solution that free the memory later instead of printing the error. 

The bugfix has landed with version 9.0.0-alpha.3. May I invite you to update to that version and to run a test?

Best regards,
Stephan

**Comment by stephanrauh** [comment]
The pdf.js team at Mozilla's have modified the cleanup algorithm. So my workaround it gone when I update pdf.js in a few weeks (or if you update to the next version of the bleeding-edge branch).

The good news it the new source code seems to solve your issue. If it doesn't, don't hesitate to reach out to me.

**Comment by kemsky** [comment]
@stephanrauh, ok, we'll see

**Comment by anudhuri23** [comment]
Hello @stephanrauh I am upgrading mozilla/pdf.js to latest one. And facing same issue. I have also raised https://github.com/mozilla/pdf.js/issues/16727 but no use. Any workaound to fix the issue.

**Comment by stephanrauh** [comment]
@anudhuri23 You don't need a work-around. You need a bugfix. But I can't tell you what's wrong. As Jonas already said, you've only provided us a screenshot, and all it tells me is that my source code is not involved.

But then, you don't need me. All you need is your debugger and a couple of hours time. Make sure you're using the non-minified version of pdf.js, otherwise you'll have a hard time debugging.

**Comment by anudhuri23** [comment]
@stephanrauh the above issue is appearing only for latest version. I tried https://github.com/mozilla/pdf.js/releases/tag/v3.7.107, and there is no issue.
