### ISSUE TITLE
Caret on zoom dropdown not functional

### ISSUE THREAD

**Issue by macynbaker** [stephanrauh/ngx-extended-pdf-viewer#660]
Using the "::after" psuedo element for the dropdown caret instead of the default select caret causes functionality issues. The caret is not clickable on chrome and on windows it is appears misaligned. 

![image](https://user-images.githubusercontent.com/47578240/108546785-9b004580-72b7-11eb-919a-b0a7e834750d.png)

**Comment by stephanrauh** [comment]
What? Oh, no, not again! This dropdown is driving me nuts!

But I'm not entirely sure your bug report is true. Or rather, I'm sure it's true - you've proved it with a screenshot - but maybe there's a different root cause. Please navigate to https://pdfviewer.net and check if the dropdown is broken over there, too. On my machine, it works just fine:

![image](https://user-images.githubusercontent.com/3045767/108558874-d8d28d80-72fa-11eb-9f43-830f5f9c03c2.png)

**Comment by stephanrauh** [comment]
More likely than not, your CSS code interferes with the CSS code of pdf.js. But I'm open to suggestions. As I've said, the dropdown is driving me nuts, so I'm looking for alternatives. Simply using the default widgets works fine on some browsers, but looks ugly like hell on other browsers, so that's not the way to go. In 2021, it can't be so difficult to find a cross-browser compatible dropdown... but until now, I failed to find a decent implementation. Any suggestions?

**Comment by stephanrauh** [comment]
I haven't heard from you for more than a week. So I suppose you've managed to solve the issue, and I'm going to close the issue now.

Best regards,
Stephan
