### ISSUE TITLE
Linking External TOC Link with PDF

### ISSUE THREAD

**Issue by amitusc** [stephanrauh/ngx-extended-pdf-viewer#673]
Hi,

Is there any way for me to click on an external link and generate an event to auto-scroll the PDF in the viewer to the page specified in the link?

Thanks,
Amit Aggarwal

**Comment by stephanrauh** [comment]
Hi Amit,

yes, that's possible. Maybe. I'm not sure. Now that you mention it, I wonder why I never documented the feature.

There's definitely code dealing with URL parameters. It's just I can't promise that works, because Angular itself also uses URLs for its own purposes. So maybe the URL parameters aren't detected by the library.

These URL parameters are available in pdf.js (and maybe in ngx-extended-pdf-viewer):

- ?search=<query>
- ?page=<pageNumber>
- ?zoom=<zoom>, where <zoom> can be Fit, FitB, FitH, FitV, FitBV or a numeric percentage
- ?pagemode=<pagemode>, where <pagemode> is probably 0, 1 or 2
- ?nameddest=<destination> 

Best regards,
Stephan

**Comment by stephanrauh** [comment]
@amitusc Did my answer help you?

**Comment by stephanrauh** [comment]
It seems Angular swallows the query parameters. But you can implement them yourself and use attributes like `[page]` to open the viewer with a specific page.
