### ISSUE TITLE
Forms not working on iOS devices/ Safari browser

### ISSUE THREAD

**Issue by narendra-cb** [stephanrauh/ngx-extended-pdf-viewer#677]
When I tried it with forms in iOS devices and in safari browser, it was not working. I clicked on one input field and after filling it not able to move to another input field. 

Then I checked it into your site https://pdfviewer.net/extended-pdf-viewer/forms, **it was also not working there too.**

Please help me in fixing this issue.

**Comment by stephanrauh** [comment]
Hi Narenda,

oops - I can confirm your issue. That's the sort of issue that tend be take a lot of time and perseverance to solve, so I'll apologize in advance for solving this bug slowly. Maybe you can help me. Did you already test the same form on iOS on https://mozilla.github.io/pdf.js/web/viewer.html?

Best regards,
Stephan

**Comment by stephanrauh** [comment]
This bug can also be reproduced on Safari on macOS Big Sur 11.2.2.

**Comment by stephanrauh** [comment]
@timvandermeij When I open the PDF file https://pdfviewer.net/assets/pdfs/OoPdfFormExample.pdf on https://mozilla.github.io/pdf.js/web/viewer.html in Safari on an Apple device, I can never leave the first field I've clicked or tapped. The cursor is caught in the field and doesn't go to the next field, no matter what I do.

Is this something you guys feel responsible for? Or is iOS and OSX support out of your scope?

Best regards,
Stephan

**Comment by timvandermeij** [comment]
PDF.js uses generic web APIs, so I'm very surprised that Safari behaves differently since the AcroForm support is basically just a regular form that is overlayed over the PDF. If there is something we can easily do that is not browser-specific, we can consider integrating it, but we do try to keep browser-specific hacks to a bare minimum, especially since this should just work given that no exotic web APIs are used here, just simple forms. So the answer here is: it depends on what is necessary to get Safari to work whether or not we can integrate it.

**Comment by stephanrauh** [comment]
Today I've analyzed the bug again, and I didn't manage to reproduce it on Mozilla's demo page. It seems to be an Angular bug. The input fields have an `onBlur` listener. If I deactivate it, the bug is gone.

It's hard to tell because zone.js sort of obfuscates the event listener, but I guess it's this event listener:

https://github.com/stephanrauh/pdf.js/blob/8dfa2124b9506e16365b82e3c61a5ea592f55254/src/display/annotation_layer.js#L812

**Comment by narendra-cb** [comment]
@stephanrauh Today I checked it and found, it is working in older release that is 7.3.2 but not working for any version after this release. may be this can help you for finding the root cause of this issue.

**Comment by stephanrauh** [comment]
Sounds like a useful hint. 7.3.2 was the last version I shipped with pdf.js 2.6. Maybe it's an error of pdf.js 2.7 (or, even more likely, of my fork of pdf.js 2.7 - sometimes it's difficult to merge the latests changes correctly).

**Comment by stephanrauh** [comment]
I've started to rewrite forms support from scratch (see #718). As a side effect, this issue is going to be solved.
