### ISSUE TITLE
Printing a pdf file with only one page on Firefox shows a blank page on preview.

### ISSUE THREAD

**Issue by ThicoMart** [stephanrauh/ngx-extended-pdf-viewer#682]
I've noticed that if I send the print it works, but as the preview shows a blank page, some users is complaining that the print isn't working.

**Comment by ThicoMart** [comment]
I've also noticed in this page: "https://pdfviewer.net/extended-pdf-viewer/print-range" that printing in firefox for the second time shows the white pages, but if you scroll down the page and go back, the page renders.

**Comment by Arytecs** [comment]
Hi! I'm having the same issue here. I had in chrome but I resolved adding css styles
```
#printContainer > div {
  display: inline;
}
```

The solution dosn't resolve the problem in firefox. ¿Any updates?

**Comment by stephanrauh** [comment]
Desafortunadamente no. But I can confirm the bug. It's always difficult to debug printing, so that's bad news to me :)

**Comment by ThicoMart** [comment]
Yeah, no news on this, its really a bug.

**Comment by stephanrauh** [comment]
I can confirm the bug on Firefox. Does it also happen on https://mozilla.github.io/pdf.js/web/viewer.html?

**Comment by stephanrauh** [comment]
Oh, it does happen in the Mozilla demo, too. At least using my copy of Firefox. @timvandermeij Does this ring a bell? Have you seen this before? Does it happen on your machine, too?

![image](https://user-images.githubusercontent.com/3045767/112389798-9df6b780-8cf5-11eb-9985-bdd51942bcc2.png)

**Comment by timvandermeij** [comment]
Yes, but it's intermittent and most likely an upstream Firefox issue instead of a PDF.js issue. Sometimes the print preview renders immediately and sometimes it shows up blank first, and when you scroll one or two pages all of them render all of a sudden.

I do know that printing is currently being developed more actively (finally, since this has historically been one of the worst browser features to control from an application). This print dialog is new, more printing APIs are being implemented so applications have more control over the output and on the PDF.js side we're seeing some printing-related patches lately as well from upstream Firefox developers, so fortunately it's improving.

As for this bug, I'd recommend reporting this upstream to Firefox in Bugzilla since this really looks like a browser bug given its intermittent nature: https://bugzilla.mozilla.org/

**Comment by stephanrauh** [comment]
Thanks a lot, Tim!

**Comment by stephanrauh** [comment]
@ThicoMart Did you already open a ticket in Bugzilla?

**Comment by rekna1** [comment]
has similar issue even with latest 9 version... in my case printpreview only showed first page. solved it by
`
#printContainer {
    position: absolute;
}
`
which resolved the problem in all browsers for me
