### ISSUE TITLE
Comment's date time not rendered correctly when application hosted in IIS(windows server).

### ISSUE THREAD

**Issue by ditiumdev1** [stephanrauh/ngx-extended-pdf-viewer#689]
**Description:**
I'm trying to display the PDF document with comments. It's displaying the comment with date correctly in my local environment. 
But when I host the angular application in IIS server VM, the date and time of the comment is not rendering correctly.  

From the console logs I could see that it's unable to get the localization keys. The windows server locale is English(United states). 

**Version info**
7.3.2

**Desktop** 
Google Chrome - Version 88.0.4324.190 (Official Build) (64-bit)

**Screenshots**
The comment popup

![image](https://user-images.githubusercontent.com/78896870/110908897-6a597c00-834a-11eb-9cb3-f6445b090e95.png)

Rendered HTML

![image](https://user-images.githubusercontent.com/78896870/110899903-daf99c00-833c-11eb-9795-10e2b9febb06.png)

Warning in console

![image](https://user-images.githubusercontent.com/78896870/110908788-439b4580-834a-11eb-9f75-93b998ed34c1.png)

**Additional context**

Please refer to the missing localization keys here
https://github.com/mozilla/pdf.js/blob/master/l10n/en-US/viewer.properties

Let me know if you have any further questions. Thank you in advance for your help.

**Comment by stephanrauh** [comment]
Does your assets folder contain the translation files? Does the same error occur if you're using `ng serve`?

As a workaround, you can embed the English translation file as an Json object in your HTML code. Here's an excert of the README.md file describing your options:

## Internationalization
<details>
  <summary><b>Expand to learn how to translate ngx-extended-pdf-viewer to 120+ languages</b></summary>


### Slow default way

If you add the translation files to your project as described above in step 3, the PDF viewer uses the browser language setting to determine which language to load. First, it loads the `locale.properties`, scans it for the desired language files, and loads the language file from the corresponding folder. That's two additional HTTP calls. That's slow, and it may even lead to errors if the network is already congested loading other resource files.

Don't forget to set the attribute `useBrowserLocale="true"` if you follow this approach.

### Slow way with custom translation files

If you want to use the slow way, but prefer to load the language files from a different URL, add a link to your application like so:

```html
<link rel="resource" type="application/l10n" href="https://www.example.com/locale/locale.properties" />
```

In this case, don't set `useBrowserLocale` (or set it explicitly to false).

### Inlining (aka embedding) the language files

Alternatively, you can provide the translations as a Json file. This Json file has to be part of an HTML page. That's especially useful if you need only one or two languages, because the are loaded a lot faster. To get familiar with this approach, embed the Json file in the `index.html` like so:

```html
<script type="application/l10n">
  {"default_locale":"de","locales":{"de": ... }}
</script>
```

The folder `node_modules/ngx-extended-pdf-viewer/assets/inline-locale-files` contains snippet files you can simply copy into your HTML page.

_Hint_: You can also add the language definition in another HTML file. The bottom line is that the HTML snippet is already part of the DOM when the PDF viewer is initialized. Cluttering the root index file with the translations is an ugly and inflexible hack, but it works.

If you're using the "inline" approach, don't set `useBrowserLocale` (or set it explicitly to `false`).
</details>

**Comment by ditiumdev1** [comment]
Thanks for the guidelines. 

I've added the value for useBrowserLocale and localeFolderPath to point to the locale folder, and configured the .Net core application to support the .properties files in the IIS. Now I could see the date time and also the warnings are not displayed. Thanks for the help!

Below are the changes I did,

HTML file.

```
<ngx-extended-pdf-viewer [(src)]="src"
                         [textLayer]="true"
                         [useBrowserLocale]="true"
                         [customToolbar]="additionalButtons"
                         (pagesLoaded)="onPagesLoaded()"
                         (pdfLoaded)="onPDFLoaded($event)"
                         (pageChange)="onPageChange($event)"
                         localeFolderPath="./assets/locale">
</ngx-extended-pdf-viewer>
```

Code changes in startup.cs file.

```
            var provider = new Microsoft.AspNetCore.StaticFiles.FileExtensionContentTypeProvider();
            provider.Mappings[".properties"] = "application/octet-stream";
            app.UseSpaStaticFiles( new StaticFileOptions { ContentTypeProvider = provider });
```
