### ISSUE TITLE
Search in smartphone mode

### ISSUE THREAD

**Issue by hunterlan** [stephanrauh/ngx-extended-pdf-viewer#701]
Hi,
My name is Kostiantyn Sharykin. 

I have a quite simple question to you. 

I need to enable search in smartphone mode, but I can't do it. I don't why, but I know, that everything, which has "find", get class "invisible". If I remove this class by browser, it appears and works well. So, the question is: how to remove class "invisible" from find function in a smartphone mode? 

Attached screenshot.

![image](https://user-images.githubusercontent.com/38838841/112452043-db435f80-8d5e-11eb-939d-ae86ebf74f8a.png)

Thanks for PDF Viewer (it's awesome!) and for your work 😁

**Comment by stephanrauh** [comment]
Hi Kostiantyn,

nice meeting you!

Weird. Does the bug occur on smartphones only?

If it doesn't, check the attribute `[textLayer]`. By default, it's false. That's because rendering the text layer costs a lot of performance. The text layer, in turn, is required to support the find functionality.

But what's really weird is you're describing it like the text layer is there - it's just that the find button is hidden on smartphone. So I'm officially confused, and I need more information to help you .:)

Best regards,
Stephan

**Comment by hunterlan** [comment]
> If it doesn't, check the attribute `[textLayer]`. By default, it's false. That's because rendering the text layer costs a lot of performance. The text layer, in turn, is required to support the find functionality.

Yeah, the problem was in textLayer. I set it 'true' and find is appeared. But, as I understood, it should be shown and without this attribute. So, should I provide something?

**Comment by stephanrauh** [comment]
Well, the hidden find button is a very annoying issue. But every time I think about it, I come to the same conclusions: it's better to hide the find button by default because otherwise nobody ever detects the performance boost of omitting the text layer.

However, if you've got a suggestion how to improve the documentation or the README file, I'm alway open for suggestions!

Best regards,
Stephan
