### ISSUE TITLE
Dynamic password don't show the red error message

### ISSUE THREAD

**Issue by vega3000** [stephanrauh/ngx-extended-pdf-viewer#763]
I create my custom password popup (for i18n).
When I set the bad password, I don't have the red error message (like the documentation said), but the password popup from ngx-extended appears.
And I was hoping that the pdfLoadingFailed event will be triggered.

If I put the good password, it's ok.

```html
<ngx-extended-pdf-viewer *ngIf="isPdfVisible" [base64Src]="base64Pdf" [password]="password"
       [useBrowserLocale]="true" (pdfLoadingFailed)="onPdfLoadingFailed($event)">/ngx-extended-pdf-viewer>
```
When I submit mu custom Password:
```TypeScript
    setPassword(password: string, base64Pdf: string) {
        this.isPdfVisible = true;
        this.base64Pdf = base64Pdf;
        this.password = password;
    }
```

There's something wrong in my code ?

Do you think it's possible to raise an event when password failed (in this case, I can do a 3 times retry) ?

Tx

version : "ngx-extended-pdf-viewer": "^9.0.0-alpha.7"

**Comment by stephanrauh** [comment]
Interesting use-case. For some reason, this scenario never crossed my mind, but of course it's a useful feature.

I believe this ticket is an umbrella ticket for three different tasks:
- Setting a wrong password via `[password]` should result in an error message. I consider this a bug.

- It should be possible to limit the number of times you can enter a wrong password. For example, I could implement a feature that allows x wrong password with y minutes, possible with a cool-down phase of z minutes. Of course, that's a weak protection, but even so, it is a protection against brute force attacks. Sounds like a nice enhancement.

- Maybe I can even implement a customizable password dialog. That'd be similar to the custom toolbars. This option enables you to do much more - such as storing the IP address of the hacker on the server, enabling you to rise the protection to another level. Before anybody sues me: if you implement such a thing, you have to ask the user for consent and to make sure the requirements of GDPR and your local law are fulfilled. But that shouldn't be much of a problem, so I consider this a nice enhancement.

At the moment, my top priority is to repair form support because that's blocking the release of version 9.0.0, so please bear with me if I need some time to implement the bugfix and the features. Luckily, it sounds like an easy task, so I'm likely to address your issue soon.

**Comment by vega3000** [comment]
Tx Stephan for your quick reply.

I'm very interesting by your idea of the cool-down phase.
About the custom password dialog, if you eventually go there, the best thing, I think, is to have a customizable label for i18n, and css too. Why css ? Because, in a my concrete case, I code for a PWA, and the password popup is very little on a mobile device.
It's why I suggested a event if password is wrong to have my custom popup. Maybe the event can be the first the step, maybe it's easy to have css, You will know ;)

Thank you

**Comment by stephanrauh** [comment]
To my surprise, it was easy to implement the custom dialog but hard to implement the other feature. So I've decided to add an option to register a custom dialog without implementing the error message or the cool-down phase.
