### ISSUE TITLE
Search content not working in specific codument

### ISSUE THREAD

**Issue by gajeravijayb** [stephanrauh/ngx-extended-pdf-viewer#80]
Hello
We faced issue in search content in bellow attached document 
Can you please verify me and look on that why search content is not working?
In case of search any content will not response and will hang browser tab.

And other document when we click on search and enter content will hang for several seconds in first time after will work

Thanks
[asic_test_eBook_v1.02.pdf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/3223339/asic_test_eBook_v1.02.pdf)

**Comment by stephanrauh** [comment]
Confirmed. The same document works fine with https://mozilla.github.io/pdf.js/web/viewer.html. Weird!

**Comment by stephanrauh** [comment]
@timvandermeij @Snuffleupagus This bug confuses me a lot. I've updated to pdf.js 2.2.199, and the bug is still there. Along the way, I modify the files viewer.js and pdf.js a little, but the changes have nothing to do with the search function. Nonetheless, you can reproduce it on https://pdfviewer.net/simple. Opening the same file on https://mozilla.github.io/pdf.js/web/viewer.html doesn't cause problem.

Steps to reproduce:
- download the test file mentioned above
- open it in the PDF viewer
- open the find dialog
- type any key.

On https://mozilla.github.io/pdf.js/web/viewer.html the first search result shows after a few second. On my demo https://pdfviewer.net/simple there seems to be an infinite loop.

The only differences I can think of are
- minification (Angular minifies the files automatically)
- the build process (I'm using "gulp generic" and take the files from `/build/generic`)

**Comment by timvandermeij** [comment]
It looks like the difference is that the default PDF.js viewer searches and renders only the text layers of all pages, whereas your viewer appears to render all pages _completely_, i.e., also the non-text layers such as the canvases themselves. This causes a lot of CPU usage, at least in Firefox with which I test. Most likely this is caused by an integration mistake with regards to the viewer and/or the PDF find controller, so I would suggest to use `git bisect` or start with the working default PDF.js viewer and applying your changes on top of it in small chunks until it breaks to find out where the issue is.

**Comment by stephanrauh** [comment]
@gajeravijayb @timvandermeij After a long time, I've finally got an idea what's going on. It seems to be a weird Angular problem. Instead of executing the timeout, Angular gets caught in an infinite loop. More precisely, it looks like an infinite recursion. I've tried to run the code outside Angular's change detection, but that didn't help.

Here's the code that should be executed but isn't:

```javascript
executeCommand(cmd, state) {
      ...
      if (cmd === 'find') {
        this._findTimeout = setTimeout(() => { // this line is executed
          this._nextMatch(); // but this line is never reached

          this._findTimeout = null;
        }, FIND_TIMEOUT);
      } else if (this._dirtyMatch) {

```

**Comment by stephanrauh** [comment]
@gajeravijayb I just found out that the search function does work, it just takes roughly four minutes to respond. After that, it's fast. I still suspect that pdf.js is slowed down by Angular, but currently I'm clueless how to avoid that. 

I'll close the ticket now because the library works well with smaller PDF files. Nonetheless, I hope to find out what's going on, one day or another!
