### ISSUE TITLE
pdf render

### ISSUE THREAD

**Issue by adamabdulaev** [stephanrauh/ngx-extended-pdf-viewer#842]
I apologize in advance for the large number of questions (this is the third in the last few weeks). But I hope for your help)). I can't find where exactly in the library the PDF document is rendered? I have a json object that stores links to videos and PDF files. 
```typescript
    document = [
      {type: 'file', url: 'src/assets/pdf/1.pdf'},
      {type: 'file', url: 'src/assets/pdf/2.pdf'},
      {type: 'file', url: 'src/assets/pdf/3.pdf'},
      {type: 'file', url: 'src/assets/pdf/4.pdf'},
      {type: 'file', url: 'src/assets/pdf/5.pdf'},
      {type: 'file', url: 'src/assets/pdf/6.pdf'},
      {type: 'video', url: 'https://www.youtube.com/watch?v=tB-MEWncEkA'},
    ];
```
My task is to render the pdf mixed with the video, for this I am going to render each pdf page as a separate document.But I can't figure out exactly where you are rendering the files in the library to change this. I would be glad to receive any information.
Screenshot of what i am going to do.
![image](https://user-images.githubusercontent.com/84326043/126210835-7d0b0fa9-27f9-4ce9-aab7-ae3b37126f3d.png)
I also tried to make my render implementation, but I cannot figure out where and how I can access `pdfjsLib.getDocument()`. Thank you!

**Comment by stephanrauh** [comment]
Don't worry about asking too many questions. :) I'm glad to share my knowledge!

**Comment by stephanrauh** [comment]
Unfortunately, in this particular case, I don't have much knowledge to share. I don't know precisely how rendering the pages works. I've debugged it several times, so I have a rough understanding, but the sourcecode is very convoluted. I always forget the details. I believe the code you're looking for must be below this line: 

https://github.com/stephanrauh/pdf.js/blob/d083a05720434de29d59de6e413043c022ee1c1a/web/app.js#L1297

I'm just a bit confused because I'm don't see where the canvas is generated.

**Comment by stephanrauh** [comment]
This line looks even more promising:

https://github.com/stephanrauh/pdf.js/blob/d083a05720434de29d59de6e413043c022ee1c1a/web/pdf_page_view.js#L760

**Comment by adamabdulaev** [comment]
> This line looks even more promising:
> 
> https://github.com/stephanrauh/pdf.js/blob/d083a05720434de29d59de6e413043c022ee1c1a/web/pdf_page_view.js#L760

I am trying to import pdfjs in angular 11 like this.
import * as PDFJS from 'src / assets / pdf-2.9.149.js';

But I was getting an error while building. Googling, it seemed to me that the problem is that angular 11 is using webpack 4. I updated webpack to version 5 and then angular using ng update. But now I get the error from the second screenshot. Have you encountered such a problem?
![image](https://user-images.githubusercontent.com/84326043/126330782-c2a724c5-e83c-4289-bb21-43ce98227d35.png)
![image](https://user-images.githubusercontent.com/84326043/126331869-9b270bb6-bd1a-481b-9e8a-9c1ca4938ad5.png)

**Comment by stephanrauh** [comment]
I'm using a different approach, so I didn't run into this problem. But you might want to have a look at https://github.com/VadimDez/ng2-pdf-viewer. This is another fine PDF viewer using the `import` statement. The author has run into a couple of problems because TypeScript (or Angular?) doesn't support the module system used by pdf.js. Or rather, it used to support it, but nowadays it want to do it differently.

Truth to tell, I'm happy with simply adding `pdf-2.9.149.js` to the scripts section of the `angular.json` file. It's less elegant, that's for sure. But it matches the way pdf.js is meant to be used. I'm afraid you can't stop pdf.js from polluting the global namespace, so there's no advantage to using the `import` statement. I also wonder what tree shaking does. Maybe it removes important parts of pdf.js when you're `import`ing it?

**Comment by stephanrauh** [comment]
I'll close this ticket now because I didn't hear anything from you for almost a month. Don't hesitate to add your questions here - I'm still listening to this channel.
