### ISSUE TITLE
Disable embedded print script

### ISSUE THREAD

**Issue by severinkl** [stephanrauh/ngx-extended-pdf-viewer#843]
**Is your feature request related to a problem? Please describe.**

PDFs can carry embedded scripts. ​

E.g. The following embedded script opens the print view when accessing it: [image](https://user-images.githubusercontent.com/22167134/126455179-967a7c2a-2bcb-40e5-9ef2-a91fd626c367.png)

Example PDF:  [call_print_action.pdf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/6854160/call_print_action.pdf)

Steps to reproduce: Open the example PDF in the [showcase](https://pdfviewer.net/extended-pdf-viewer/multiple-documents).

I would like to disable the embedded script.

**Describe the solution you'd like**

Implementing a `@Input() enableScripting: boolean` to regulate the embedded scripts solves the problem.

**Implementing the solution**

The default Mozilla PDF viewer offers a `pdfjs.enableScripting` flag. However I was not yet able to find that same flag in the API.

**Additional context**

Pose those embedded scripts a security risk (XSS)? Is embedded JS actually always executed? I rummaged through Mozilla's PDF viewer and stumbled across the following issues. It seems like there is no security risk involved for the API.

- https://github.com/mozilla/pdf.js/issues/12709
- https://github.com/mozilla/pdf.js/issues/11458

**Comment by stephanrauh** [comment]
Good idea. I'm going to add your `@Input()` to the version I'm currently preparing.

**Comment by stephanrauh** [comment]
@timvandermeij Is there any documentation of the pdf.js scripting engine? From what I've seen, I'm pretty sure that scripts embedded in PDF files are no security risk because you guy have put them into a sandbox - but that's just guesswork. Can you say something about XSS attacks?

**Comment by timvandermeij** [comment]
The scripting code is indeed always run in a sandbox to avoid security risks with executing arbitrary JS code in PDF files. The sandbox is called QuickJS and it's integrated in PDF.js to run the JS code in there and from the sanbox get the results from the execution and use those for e.g., XFA support.

@calixteman knows most about the sandbox integration, but since security was built in from the start since that was the primary concern with this feature I'm pretty sure that's handled. Maybe Calixte has time to confirm this.

**Comment by calixteman** [comment]
Quickjs is a JS engine written in C:
https://github.com/bellard/quickjs
and we compiled it in WASM using:
https://github.com/mozilla/pdf.js.quickjs
and finally we get this js code:
https://github.com/mozilla/pdf.js/blob/master/external/quickjs/quickjs-eval.js
Then we run the sandbox using:
https://github.com/mozilla/pdf.js/blob/master/src/pdf.sandbox.js

At building step, all the code to implement pdf apis (https://github.com/mozilla/pdf.js/blob/master/src/scripting_api/initialization.js) is bundled in one big string and this one will be injected in the sandbox at runtime:
https://github.com/mozilla/pdf.js/blob/7b6767d415919b8a7360f7d8adeb2a7ab76bcb5a/src/pdf.sandbox.js#L61

Data are passed to the sandbox as strings so it means that objects are passed using `JSON.stringify`:
https://github.com/mozilla/pdf.js/blob/834a638aad900f511836851c5b148ed6f58b2a7d/src/pdf.sandbox.js#L28
and the sandbox outputs some strings which are passed to `JSON.parse`:
https://github.com/mozilla/pdf.js.quickjs/blob/7428b6dba4aa599a2bce95b0ced4c21af65ef1e8/src/myjs.js#L26
then the data (as objects) are passed to different functions:
https://github.com/mozilla/pdf.js/blob/834a638aad900f511836851c5b148ed6f58b2a7d/src/pdf.sandbox.external.js#L71

the main used function is:
https://github.com/mozilla/pdf.js/blob/834a638aad900f511836851c5b148ed6f58b2a7d/src/pdf.sandbox.external.js#L153
to update html elements after executing callbacks.

So at the end the sandbox is a JS interpreter executed by an other JS engine (v8, spidermonkey, ...) which has no access to the main window object (or whatever object).
Even if someone finds a way to get an access to window object, this object will go through `JSON.stringify` to be used in the sandbox so I'd say that nothing is problematic here.
By design, there are no access to the network, so even if a script is used to make some computations, no data can be sent

The only real possibility to attack would be to find a bug in quickjs itself (which should not be that hard), use it to exploit a bug in WASM interpreter and then try to get an access to whatever...: I'd say that in general it isn't more risky than a "normal" script on a "normal" website.

If you've any idea to make an exploit, please file a bug or if you think that something is terrible don't hesitate to send a private email to one of the pdf.js maintainers.

If something is not clear, please ask for questions.

**Comment by stephanrauh** [comment]
Hi @calixteman, whow, such an exhaustive and useful answer! Thank you very much!

Do you happen to know if someone has already blogged about the pdf.js scripting engine in general or pdf.js scripting security in particular? If not, that'll be my leisure time project next week. You've put so much effort into this project that I think it's high time to tell the world about it!

Best regards,
Stephan

**Comment by calixteman** [comment]
For now, afaik, nothing has been written.

And to be clear, the pdf built-in viewer in Firefox doesn't use the quickjs-based sandbox but it uses its own sandbox, see
https://github.com/mozilla/pdf.js/issues/13284
for more information (and few more info here: https://security.stackexchange.com/a/248985).

**Comment by stephanrauh** [comment]
I've implemented your feature and I've added a demo to the showcase. However, I didn't release either yet because along the way I stumbled upon #868.

**Comment by stephanrauh** [comment]
@severinkl You test document isn't perfect to show that disabling JavaScript works. pdf.js has a fallback algorithm detecting auto-prints implemented by JavaScript. It doesn't run your JavaScript, but it prints the document nonetheless. You can only spot the difference if your embedded JavaScript passes options that make the print look differently.

**Comment by stephanrauh** [comment]
Your feature has landed with version 10.0.0-alpha.5. You'll find the documentation at https://pdfviewer.net/extended-pdf-viewer/scripting.
