### ISSUE TITLE
how formDataChange works

### ISSUE THREAD

**Issue by adamabdulaev** [stephanrauh/ngx-extended-pdf-viewer#875]
Hi Stephan! I am studying your component and now my task is to get the data entered into the inputs, selects etc. As I understand it, formDataChange is responsible for this in your component (please correct me if this is not the case). I am trying to figure out how you implemented this functionality, since I did not find such a possibility in Pdf.js. Did you change the source code of the pdf.js library? Thank you in advance for your response!

**Comment by stephanrauh** [comment]
Yes, I've modified the source code of pdf.js. `(formDataChange)` was one of the feature that seemed simple at first but turned out to be a huge pile of work. :)

You find the changes I've made if you clone https://github.com/stephanrauh/pdf.js and scan for "#718".  To implement `[(formData)]`, I only had to modify two files (annotation_storage.js and annotation_layer.js).
