### ISSUE TITLE
Zoom on first and last page breaks center-alignment

### ISSUE THREAD

**Issue by barnewsapp** [stephanrauh/ngx-extended-pdf-viewer#881]
**Describe the bug**
pageViewMode="single"
spread="even"

If you zoom in on the first or last page (in a PDF with even page count), the page is no longer centered. 
The same happens if you change zoom mode til page-fit or auto. 

**Version info**
Latest from git, PDF viewer: ngx-extended-pdf-viewer running on pdf.js 2.10.549

**Desktop (please complete the following information):**
 - Browser: Google Chrome

**To Reproduce**
Let me know if you need a reproducer? 

If you really can't provide me a reproducer, please tell me how to reproduce the behavior:
1. Go to https://pdfviewer.net/extended-pdf-viewer/page-view-mode
2. Go to first page i the PDF.
3. Change to even spread mode 
4. The page is not centered

**Demo PDF file**
I'll attach my 8-page demo PDF. 
[Page 1-8.pdf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/7013217/Page.1-8.pdf)

**Screenshots**
![Peek 19-08-2021 11-03](https://user-images.githubusercontent.com/67910734/130043159-c007032d-a819-40d2-b6da-426ea3cbaee5.gif)

**Additional context**
BONUS BUG! 
I probably should open a separate bug-report on this but I saw it just now when making the screencast. 
In even spread mode, if you go to the last page and click the previous-page button the viewer only show one page. 
If you to page 1 and forward again the problems disappears. 
I think the problem is related to how display: block | inline-block is set.

**Thank you!**

**Comment by stephanrauh** [comment]
You're keen-eyed! :)

**Comment by barnewsapp** [comment]
hehe, thanks. 
I'm looking forward to get to know the code-base more and can fix small issues like this myself and send pull requests instead of bug-reports :-)

**Comment by stephanrauh** [comment]
Basically, there are two source code. ngx-extended-pdf-viewer is a thin layer above pdf.js. I'm pretty sure it's easy to tinker around with the ngx-extended-pdf-viewer source code. Maybe it's a bit scary because it's  a single giant class. According to the clean code initiative, that's bad design. However, I don't see how to split the "god class" into smaller chunks without making it worse, so I keep it that way. :)

The other source code is pdf.js itself (or rather, my fork of pdf.js). That's high-quality sourcecode, but almost everything is done asynchronously, so it took me a lot of time to understand it. Plus, the build process is a bit cumbersome because you have to build pdf.js first before you can build ngx-extended-pdf-viewer.

**Comment by stephanrauh** [comment]
The bug was caused by a left-over of my original, clumsy approach.

**Comment by stephanrauh** [comment]
Shipped with version 10.0.0-alpha.10.
