### ISSUE TITLE
It will be cool, if the method 'getPageAsImage' could return image with transparency. I mean if pdf has transparent background. Now it filling with white color

### ISSUE THREAD

**Issue by IvanMilaev** [stephanrauh/ngx-extended-pdf-viewer#916]
Currently, `getAsPage()` always returns an image without transparency, even if the PDF itself has a transparent background. Is it possible to modify the image export to respect transparency?

**Comment by stephanrauh** [comment]
@timvandermeij The author of the ticket refers to a piece of code I've copied and adapted from the pdf.js codebase, so I suppose you've familiar with the code pattern. If not, just ignore my question. :)

```typescript
    const renderContext = {
      canvasContext: ctx,
      viewport: drawViewport,
    };
    const renderTask = pdfPage.render(renderContext);

    const dataUrlPromise = () =>
      new Promise<string>((resolve, reject) => {
        resolve(canvas.toDataURL());
      });

    return renderTask.promise.then(dataUrlPromise);
```

https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/6cde30a31c41397863ede37e17b68b0f6852ace8/projects/ngx-extended-pdf-viewer/src/lib/ngx-extended-pdf-viewer.service.ts#L249

What happens if the PDF file has a transparent background? Does the resulting image have a transparent background, too? If not, how to implement such a feature?

**Comment by timvandermeij** [comment]
I recall this being asked before in the PDF.js repository and it got implemented by a contributor in https://github.com/mozilla/pdf.js/commit/cfc2f36f5c00f17317fe68e1fc74be4566d1767a. Basically you can give a custom background color instead of the default white background color during rendering: see https://github.com/mozilla/pdf.js/blob/master/test/unit/custom_spec.js#L71-L89 and specifically https://github.com/mozilla/pdf.js/blob/master/test/unit/custom_spec.js#L78. It only means that you can set another background, but it doesn't automatically determine it; I don't think there is way to do so in general.

**Comment by stephanrauh** [comment]
@timvandermeij Awesome. Thank you very much! I hope you keep track how many coffees I've already promise to spend you - it must be a huge number. :)

**Comment by stephanrauh** [comment]
According to https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Applying_styles_and_colors#transparency, the background color may even be transparent or semi-transparent. Maybe that approach does the trick.

**Comment by timvandermeij** [comment]
Exactly. I should also have linked the original PR at https://github.com/mozilla/pdf.js/pull/8413 where the author indeed wanted to have a transparent background, so the fourth color component (alpha) can be used for that.

**Comment by stephanrauh** [comment]
I've implemented a prototype. If works with many documents. Some documents bear their own background color, so the custom background color is slightly disappointing. Other documents can be given a custom background colors without further ado.

But: transparency doesn't seem to work yet.  Decreasing the opacity makes the document darker. `rgba(255, 255, 255, 0)` isn't fully transparent, but pitch black.

This is the result of  `background: 'rgba(255, 0, 255, 0.3)'`. The color should be cerise, but I'm afraid these cherries are very ripe:

![image](https://user-images.githubusercontent.com/3045767/134072078-56e7711c-0055-4f86-80e2-4159d64cb609.png)

**Comment by stephanrauh** [comment]
Starting with version 13.0.0-alpha.12, you'll be able to export images with custom backgrounds:

```typescript
await this.pdfViewerService.getPageAsImage(1, scale, rgba(0, 0, 0, 0)); // transparent background
await this.pdfViewerService.getPageAsImage(1, scale, '#FF000050'); // transparent cerise background
await this.pdfViewerService.getPageAsImage(1, scale, rgba(0, 0, 0, 0), '#FF0000'); // replace red background by transparent background
```

However, if an element of the PDF file bears a background color, this background color is not transparent. You can observe this in the demo at https://pdfviewer.net/extended-pdf-viewer/export (once I've updated it). Some texts are transparent, others are not. I didn't find out where this particular background color comes from - but on the other hand, if the author of the file wants to add a background to the text, I shouldn't overrule this.

**Comment by stephanrauh** [comment]
The new version has landed.

Enjoy!
Stephan
