### ISSUE TITLE
Possibility to deactivate given form portion on pdf.

### ISSUE THREAD

**Issue by namblard-sword** [stephanrauh/ngx-extended-pdf-viewer#931]
Hello,

**First of all thank you for your work it'll help a lot.**

However after reading multiple times the documentations and some issues in git, I haven't found any answer to my question which is : Is it possible to deactivate some form and keep some active for a given solution ? 

For instance, a document is to be filled by two users:

- User A must fill his legal information
- User B must fill the contract details such as agreed price etc.

So user A must have form disabled except for his legal part and the opposite for user B.

If there is already such an opened question that I missed I apologize.

Thank you for your time and consideration.

**Comment by stephanrauh** [comment]
You can achieve this by manipulating the DOM tree after rendering.

I believe the `(pageRendered)` event is your friend. It's called each time a page has been rendered. Use it to find your forms and to disable them. You can find the form using a selector like `document.querySelectorAll(".page > annotationLayer > input")`. The details may be wrong because I haven't run the code, but you get the gist. The CSS classes and the structure of the HTML code representing the PDF files aren't likely to change in future, so you can rely on such a query.

AFAIK pdf.js doesn't render a `<form>` tag, so you have to deactivate every input field of the form individually.

That's it in a nutshell. I'll close the ticket now, but I'm still going to listen to this channel. Don't hesitate to ask if you run into trouble!

Best regards,
Stephan
