### ISSUE TITLE
Zoom on a span/div inside textlayer

### ISSUE THREAD

**Issue by masartbenji** [stephanrauh/ngx-extended-pdf-viewer#936]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need to find a span text on pdf

**Describe the solution you'd like**
Actually I reconstruct the textlayer based on xml file. I would like to have a focus on a particular span on pdf, maybe with a 150% of zoom on this span. This span can be located by x,y positions and width and height

**Comment by stephanrauh** [comment]
Sounds exciting - but I'm afraid I can't help you. 

Judging from your question, I assume you're already familiar with the DOM structure of the PDF document. In particular, you're already familiar with internal structure of the text layer.

- Finding a span: I suppose you can implements that as well as I can. Once the text layer has been rendered, it's a simple DOM tree. Or maybe not simple, because the `<span>` can appear at any location, often cutting a word in two. But you can still use the JavaScript API of the DOM of the page, so you should be able to find a `<span>` by it's x/y coordinates.
- Focusing a span and enlarging it: I'd love this feature, too, but you can't implement it without modifying the PDF renderer. It doesn't suffice to make the text layer visible and to resize the `<span>` under focus. You'd also have to resize the corresponding canvas below the text layer. Usually, the text layer remains invisible, so it's the canvas you need to focus. That's certainly possible, but it's beyond my ambition (not to mention my limited leisure time).

**Comment by stephanrauh** [comment]
If I've misunderstood your question, don't hesitate to tell me. Closed tickets can be re-opened. :)

**Comment by masartbenji** [comment]
There is a possible work around  about this functionnality. I can use the find functionnality, that i assume it will go on the good page, then maybe I can make a zoom on certain point like the mouse wheel zoom work. It need investigation of my part.

**Comment by masartbenji** [comment]
@stephanrauh In fact no need of the x,y coordinates of the span, we just need the span, and then we can do span.scrollIntoView. Before to activate the scroll to focus the span, I simply set the page number to the correct page number. Actually the scroll is a bit random, maybe because the text-layer is not completely loaded when I try to scroll on it.

Best regards

**Comment by stephanrauh** [comment]
Ah, I see! I thought of a fashionable magnification gimmick, something like that: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSBeNBqbiWer4f-A_Nta996pEgCt16fxOw-GA&usqp=CAU

Did you already discover the `(textLayerRendered)` event?

**Comment by stephanrauh** [comment]
I suppose you've managed to solve the issue during the last three months?
