### ISSUE TITLE
Allow file:// URLs in Electron apps and Chrome browser extensions

### ISSUE THREAD

**Issue by stephanrauh** [stephanrauh/ngx-extended-pdf-viewer#938]
As discussed in #907, it's almost always a good idea to prevent local file access in a browser application. But ngx-extended-pdf-viewer can also be used in a Cordoba app, an Electron app or a Chrome browser extension. In such a scenario forbidding the local file access is exactly what you don't want to do.

Let's add a option allowing users to disable the protocol check.

**Comment by stephanrauh** [comment]
@chan-dev @muuvmuuv I've tried to write an Electron app accessing a local file. But I didn't figure out how to do it. Can you help me? Either by adding to my reproducer see the commit above) or by sending me a reproducer of your Chrome extension?

**Comment by stephanrauh** [comment]
Note to myself: these files contain a check on the protocol of the URL:

- display_utils.js#isValidFetchUrl()
- fetch_stream.js#PDFFetchStream()
- network.js#constructor()
- util.js#_isValidProtocol()

However, currently the "file not found" error occurs in network.js#request(). The http status code is 0.

**Comment by muuvmuuv** [comment]
@stephanrauh Hey, apologies for the delayed response, we haven't got any further with the cordova-windows -> electron migration and added it back to the backlog due to some other major issues. We can keep that open for the time, and I will come back to it as soon as we get back to work on the migration. Our app is massive, so its takes a lot of time.

We are using Ionic with @capacitor-community/electron. I think there is an example somewhere which you could download and run.

**Comment by stephanrauh** [comment]
OK, I'll wait! It'd be great if you could boil down your large app to a tiny reproducer, or if you can debug the problem yourself, using `[minifiedJSLibraries]=false` and the pointers I've mentioned above.

**Comment by stephanrauh** [comment]
Let's close the ticket for the moment. We can re-open it when you send me reproducer.
