### ISSUE TITLE
High CPU usage for huge 2 way binded pdf forms

### ISSUE THREAD

**Issue by abdulaleem1** [stephanrauh/ngx-extended-pdf-viewer#948]
Hi Stephen, I am using the pdf to fill few forms were each form has hundreds of fields. I do not really need a 2 way binding approach as user will be directly filling the form. but I am working on a typeahead to show a list as the user types and set the value when user selects it from the list. 

Is there a way I can use the setFormValue and getFormValue methods defined in window instead of going the 2 way binding route as it shoots the cpu usage  by 30%+ ?

**Comment by stephanrauh** [comment]
That's an unexpected side-effect. The brute force solution is to set the two function to dummy functions in an `AfterViewInit` handler:

```typescript
      (window as any).getFormValue = (key: string) => undefined;
      (window as any).setFormValue = (key: string, value: string) => {}
```

I'll add an option to opt-out of two-way-binding in one of the next versions.

**Comment by bruceRuan1** [comment]
Hi Stephen, this is Bruce, I am working with @abdulaleem1 on our client project. Firstly, thank you for your instant response, but I guess we need to clarify the question just a little bit more, so here's what we are expecting:

1. we are trying to implement a typeahead search functionality for one of many pdf fields, since your library does not offer such feature.
2. my initial thought is to create an overlay div on top of the pdf-extended-viewer component, which after some hard work, it is working as expected.
3. so as mentioned in point 2, the drop down layer can be opened/displayed whenever user types in one of the input fields, but I'm struggling with syncing the data with your component and of course ideally should sync with the input field (annotation layer). To elaborate more, I am using two-way binding for formData, my component is responsible for updating the formData internally, but looks like I have to **clone the formData object after updating one of its fields**, since your library uses **`ChangeDetectionStrategy.OnPush`**. A code snippet looks like: `    this._formData[this.fieldName] = selected;     this.formData = JSON.parse(JSON.stringify(this._formData));`.  which is not working as expected, inside your code base, the simpleChange object exceptionally captures same field value for previousValue and currentValue. I suppose this is why it prevented the user selection value to be updated in the annotation storage, but I haven't been able to figure out why. 

We sincerely hope you could provide us with some information or suggestions as this has become a blocker for the project, thank you in advance!

**Comment by stephanrauh** [comment]
@timvandermeij Time and again, I'm fascinated by what people do with pdf.js and ngx-extended-pdf-viewer, and I want to share this fascination with you. The majority of the ticket is about my library - just ignore it, unless you're curious. The exciting bit that might be a thing for pdf.js, too, is that Bruce and Abdula (guessing that's their names - which I cannot know) have implemented a type-ahead search on top of pdf.js.

How cool is that?

**Comment by stephanrauh** [comment]
@bruceRuan1 @abdulaleem1 I wonder if adopting the `OnPush` strategy was an accident. At the time, I tried to solve a performance problem, but in hindsight, I was lurking in the dark (https://github.com/stephanrauh/ngx-extended-pdf-viewer/commit/d62c229298ea48a7dddbac5484092b6ed6ab2950).

**Comment by stephanrauh** [comment]
I'm not sure whether it's an option to you, but you since you've read and understood so much of the source code, you could update the annotation storage directly. `updateFormFields()` implements it for the entire form, and you could break it down to individual fields. If that works, I guess I could also offer an `AcroFormService` allowing you to read and write fields of the form without having to rely on the change detection engine.

Something along these lines:

```typescript
public updateAcroFormField(key: string, value: any): void {
  const field = document.querySelector("input[name='" + key + "']") as HTMLElement;
  if (field instanceof HTMLInputElement) {
     storage.setValue(field.id, key, { value: formData[key], emitMessage: false });
     field.value = value;
  } else if ( /* countless special cases :) */ {
     ...
  }
```

**Comment by bruceRuan1** [comment]
@stephanrauh with my limited knowledge, I can still imagine why OnPush would be necessary for a large document, however if what we mentioned is an unexpected side effect.... Okay, I just read your latest message, the AcroFormService approach looks like a good solution for our use case, one quick question I can think of now is, if you take out the [formData] binding, can we still access the entire pdf (data across multiple pages) anytime we'd like? As I can foresee that sometime in the future, we'd need the functionality to wrap every data field and send it to our db (a saving functionality).

**Comment by bruceRuan1** [comment]
I guess that's not a problem, please correct me if I am wrong though, whenever user types in any field, we'd be able to retrieve latest data from `(formDataChange)` event, in that case we can keep a local copy of the `formData`, and update that in the callback.

**Comment by stephanrauh** [comment]
Exactly. That's the idea. You care about sending your data from Angular to the PDF file yourself and let my library care about the other direction. I'm looking forward to your success story! :)

(Of course, if the idea doesn't work, I want to know that, too!)

**Comment by bruceRuan1** [comment]
Are you planning to update the library with AcroFormService  anytime soon?

**Comment by stephanrauh** [comment]
Good question. At the moment, I'm waiting for your feedback. At the moment, I'd like to address the tickets I've label "version 11" first: https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues?q=is%3Aopen+is%3Aissue+label%3A%22Version+11%22

On the other hand, if you report the direct access to pdf.js solves your problem, I'm ready to increase to priority of the `AcroFormService`. Come to think of it, you can also contribute it yourself. Implementing the direct access to pdf.js amounts pretty much to implementing the `AcroFormService`.

**Comment by bruceRuan1** [comment]
Yeah, understood. We don't mean to push you or anything, if this approach doesn't work in the end, we can just look at some other options, but just an FYI, we did experiment with the `storage.setValue()` a little bit, it looks like a success at first, we were able to update input value with the user selection from the dropdown,  but it seems when the input element receives a focus event, the value resets itself. We are not quite sure why that is happening at the moment,  below I am providing a text-form illustration: 

user types in input field: "n" => from dropdown user selects one option => input field value updated to "New York" => now if we click on the input field, it resets back to "n"

**Comment by stephanrauh** [comment]
Don't worry about pushing me. As long as you're pushing, I know you're still using my pet library!

At the moment, I have no idea why getting the focus resets the field. Maybe it calls `window.getFormValue()`?

**Comment by bruceRuan1** [comment]
I am not sure, but it might have something to do with these lines in pdf.js:

`        element.addEventListener("focus", event => {
          if (elementData.userValue) {
            event.target.value = elementData.userValue;
          }
        });`

But I don't really know what is the userValue used for.

**Comment by stephanrauh** [comment]
I suppose we can close this tickets after waiting three months.
