### ISSUE TITLE
Annotation  Layer. (I need a right hand panel) 

### ISSUE THREAD

**Issue by drpjl** [stephanrauh/ngx-extended-pdf-viewer#986]
Hi 

I am working adding an annotations layer.  I will have my own data structure to store the annotations (I am not modifying the pdf).  I have just implemented the proof of concept for the pen tool which is working nicely by using the PDFPageView object which I get from the page render call back.    I use this to add mouse listeners and render the annotations by drawing to the canvas.  This seems to work fine and I don't think requires any changes to code.

I would also like allow the user to add comments to annotations. This requires an additional right hand sidebar.   I see there is already a feature request for this for another purpose but I don't see why this would not suit my need.

[#899](https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/899)

So I am wondering if this feature is ready in some development branch.  If not I will probably fork my own branch and add it myself.   Or hack the DOM !

Long term it might be nice to have the annotations integrated OR as a separate package ?

**Comment by stephanrauh** [comment]
Sounds like you're working on a cool project! If there's something to share with the community, I'd like to encourage you to do so.

I haven't started working on #899 yet. But I've added the "version 11" tag because it seems to be a popular feature.

Does this answer your question? If so, I'd like to close the issue.
