### ISSUE TITLE
Error in Cordova App:  Uncaught SyntaxError: Unexpected token .

### ISSUE THREAD

**Issue by pilz97** [stephanrauh/ngx-extended-pdf-viewer#991]
Hi,

i am using version 10.1.0.
In the browser everything works finde but in the cordova app i get an error:
Uncaught SyntaxError: Unexpected token .

The Error is thrown in Line 2280:
![image](https://user-images.githubusercontent.com/42172207/138407128-3ec36e38-f37a-4e31-8503-7b37bc90fa03.png)

I read in an other issue that .? is causing the issue, but i don't understand why, because i am also using the ? operator in my code (and there are no problems)

Is the issue [https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/657](url) only fixed for "bleeding-edge" mode? 

Has anyone an idea how to fix that issue?

Thanks.

**Comment by stephanrauh** [comment]
Well... your `try` won't ever raise an exception because it's compiled by the TypeScript compiler. I know that, because I've tried to do the same. The key to success is to implement the try-catch-block in JavaScript and to make sure this JavaScript code isn't transpiled. At the moment, the only way to do so I know is to publish a library on npm. I can do that, but it feels a bit embarrassing to create an npm library for such a simple task.

Do you happen to know any alternative?

**Comment by LAlves91** [comment]
Hi @stephanrauh!

I don't have a full knowledge of ngx-extended-pdf-viewer's codebase, but wouldn't be possible to use the same approach used to load PDF.js? Adding a Javascript function as an asset to the library and loading it dinamically?

**Comment by stephanrauh** [comment]
@LAlves91 Good idea. This approach works. It's an additional HTTP request, but I'm afraid ngx-extended-pdf-viewer isn't the fastest library in the Angular universe, anyways, so I'm going to get away with one extra HTTP call.

Thanks for the hint!

**Comment by LAlves91** [comment]
@stephanrauh no problem at all! I was gonna send a pull request, but I thought it would be better to run the idea by you first, since it would be my first PR!

I searched for an alternative, but it seems there’s no way to tell tsc to not transpile something…I even tried creating a js file and use the allowJs config, but then the function was transpiled…

**Comment by stephanrauh** [comment]
Awesome! Pull requests are always welcome!

To be honest, I'm a bit confused about the transpilation business. I faintly remember I used to include native JavaScript files in an Angular 2 project. But maybe I remember wrong.

**Comment by LAlves91** [comment]
@stephanrauh 

I've also seen these kinds of situations...one of the Angular projects I work on used to have a "dock menu" component, using a Fisheye function from jQuery.

The thing is: I think these scripts were vanilla JS to begin with, so no transpilation would occur...also, they were added to angular.json's "script" section, maybe there's a difference in the way Angular process these. Anyway, this pattern ends up resulting in the same behaviour as loading the script as an asset.

From my research here, I've seen a few open feature requests in Typescript's repo regarding "conditional transpiling", but it doesn't seem like it'll be implemented anytime soon (if at all).

I have a request: after I send the PR, do you mind if I port this "Feature Detection" logic to ng2-pdf-viewer? I actually use their viewer here (crazy feature required from my project's business team, to show all related PDF/HTML documents in a infinite scroll way - sometimes hundreds of them...), and I think it would be a nice optimization!

Thank you!

**Comment by stephanrauh** [comment]
Go for it! I like Vadim's ng2-pdf-viewer viewer. I've even added it to my showcase. It's a different use-case, so there's little to none competition, anyways :)

BTW, if it helps, I can support your PR by sending an email to Vadim.

**Comment by LAlves91** [comment]
Hi @stephanrauh !

I have an idea to run by you: I did some research here and came across a small library called [secure-eval](https://www.npmjs.com/package/secure-eval). Basically, it runs a code string like the eval() function, but in an isolated iframe, returning the result as a Promise.

So, we could use it to run the following code:

```
const opChainingEval = {
  opChainingSupport: true
};

try {
  window.parent.postMessage({
    type: 'secure-eval-iframe-result',
    opChainingEval?.opChainingSupport
  }, '*');
} catch {
  window.parent.postMessage({
    type: 'secure-eval-iframe-result',
    false
  }, '*');
}
```
As the code is passed as a string parameter, tsc won't transpile it. We'll get the expected result in a simpler way without the possible security risks eval() would bring. What do you think?

**Comment by stephanrauh** [comment]
It's definitely a great idea. Thanks! Nonetheless, indulge me in playing advocatus diaboli. 30K+ downloads per month make me shy away from risks. What might go wrong?

- What about the Content Security Policy? Does your approach play well with CSP?

- Many architects and developers hate iFrames. That's not always rational. However, there's already a great PDF viewer library out there using iFrames (https://www.npmjs.com/package/ng2-pdfjs-viewer), and the key difference is the other library is using iFrames. Maybe - just maybe, I'm not sure - it's a bad idea to blur this difference.

- Some time ago, I experimented with `eval()` and with a more sophisticated approach. To my surprise, no matter what I tried, there was always a user running into problems. This kind of experience makes me very careful.

Let's do it like this: please submit two pull requests. The first PR uses your first suggestion. I'm going to merge it first because I don't expect any problem (apart from the small performance penalty). The second PR uses secure-eval. I'm going to merge it when I'm planning the next major version. So it's going to be an alpha version for an extended period of time, giving the community enough time to test the new feature thoroughly.

Does this sound like a plan?

**Comment by LAlves91** [comment]
Hey @stephanrauh 

First things first...thank you for taking the time answering these suggestions with this kind of depth! I really appreciate it (and it makes me grow a lot as a developer)!

That's a great plan! I'll work on the first PR, to quickly resolve this issue. Then I'll research more about the points you've made and run it by you. Who knows, maybe by then there will be an easy way to avoid tsc transpiling everything!

Cheers!

**Comment by LAlves91** [comment]
@stephanrauh 

I've tested the fix (actually, I've published a small lib with the checker function)...no go. As it happens, if the browser doesn't support optional chaining, it throws an 'Uncaught SyntaxError', which doesn't work with try/catch. Apparently, you can't catch syntax errors.

Now I think there are two choices:
- Detect browser version (manually or through a library, like [platform.js](https://github.com/bestiejs/platform.js/) or [bowser](https://github.com/lancedikson/bowser)), matching the information with [support data](https://caniuse.com/?search=optional%20chaining).
- Use eval() (it's actually the described way to catch a SyntaxError on [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError#catching_a_syntaxerror)).

Both options have upsides and downsides. Version detection would keep the ngx-extended-pdf-viewer away from eval(), but it would create a dependency on navigator.userAgent, which is a bad practice (Chrome is actually in the process of deprecating this property) and can be unreliable sometimes. Using eval() would give a more reliable and direct answer to optional chaining support, but...its eval() hahahh

**Comment by stephanrauh** [comment]
I've already tried `eval()`. I gave it up for a reason. It didn't work on every machine. As far as I remember, it fails if you're using CSP, but I'm not sure.

Browser detection is a great approach. I just couldn't wrap my head around it. There's the CanIUse project, which is also available on npm: https://www.npmjs.com/package/caniuse-lite and https://www.npmjs.com/package/caniuse. But I didn't find out how to use it.

Finally, there's the `Uncaught SyntaxError`. Are you sure you can't catch it? I think I already caught it successfully, and there's a StackOverflow answer claiming the same: https://stackoverflow.com/questions/66288922/check-if-optional-chaining-is-supported/66288923?noredirect=1#comment123207777_66288923

Please give that solution a second try, because it'd be the most elegant and most reliable solution I can think of!

**Comment by LAlves91** [comment]
Hi @stephanrauh ,

I've sent [PR 1009](https://github.com/stephanrauh/ngx-extended-pdf-viewer/pull/1009). I've explained my approach in more details there, but basically, I managed to avoid eval() by creating an HTMLScriptElement dinamically, in order to keep the main thread from crashing when there's a SyntaxError.

I've tested the code in the following browsers:

- Chrome (most recent);
- Firefox (most recent);
- Edge (most recent);
- Chromium v78 (last version without native optional chaining support);
- Firefox v73 (last version without native optional chaining support).
It worked as expected! If there are any changes you think are interesting to add to my PR, just let me know!

Cheers!

**Comment by stephanrauh** [comment]
Your bugfix has shipped with version 11.0.0-alpha.1.

I think we can still tune it a bit. There's a duplicate check for `Promise.allSettled`, and in some cases, there's no need to load the `opchaining.js` because it's already obvious the browser doesn't support optional chaining:

```typescript
  private async needsES5(): Promise<boolean> {
    const isIE = !!(<any>window).MSInputMethodContext && !!(<any>document).documentMode;
    const isEdge = /Edge\/\d./i.test(navigator.userAgent);
    const isIOs13OrBelow = this.iOSVersionRequiresES5();
    let needsES5 = typeof ReadableStream === 'undefined' || typeof Promise['allSettled'] === 'undefined';
    if (needsES5 || isIE || isEdge || isIOs13OrBelow) {
      return true;
    }
    return await this.checkOpChainingSupport();
  }
```

**Comment by LAlves91** [comment]
@stephanrauh awesome!

Your changes make a lot of sense, and the code looks much better like this! It's just a shame there isn't a simpler way to check for this kinds of stuff (a navigator.esVersionSupport or even a custom property for each feature implemented).

Two suggestions:
1. I think the isIE check can be eliminated, since typeof ReadableStream === 'undefined' and typeof Promise['allSettled'] will already fail with Internet Explorer;
2. Maybe iOSVersionRequiresES5() should be erased too. I believe it was added as a temporary fix for problems with optional chaining support, right?

**Comment by stephanrauh** [comment]
I'll close the ticket now. The algorithm can still be improved, but on the other hand, the extra checks don't hurt, and maybe they detect an incompatibility we didn't think of.

**Comment by stephanrauh** [comment]
Yes, I think so.
